// Code generated from legacy source data. DO NOT EDIT BY HAND.
// 生成方式：一次性 Python 脚本解析旧仓库 Kotlin 数据表机械转换（脚本用完即删，未入库），
// 字段与 Kotlin 一一对应（canonical/variants/characters[].canonical/aliases），中文原文保留。

// builtinGroups 是内置出处/角色检索表，共 130 个 SourceGroup（游戏/动漫/影视，仅收录
// 女性角色——本项目核心场景），源自旧项目（绮梦影库 App）：
//
//	app/src/main/java/com/qimeng/media/ui/album/SourceGroupsData.kt
//
// 迁移授权：docs/DOMAIN_RULES.md §4「内置检索表……迁移时整表翻译」。
//
// 规模勘误：DOMAIN_RULES §4 / 旧 GUIDE_ALGORITHM.md 记"131 个 SourceGroup"，
// 实测源文件数据组为 130（131 次出现含 1 行 data class SourceGroup 定义），
// 本表以源数据保真为准（2026-08-30 转换时核实）。
//
// BUILTIN_GROUPS 更新规范（译自旧 Kotlin 文件头部注释，后续增补逐字遵守四原则：
// 查重优先 / 规范命名 / 别名完整 / 长度降序）：
//  1. 新增前必须搜索确认无重复 canonical 或变体重叠（查重优先）
//  2. canonical 用最通用中文名，不带版本号（铁拳/最终幻想/生化危机）（规范命名）
//  3. 版本号合并到 variants：listOf("铁拳8","铁拳7","铁拳","Tekken 8","Tekken 7","Tekken")
//  4. 新 SourceGroup 追加到末尾，不插入中间
//  5. CharEntry canonical 用最常用中文名，aliases 含自身+中文别名+英文名+昵称，按长度降序（别名完整/长度降序）
//  6. 出处+角色名是唯一标识，不同出处同名角色各自独立 CharEntry
//  7. 同一 SourceGroup 内禁止重复 CharEntry，发现重复必须合并 aliases
//
// 规模说明：本文件超出「Go 单文件 ≤600 行」警戒线。豁免理由（协议生成接口签名同级）：
// 纯数据表完整性优先——130 组拆散成多个文件会破坏「查重优先」的增补维护性
// （增补者必须能一眼看到全部既有 canonical/变体才能查重），拆散反而制造重复与漂移风险。
package sourcematcher

// builtinGroups 内置检索表；排序与索引构建在 Matcher 构造时完成（见 matcher.go）。
var builtinGroups = []SourceGroup{
	{Canonical: "尼尔 机械纪元", Variants: []string{"尼尔 机械纪元", "尼尔机械纪元", "NieR Automata", "NieR"}, Characters: []CharEntry{
		{Canonical: "2B", Aliases: []string{"2B", "2b", "二号机", "YoRHa No2 Type B"}},
		{Canonical: "A2", Aliases: []string{"A2", "a2", "A型二号"}},
		{Canonical: "帕斯卡", Aliases: []string{"帕斯卡", "Pascal"}},
		{Canonical: "司令官", Aliases: []string{"司令官", "Commander", "怀特", "Yorha指挥官", "指挥官"}},
		{Canonical: "迪瓦拉", Aliases: []string{"迪瓦拉", "迪瓦菈", "Devola"}},
		{Canonical: "波波拉", Aliases: []string{"波波拉", "波波菈", "Popola"}},
		{Canonical: "凯妮", Aliases: []string{"凯妮", "Kaine"}},
		{Canonical: "艾米尔", Aliases: []string{"艾米尔", "Emil"}},
	}},
	{Canonical: "守望先锋", Variants: []string{"守望先锋", "守望先锋 归来", "守望先锋2", "Overwatch", "OW"}, Characters: []CharEntry{
		{Canonical: "天使", Aliases: []string{"天使", "Mercy", "安吉拉", "齐格勒", "Angela"}},
		{Canonical: "猎空", Aliases: []string{"猎空", "裂空", "Tracer", "莉娜"}},
		{Canonical: "DVA", Aliases: []string{"DVA", "D.Va", "Dva", "宋哈娜", "Hana"}},
		{Canonical: "黑百合", Aliases: []string{"黑百合", "Widowmaker", "艾米丽", "Amelie"}},
		{Canonical: "小美", Aliases: []string{"小美", "Mei", "周美灵"}},
		{Canonical: "雾子", Aliases: []string{"雾子", "Kiriko", "狐狸"}},
		{Canonical: "朱诺", Aliases: []string{"朱诺", "Juno"}},
		{Canonical: "艾什", Aliases: []string{"艾什", "Ashe", "莱德"}},
		{Canonical: "芙蕾雅", Aliases: []string{"芙蕾雅", "Freya"}},
		{Canonical: "法老之鹰", Aliases: []string{"法老之鹰", "法鸡", "Pharah", "法拉"}},
		{Canonical: "秩序之光", Aliases: []string{"秩序之光", "Symmetra", "塞特娅"}},
		{Canonical: "查莉娅", Aliases: []string{"查莉娅", "Zarya", "毛妹"}},
		{Canonical: "黑影", Aliases: []string{"黑影", "Sombra"}},
		{Canonical: "安娜", Aliases: []string{"安娜", "Ana"}},
		{Canonical: "布丽吉塔", Aliases: []string{"布丽吉塔", "Brigitte", "锤妹"}},
		{Canonical: "莫伊拉", Aliases: []string{"莫伊拉", "Moira"}},
		{Canonical: "回声", Aliases: []string{"回声", "Echo"}},
		{Canonical: "狂鼠女王", Aliases: []string{"狂鼠女王", "Junker Queen", "渣客女王"}},
		{Canonical: "伊拉莉", Aliases: []string{"伊拉莉", "Illari"}},
		{Canonical: "探奇", Aliases: []string{"探奇", "Venture"}},
		{Canonical: "温斯顿", Aliases: []string{"温斯顿", "Winston"}},
		{Canonical: "安燃", Aliases: []string{"安燃", "安然", "Anran"}},
	}},
	{Canonical: "英雄联盟", Variants: []string{"英雄联盟", "League of Legends", "LOL", "撸啊撸"}, Characters: []CharEntry{
		{Canonical: "阿狸", Aliases: []string{"阿狸", "Ahri", "九尾妖狐", "狐狸"}},
		{Canonical: "金克丝", Aliases: []string{"金克丝", "Jinx", "暴走萝莉"}},
		{Canonical: "拉克丝", Aliases: []string{"拉克丝", "Lux", "光辉女郎"}},
		{Canonical: "伊芙琳", Aliases: []string{"伊芙琳", "Evelynn", "寡妇制造者", "寡妇"}},
		{Canonical: "莫甘娜", Aliases: []string{"莫甘娜", "Morgana"}},
		{Canonical: "戴安娜", Aliases: []string{"戴安娜", "Diana", "皎月女神"}},
		{Canonical: "格温", Aliases: []string{"格温", "Gwen"}},
		{Canonical: "好运姐", Aliases: []string{"好运姐", "女枪", "厄运小姐", "Miss Fortune", "MF", "赏金", "赏金猎人"}},
		{Canonical: "卡特琳娜", Aliases: []string{"卡特琳娜", "卡特", "Katarina", "不祥之刃"}},
		{Canonical: "阿卡丽", Aliases: []string{"阿卡丽", "Akali"}},
		{Canonical: "卡莎", Aliases: []string{"卡莎", "Kaisa", "卡莎"}},
		{Canonical: "琴女", Aliases: []string{"琴女", "Sona", "娑娜"}},
		{Canonical: "薇恩", Aliases: []string{"薇恩", "Vayne", "暗夜猎手"}},
		{Canonical: "艾希", Aliases: []string{"艾希", "Ashe", "寒冰射手"}},
		{Canonical: "凯特琳", Aliases: []string{"凯特琳", "Caitlyn", "女警"}},
		{Canonical: "蔚", Aliases: []string{"蔚", "Vi", "皮城执法官"}},
		{Canonical: "辛德拉", Aliases: []string{"辛德拉", "Syndra"}},
		{Canonical: "蕾欧娜", Aliases: []string{"蕾欧娜", "Leona", "日女"}},
		{Canonical: "婕拉", Aliases: []string{"婕拉", "Zyra"}},
		{Canonical: "希瓦娜", Aliases: []string{"希瓦娜", "Shyvana", "龙女"}},
		{Canonical: "锐雯", Aliases: []string{"锐雯", "Riven", "放逐之刃"}},
		{Canonical: "菲奥娜", Aliases: []string{"菲奥娜", "Fiora", "剑姬"}},
		{Canonical: "艾瑞莉娅", Aliases: []string{"艾瑞莉娅", "Irelia", "刀妹"}},
		{Canonical: "卡西奥佩娅", Aliases: []string{"卡西奥佩娅", "Cassiopeia", "蛇女"}},
		{Canonical: "丽桑卓", Aliases: []string{"丽桑卓", "Lissandra", "冰女"}},
		{Canonical: "卡蜜尔", Aliases: []string{"卡蜜尔", "Camille", "青钢影"}},
		{Canonical: "霞", Aliases: []string{"霞", "Xayah"}},
		{Canonical: "佐伊", Aliases: []string{"佐伊", "Zoe"}},
		{Canonical: "妮蔻", Aliases: []string{"妮蔻", "Neeko"}},
		{Canonical: "塞娜", Aliases: []string{"塞娜", "Senna"}},
		{Canonical: "萨勒芬妮", Aliases: []string{"萨勒芬妮", "Seraphine"}},
		{Canonical: "泽丽", Aliases: []string{"泽丽", "Zeri"}},
		{Canonical: "薇古丝", Aliases: []string{"薇古丝", "Vex"}},
		{Canonical: "奎因", Aliases: []string{"奎因", "Quinn", "德玛西亚之翼"}},
		{Canonical: "希维尔", Aliases: []string{"希维尔", "Sivir", "轮子妈"}},
		{Canonical: "崔丝塔娜", Aliases: []string{"崔丝塔娜", "Tristana", "小炮"}},
		{Canonical: "波比", Aliases: []string{"波比", "Poppy", "圣锤之毅"}},
		{Canonical: "莉莉娅", Aliases: []string{"莉莉娅", "Lillia"}},
		{Canonical: "蕾珂丝", Aliases: []string{"蕾珂丝", "Rek'Sai"}},
		{Canonical: "米利欧", Aliases: []string{"米利欧", "Millio"}},
		{Canonical: "娜美", Aliases: []string{"娜美", "Nami"}},
		{Canonical: "索拉卡", Aliases: []string{"索拉卡", "Soraka", "星妈"}},
		{Canonical: "迦娜", Aliases: []string{"迦娜", "Janna", "风女"}},
		{Canonical: "璐璐", Aliases: []string{"璐璐", "Lulu"}},
		{Canonical: "塔莉垭", Aliases: []string{"塔莉垭", "Taliyah", "岩雀"}},
		{Canonical: "奇亚娜", Aliases: []string{"奇亚娜", "Qiyana"}},
		{Canonical: "伊泽瑞尔", Aliases: []string{"伊泽瑞尔", "Ezreal", "EZ"}},
	}},
	{Canonical: "崩坏 星穹铁道", Variants: []string{"崩坏 星穹铁道", "崩坏星穹铁道", "Honkai Star Rail", "星铁", "星穹铁道", "HSR"}, Characters: []CharEntry{
		{Canonical: "卡芙卡", Aliases: []string{"卡芙卡", "Kafka"}},
		{Canonical: "银狼", Aliases: []string{"银狼", "Silver Wolf"}},
		{Canonical: "布洛妮娅", Aliases: []string{"布洛妮娅", "Bronya"}},
		{Canonical: "希儿", Aliases: []string{"希儿", "Seele"}},
		{Canonical: "姬子", Aliases: []string{"姬子", "Himeko"}},
		{Canonical: "黑塔", Aliases: []string{"黑塔", "Herta"}},
		{Canonical: "青雀", Aliases: []string{"青雀", "Qingque"}},
		{Canonical: "符玄", Aliases: []string{"符玄", "Fu Xuan"}},
		{Canonical: "托帕", Aliases: []string{"托帕", "Topaz"}},
		{Canonical: "桂乃芬", Aliases: []string{"桂乃芬", "Guinaifen"}},
		{Canonical: "藿藿", Aliases: []string{"藿藿", "HuoHuo"}},
		{Canonical: "阮梅", Aliases: []string{"阮梅", "Ruan Mei"}},
		{Canonical: "花火", Aliases: []string{"花火", "Sparkle"}},
		{Canonical: "黄泉", Aliases: []string{"黄泉", "Acheron"}},
		{Canonical: "知更鸟", Aliases: []string{"知更鸟", "Robin"}},
		{Canonical: "流萤", Aliases: []string{"流萤", "Firefly"}},
		{Canonical: "翡翠", Aliases: []string{"翡翠", "Jade"}},
		{Canonical: "云璃", Aliases: []string{"云璃", "Yunli"}},
		{Canonical: "椒丘", Aliases: []string{"椒丘", "Jiaoqiu"}},
		{Canonical: "飞霄", Aliases: []string{"飞霄", "Feixiao"}},
		{Canonical: "灵砂", Aliases: []string{"灵砂", "Lingsha"}},
		{Canonical: "停云", Aliases: []string{"停云", "Tingyun"}},
		{Canonical: "素裳", Aliases: []string{"素裳", "Sushang"}},
		{Canonical: "虎克", Aliases: []string{"虎克", "Hook"}},
		{Canonical: "克拉拉", Aliases: []string{"克拉拉", "Clara"}},
		{Canonical: "娜塔莎", Aliases: []string{"娜塔莎", "Natasha"}},
		{Canonical: "佩拉", Aliases: []string{"佩拉", "Pela"}},
		{Canonical: "玲可", Aliases: []string{"玲可", "Lynx"}},
		{Canonical: "白露", Aliases: []string{"白露", "Bailu"}},
		{Canonical: "镜流", Aliases: []string{"镜流", "Jingliu"}},
		{Canonical: "三月七", Aliases: []string{"三月七", "March 7th", "三七"}},
		{Canonical: "开拓者", Aliases: []string{"开拓者", "Trailblazer", "星", "穹"}},
		{Canonical: "昔涟", Aliases: []string{"昔涟"}},
		{Canonical: "海瑟音", Aliases: []string{"海瑟音"}},
		{Canonical: "遐蝶", Aliases: []string{"遐蝶"}},
		{Canonical: "玄符", Aliases: []string{"玄符"}},
	}},
	{Canonical: "崩坏3", Variants: []string{"崩坏3", "崩坏3rd", "Honkai Impact 3rd", "崩坏三"}, Characters: []CharEntry{
		{Canonical: "琪亚娜", Aliases: []string{"琪亚娜", "Kiana", "空之律者"}},
		{Canonical: "芽衣", Aliases: []string{"芽衣", "Mei", "雷电芽衣"}},
		{Canonical: "布洛妮娅", Aliases: []string{"布洛妮娅", "Bronya", "理之律者"}},
		{Canonical: "符华", Aliases: []string{"符华", "Fu Hua", "凤凰"}},
		{Canonical: "丽塔", Aliases: []string{"丽塔", "Rita"}},
		{Canonical: "幽兰黛尔", Aliases: []string{"幽兰黛尔", "Durandal"}},
		{Canonical: "希儿", Aliases: []string{"希儿", "Seele"}},
		{Canonical: "八重樱", Aliases: []string{"八重樱", "Sakura", "Yae Sakura"}},
		{Canonical: "德丽莎", Aliases: []string{"德丽莎", "Theresa"}},
		{Canonical: "爱莉希雅", Aliases: []string{"爱莉希雅", "Elysia", "粉色妖精"}},
		{Canonical: "梅比乌斯", Aliases: []string{"梅比乌斯", "Mobius", "蛇"}},
		{Canonical: "伊甸", Aliases: []string{"伊甸", "Eden"}},
		{Canonical: "阿波尼亚", Aliases: []string{"阿波尼亚", "Aponia"}},
		{Canonical: "千劫", Aliases: []string{"千劫", "Kalpas"}},
		{Canonical: "华", Aliases: []string{"华", "Hua"}},
		{Canonical: "渡鸦", Aliases: []string{"渡鸦", "Raven"}},
		{Canonical: "萝莎莉娅", Aliases: []string{"萝莎莉娅", "Rozaliya"}},
		{Canonical: "莉莉娅", Aliases: []string{"莉莉娅", "Liliya"}},
		{Canonical: "瑟利姆", Aliases: []string{"瑟利姆", "Selim"}},
	}},
	{Canonical: "原神", Variants: []string{"原神", "Genshin Impact", "Genshin", "原"}, Characters: []CharEntry{
		{Canonical: "甘雨", Aliases: []string{"甘雨", "Ganyu", "椰羊"}},
		{Canonical: "胡桃", Aliases: []string{"胡桃", "Hu Tao", "堂主"}},
		{Canonical: "雷电将军", Aliases: []string{"雷电将军", "雷神", "Raiden Shogun", "影", "Ei"}},
		{Canonical: "神里绫华", Aliases: []string{"神里绫华", "绫华", "Ayaka", "白鹭公主"}},
		{Canonical: "宵宫", Aliases: []string{"宵宫", "Yoimiya"}},
		{Canonical: "八重神子", Aliases: []string{"八重神子", "神子", "Yae Miko", "狐狸"}},
		{Canonical: "珊瑚宫心海", Aliases: []string{"珊瑚宫心海", "心海", "Kokomi", "军师"}},
		{Canonical: "申鹤", Aliases: []string{"申鹤", "Shenhe"}},
		{Canonical: "夜兰", Aliases: []string{"夜兰", "Yelan"}},
		{Canonical: "妮露", Aliases: []string{"妮露", "Nilou"}},
		{Canonical: "纳西妲", Aliases: []string{"纳西妲", "Nahida", "草神", "小吉祥草王"}},
		{Canonical: "优菈", Aliases: []string{"优菈", "Eula", "浪花骑士"}},
		{Canonical: "刻晴", Aliases: []string{"刻晴", "Keqing", "玉衡星"}},
		{Canonical: "凝光", Aliases: []string{"凝光", "Ningguang", "天权星"}},
		{Canonical: "北斗", Aliases: []string{"北斗", "Beidou"}},
		{Canonical: "丽莎", Aliases: []string{"丽莎", "Lisa"}},
		{Canonical: "安柏", Aliases: []string{"安柏", "Amber"}},
		{Canonical: "芭芭拉", Aliases: []string{"芭芭拉", "Barbara", "牧师"}},
		{Canonical: "琴", Aliases: []string{"琴", "Jean", "代理团长"}},
		{Canonical: "莫娜", Aliases: []string{"莫娜", "Mona", "占星术士"}},
		{Canonical: "菲谢尔", Aliases: []string{"菲谢尔", "Fischl", "皇女"}},
		{Canonical: "诺艾尔", Aliases: []string{"诺艾尔", "Noelle", "女仆"}},
		{Canonical: "香菱", Aliases: []string{"香菱", "Xiangling"}},
		{Canonical: "行秋", Aliases: []string{"行秋", "Xingqiu"}},
		{Canonical: "荧", Aliases: []string{"荧", "Lumine", "妹妹"}},
		{Canonical: "罗莎莉亚", Aliases: []string{"罗莎莉亚", "Rosaria", "修女"}},
		{Canonical: "烟绯", Aliases: []string{"烟绯", "Yanfei"}},
		{Canonical: "辛焱", Aliases: []string{"辛焱", "Xinyan"}},
		{Canonical: "云堇", Aliases: []string{"云堇", "Yun Jin"}},
		{Canonical: "久岐忍", Aliases: []string{"久岐忍", "Shinobu"}},
		{Canonical: "鹿野院平藏", Aliases: []string{"鹿野院平藏", "平藏", "Heizou"}},
		{Canonical: "柯莱", Aliases: []string{"柯莱", "Collei"}},
		{Canonical: "多莉", Aliases: []string{"多莉", "Dori"}},
		{Canonical: "坎蒂丝", Aliases: []string{"坎蒂丝", "Candace"}},
		{Canonical: "莱依拉", Aliases: []string{"莱依拉", "Layla"}},
		{Canonical: "珐露珊", Aliases: []string{"珐露珊", "Faruzan"}},
		{Canonical: "迪希雅", Aliases: []string{"迪希雅", "Dehya"}},
		{Canonical: "米卡", Aliases: []string{"米卡", "Mika"}},
		{Canonical: "白术", Aliases: []string{"白术", "Baizhu"}},
		{Canonical: "绮良良", Aliases: []string{"绮良良", "Kirara"}},
		{Canonical: "芙宁娜", Aliases: []string{"芙宁娜", "Furina", "水神"}},
		{Canonical: "夏洛蒂", Aliases: []string{"夏洛蒂", "Charlotte"}},
		{Canonical: "娜维娅", Aliases: []string{"娜维娅", "Navia"}},
		{Canonical: "夏沃蕾", Aliases: []string{"夏沃蕾", "Chevreuse"}},
		{Canonical: "闲云", Aliases: []string{"闲云", "Xianyun", "留云借风真君"}},
		{Canonical: "嘉明", Aliases: []string{"嘉明", "Gaming"}},
		{Canonical: "千织", Aliases: []string{"千织", "Chiori"}},
		{Canonical: "阿蕾奇诺", Aliases: []string{"阿蕾奇诺", "Arlecchino", "仆人", "父亲"}},
		{Canonical: "希格雯", Aliases: []string{"希格雯", "Sigewinne", "护士长"}},
		{Canonical: "克洛琳德", Aliases: []string{"克洛琳德", "Clorinde"}},
		{Canonical: "艾梅莉埃", Aliases: []string{"艾梅莉埃", "Emilie"}},
		{Canonical: "玛拉妮", Aliases: []string{"玛拉妮", "Mualani"}},
		{Canonical: "希诺宁", Aliases: []string{"希诺宁", "Xilonen"}},
		{Canonical: "基尼奇", Aliases: []string{"基尼奇", "Kinich"}},
		{Canonical: "卡齐娜", Aliases: []string{"卡齐娜", "Kachina"}},
		{Canonical: "欧洛伦", Aliases: []string{"欧洛伦", "Ororon"}},
		{Canonical: "茜特菈莉", Aliases: []string{"茜特菈莉", "Citlali"}},
		{Canonical: "蓝砚", Aliases: []string{"蓝砚", "Lanyan"}},
		{Canonical: "瓦莱丽", Aliases: []string{"瓦莱丽", "Varesa"}},
	}},
	{Canonical: "赛博朋克2077", Variants: []string{"赛博朋克2077", "赛博朋克 2077", "2077", "Cyberpunk 2077", "Cyberpunk", "赛博朋克"}, Characters: []CharEntry{
		{Canonical: "帕南", Aliases: []string{"帕南", "Panam"}},
		{Canonical: "朱迪", Aliases: []string{"朱迪", "Judy"}},
		{Canonical: "罗格", Aliases: []string{"罗格", "Rogue"}},
		{Canonical: "梅瑞德斯", Aliases: []string{"梅瑞德斯", "Meredith"}},
		{Canonical: "艾芙琳", Aliases: []string{"艾芙琳", "Evelyn"}},
		{Canonical: "T Bug", Aliases: []string{"T Bug", "T-Bug"}},
		{Canonical: "华子", Aliases: []string{"华子", "Hanako"}},
		{Canonical: "克里", Aliases: []string{"克里", "Kerry"}},
		{Canonical: "米丝蒂", Aliases: []string{"米丝蒂", "Misty"}},
	}},
	{Canonical: "最终幻想", Variants: []string{"最终幻想7 重制版", "最终幻想7", "最终幻想 7", "最终幻想16", "最终幻想15", "最终幻想14", "最终幻想", "Final Fantasy", "FF7", "FF14", "FF16", "FF15"}, Characters: []CharEntry{
		{Canonical: "蒂法", Aliases: []string{"蒂法", "Tifa", "蒂法洛克哈特"}},
		{Canonical: "爱丽丝", Aliases: []string{"爱丽丝", "Aerith", "艾瑞丝", "爱丽丝盖恩斯巴勒"}},
		{Canonical: "尤菲", Aliases: []string{"尤菲", "Yuffie", "如月尤菲"}},
		{Canonical: "吉尔", Aliases: []string{"吉尔", "Jill"}},
		{Canonical: "蕾菲娅", Aliases: []string{"蕾菲娅", "Refia"}},
		{Canonical: "莉诺亚", Aliases: []string{"莉诺亚", "Rinoa"}},
		{Canonical: "塞拉", Aliases: []string{"塞拉", "Serah"}},
		{Canonical: "雷霆", Aliases: []string{"雷霆", "Lightning", "克莱尔"}},
		{Canonical: "露娜弗蕾亚", Aliases: []string{"露娜弗蕾亚", "Lunafreya", "露娜"}},
		{Canonical: "尤娜", Aliases: []string{"尤娜", "Yuna"}},
		{Canonical: "莉库", Aliases: []string{"莉库", "Rikku"}},
		{Canonical: "帕茵", Aliases: []string{"帕茵", "Paine"}},
		{Canonical: "阿什", Aliases: []string{"阿什", "Ashe"}},
		{Canonical: "梵妮尔", Aliases: []string{"梵妮尔", "Vanille"}},
		{Canonical: "牙", Aliases: []string{"牙", "Fang"}},
		{Canonical: "塞拉", Aliases: []string{"塞拉", "Celes"}},
		{Canonical: "蒂娜", Aliases: []string{"蒂娜", "Terra"}},
		{Canonical: "法丽斯", Aliases: []string{"法丽斯", "Faris"}},
		{Canonical: "蕾娜", Aliases: []string{"蕾娜", "Lenna"}},
		{Canonical: "嘉源", Aliases: []string{"嘉源", "Rydia"}},
		{Canonical: "罗莎", Aliases: []string{"罗莎", "Rosa"}},
		{Canonical: "艾蔻", Aliases: []string{"艾蔻", "Echo"}},
		{Canonical: "克劳德", Aliases: []string{"克劳德", "Cloud"}},
		{Canonical: "萨菲罗斯", Aliases: []string{"萨菲罗斯", "Sephiroth"}},
		{Canonical: "甘蒂亚娜", Aliases: []string{"甘蒂亚娜", "吉恩提亚娜", "Gentiana"}},
	}},
	{Canonical: "艾尔登法环", Variants: []string{"艾尔登法环", "Elden Ring", "老头环"}, Characters: []CharEntry{
		{Canonical: "玛丽卡", Aliases: []string{"玛丽卡", "Marika", "永恒女王"}},
		{Canonical: "拉妮", Aliases: []string{"拉妮", "Ranni", "雪魔女"}},
		{Canonical: "玛莲妮亚", Aliases: []string{"玛莲妮亚", "玛莲妮娅", "Malenia", "米凯拉的锋刃", "女武神"}},
		{Canonical: "梅琳娜", Aliases: []string{"梅琳娜", "Melina"}},
		{Canonical: "菈雅", Aliases: []string{"菈雅", "Rya"}},
		{Canonical: "蕾娜拉", Aliases: []string{"蕾娜拉", "Rennala"}},
		{Canonical: "瑟濂", Aliases: []string{"瑟濂", "Sellen", "魔女"}},
		{Canonical: "拉特娜", Aliases: []string{"拉特娜", "Latenna"}},
		{Canonical: "涅斐丽", Aliases: []string{"涅斐丽", "Nepheli"}},
		{Canonical: "菲雅", Aliases: []string{"菲雅", "Fia", "死眠少女"}},
		{Canonical: "海妲", Aliases: []string{"海妲", "Hyetta"}},
		{Canonical: "伊蕾娜", Aliases: []string{"伊蕾娜", "Irina"}},
		{Canonical: "托莉娜", Aliases: []string{"托莉娜", "St Trina"}},
		{Canonical: "蕾达", Aliases: []string{"蕾达", "Leda"}},
		{Canonical: "安帕赫", Aliases: []string{"安帕赫", "Ansbach"}},
		{Canonical: "穆格", Aliases: []string{"穆格", "Mohg"}},
	}},
	{Canonical: "巫师", Variants: []string{"巫师3", "巫师 3", "The Witcher 3", "The Witcher", "巫师"}, Characters: []CharEntry{
		{Canonical: "希里", Aliases: []string{"希里", "Ciri", "辛特拉的幼狮"}},
		{Canonical: "叶奈法", Aliases: []string{"叶奈法", "Yennefer", "叶姐"}},
		{Canonical: "特莉丝", Aliases: []string{"特莉丝", "Triss"}},
		{Canonical: "凯拉", Aliases: []string{"凯拉", "Keira"}},
		{Canonical: "夏妮", Aliases: []string{"夏妮", "Shani"}},
		{Canonical: "普丽希拉", Aliases: []string{"普丽希拉", "Priscilla"}},
		{Canonical: "安娜亨利叶塔", Aliases: []string{"安娜亨利叶塔", "Anna Henrietta"}},
		{Canonical: "席安娜", Aliases: []string{"席安娜", "Syanna"}},
		{Canonical: "芙琳吉拉", Aliases: []string{"芙琳吉拉", "Fringilla"}},
		{Canonical: "芮娜", Aliases: []string{"芮娜", "Renfri"}},
	}},
	{Canonical: "生化危机", Variants: []string{"生化危机4 重制版", "生化危机4", "生化危机2 重制版", "生化危机2", "生化危机3", "生化危机8", "生化危机", "Resident Evil", "RE2", "RE4"}, Characters: []CharEntry{
		{Canonical: "克莱尔", Aliases: []string{"克莱尔", "Claire", "克莱尔雷德菲尔德"}},
		{Canonical: "吉尔", Aliases: []string{"吉尔", "Jill", "吉尔瓦伦丁"}},
		{Canonical: "艾达", Aliases: []string{"艾达", "Ada", "Ada Wong", "王艾达"}},
		{Canonical: "瑞贝卡", Aliases: []string{"瑞贝卡", "Rebecca"}},
		{Canonical: "米娅", Aliases: []string{"米娅", "Mia"}},
		{Canonical: "萝丝", Aliases: []string{"萝丝", "Rose", "Rosemary"}},
		{Canonical: "蒂米特雷斯库", Aliases: []string{"蒂米特雷斯库", "Lady Dimitrescu", "八尺大人", "吸血鬼夫人"}},
		{Canonical: "谢娃", Aliases: []string{"谢娃", "Sheva"}},
		{Canonical: "海伦娜", Aliases: []string{"海伦娜", "Helena"}},
		{Canonical: "格蕾丝", Aliases: []string{"格蕾丝", "Grace"}},
		{Canonical: "雪莉", Aliases: []string{"雪莉", "Sherry Birkin", "雪莉柏金", "Sherry"}},
		{Canonical: "艾什莉", Aliases: []string{"艾什莉", "Ashley"}},
	}},
	{Canonical: "古墓丽影", Variants: []string{"古墓丽影", "Tomb Raider"}, Characters: []CharEntry{
		{Canonical: "劳拉", Aliases: []string{"劳拉", "Lara", "Lara Croft", "劳拉克劳馥"}},
	}},
	{Canonical: "博德之门3", Variants: []string{"博德之门3", "博德之门 3", "Baldurs Gate 3", "Baldurs Gate", "BG3"}, Characters: []CharEntry{
		{Canonical: "影心", Aliases: []string{"影心", "Shadowheart"}},
		{Canonical: "莱埃泽尔", Aliases: []string{"莱埃泽尔", "Laezel"}},
		{Canonical: "卡尔赫", Aliases: []string{"卡尔赫", "Karlach"}},
		{Canonical: "明萨拉", Aliases: []string{"明萨拉", "Minthara"}},
	}},
	{Canonical: "光与影 33号远征队", Variants: []string{"光与影 33号远征队", "光与影33号远征队", "Clair Obscur Expedition 33"}, Characters: []CharEntry{
		{Canonical: "吕涅", Aliases: []string{"吕涅", "Lune"}},
		{Canonical: "玛埃尔", Aliases: []string{"玛埃尔", "Maelle"}},
		{Canonical: "希耶尔", Aliases: []string{"希耶尔", "Sciel"}},
	}},
	{Canonical: "剑星", Variants: []string{"剑星", "Stellar Blade"}, Characters: []CharEntry{
		{Canonical: "伊芙", Aliases: []string{"伊芙", "Eve"}},
		{Canonical: "塔奇", Aliases: []string{"塔奇", "Tachy"}},
		{Canonical: "渡鸦", Aliases: []string{"渡鸦", "Raven"}},
		{Canonical: "讯梓", Aliases: []string{"讯梓", "Xunzi"}},
	}},
	{Canonical: "铁拳", Variants: []string{"铁拳8", "铁拳7", "铁拳6", "铁拳5", "铁拳", "Tekken 8", "Tekken 7", "Tekken 6", "Tekken"}, Characters: []CharEntry{
		{Canonical: "莉莉", Aliases: []string{"莉莉", "Lili", "艾米莉德罗什福尔"}},
		{Canonical: "风间飞鸟", Aliases: []string{"风间飞鸟", "飞鸟", "Xiaoyu", "凌晓雨"}},
		{Canonical: "妮娜", Aliases: []string{"妮娜", "Nina", "妮娜威廉姆斯"}},
		{Canonical: "安娜", Aliases: []string{"安娜", "Anna", "安娜威廉姆斯"}},
		{Canonical: "克里斯蒂", Aliases: []string{"克里斯蒂", "Christie"}},
		{Canonical: "阿丽莎", Aliases: []string{"阿丽莎", "Alisa"}},
		{Canonical: "幸运克洛伊", Aliases: []string{"幸运克洛伊", "Lucky Chloe"}},
		{Canonical: "和真", Aliases: []string{"和真", "Kazumi"}},
		{Canonical: "乔西", Aliases: []string{"乔西", "Josie"}},
		{Canonical: "莉迪亚", Aliases: []string{"莉迪亚", "Lidia"}},
		{Canonical: "卡塔琳娜", Aliases: []string{"卡塔琳娜", "Katarina"}},
		{Canonical: "艾丽莎", Aliases: []string{"艾丽莎", "Eliza"}},
		{Canonical: "莫妮卡", Aliases: []string{"莫妮卡", "Monica"}},
		{Canonical: "州光", Aliases: []string{"州光", "Kunimitsu"}},
		{Canonical: "阿苏塞娜", Aliases: []string{"阿苏塞娜", "Azucena", "咖啡女王"}},
	}},
	{Canonical: "恶魔战士", Variants: []string{"恶魔战士", "Darkstalkers", "Vampire Savior"}, Characters: []CharEntry{
		{Canonical: "莫莉卡", Aliases: []string{"莫莉卡", "Morrigan", "梦魔"}},
		{Canonical: "莉莉丝", Aliases: []string{"莉莉丝", "Lilith"}},
		{Canonical: "菲莉西亚", Aliases: []string{"菲莉西亚", "Felicia", "猫女"}},
		{Canonical: "恋", Aliases: []string{"恋", "Hsien Ko", "中国僵尸"}},
		{Canonical: "Q Bee", Aliases: []string{"Q Bee", "Q-Bee"}},
		{Canonical: "小红帽", Aliases: []string{"小红帽", "B B Hood", "Bulleta"}},
	}},
	{Canonical: "绝区零", Variants: []string{"绝区零", "Zenless Zone Zero", "ZZZ"}, Characters: []CharEntry{
		{Canonical: "安比", Aliases: []string{"安比", "Anby"}},
		{Canonical: "妮可", Aliases: []string{"妮可", "Nicole"}},
		{Canonical: "猫又", Aliases: []string{"猫又", "Nekomata", "猫宫又奈"}},
		{Canonical: "丽娜", Aliases: []string{"丽娜", "Rina"}},
		{Canonical: "艾莲", Aliases: []string{"艾莲", "Ellen", "艾莲乔"}},
		{Canonical: "朱鸢", Aliases: []string{"朱鸢", "Zhu Yuan"}},
		{Canonical: "青衣", Aliases: []string{"青衣", "Qingyi"}},
		{Canonical: "简", Aliases: []string{"简", "Jane", "简杜"}},
		{Canonical: "凯撒", Aliases: []string{"凯撒", "Caesar"}},
		{Canonical: "柏妮思", Aliases: []string{"柏妮思", "Burnice"}},
		{Canonical: "柳", Aliases: []string{"柳", "Yanagi"}},
		{Canonical: "星见雅", Aliases: []string{"星见雅", "雅", "Hoshimi Miyabi", "Miyabi"}},
		{Canonical: "伊芙琳", Aliases: []string{"伊芙琳", "Evelyn"}},
		{Canonical: "莱特", Aliases: []string{"莱特", "Lighter"}},
		{Canonical: "悠真", Aliases: []string{"悠真", "Harumasa"}},
		{Canonical: "耀嘉音", Aliases: []string{"耀嘉音"}},
		{Canonical: "仪玄", Aliases: []string{"仪玄"}},
		{Canonical: "叶瞬光", Aliases: []string{"叶瞬光"}},
		{Canonical: "千夏", Aliases: []string{"千夏", "Chinatsu"}},
	}},
	{Canonical: "明日方舟", Variants: []string{"明日方舟", "Arknights", "方舟"}, Characters: []CharEntry{
		{Canonical: "阿米娅", Aliases: []string{"阿米娅", "Amiya"}},
		{Canonical: "凯尔希", Aliases: []string{"凯尔希", "Kaltsit"}},
		{Canonical: "陈", Aliases: []string{"陈", "Chen", "陈晖洁"}},
		{Canonical: "史尔特尔", Aliases: []string{"史尔特尔", "Surtr"}},
		{Canonical: "W", Aliases: []string{"W"}},
		{Canonical: "斯卡蒂", Aliases: []string{"斯卡蒂", "Skadi", "蒂蒂"}},
		{Canonical: "幽灵鲨", Aliases: []string{"幽灵鲨", "Specter"}},
		{Canonical: "塞雷娅", Aliases: []string{"塞雷娅", "Saria"}},
		{Canonical: "推进之王", Aliases: []string{"推进之王", "Siege"}},
		{Canonical: "德克萨斯", Aliases: []string{"德克萨斯", "Texas", "得克萨斯"}},
		{Canonical: "拉普兰德", Aliases: []string{"拉普兰德", "Lappland"}},
		{Canonical: "能天使", Aliases: []string{"能天使", "Exusiai"}},
		{Canonical: "莫斯提马", Aliases: []string{"莫斯提马", "Mostima"}},
		{Canonical: "安洁莉娜", Aliases: []string{"安洁莉娜", "Angelina"}},
		{Canonical: "伊芙利特", Aliases: []string{"伊芙利特", "Ifrit"}},
		{Canonical: "麦哲伦", Aliases: []string{"麦哲伦", "Magallan"}},
		{Canonical: "临光", Aliases: []string{"临光", "Nearl"}},
		{Canonical: "泥岩", Aliases: []string{"泥岩", "Mudrock"}},
		{Canonical: "卡涅利安", Aliases: []string{"卡涅利安", "Carnelian"}},
		{Canonical: "夕", Aliases: []string{"夕", "Dusk"}},
		{Canonical: "令", Aliases: []string{"令", "Ling"}},
		{Canonical: "山", Aliases: []string{"山", "Shanhai"}},
		{Canonical: "琴柳", Aliases: []string{"琴柳", "Saileach"}},
		{Canonical: "耀骑士临光", Aliases: []string{"耀骑士临光", "Nearl the Radiant Knight"}},
		{Canonical: "瑕光", Aliases: []string{"瑕光", "Blemishine"}},
		{Canonical: "迷迭香", Aliases: []string{"迷迭香", "Rosmontis"}},
		{Canonical: "浊心斯卡蒂", Aliases: []string{"浊心斯卡蒂"}},
		{Canonical: "红", Aliases: []string{"红", "Projekt Red"}},
		{Canonical: "霜叶", Aliases: []string{"霜叶", "Frostleaf"}},
		{Canonical: "芙兰卡", Aliases: []string{"芙兰卡", "Franka"}},
		{Canonical: "崖心", Aliases: []string{"崖心", "Cliffheart"}},
		{Canonical: "初雪", Aliases: []string{"初雪", "Pramanix"}},
		{Canonical: "银灰", Aliases: []string{"银灰", "SilverAsh"}},
		{Canonical: "灵知", Aliases: []string{"灵知", "Gnosis"}},
		{Canonical: "司霆惊蛰", Aliases: []string{"司霆惊蛰", "惊蛰"}},
		{Canonical: "特蕾西娅", Aliases: []string{"特蕾西娅", "Theresa"}},
		{Canonical: "闪灵", Aliases: []string{"闪灵", "Shining"}},
	}},
	{Canonical: "碧蓝航线", Variants: []string{"碧蓝航线", "Azur Lane", "AL"}, Characters: []CharEntry{
		{Canonical: "企业", Aliases: []string{"企业", "Enterprise", "灰幽灵"}},
		{Canonical: "贝尔法斯特", Aliases: []string{"贝尔法斯特", "Belfast", "贝法"}},
		{Canonical: "爱宕", Aliases: []string{"爱宕", "Atago", "犬"}},
		{Canonical: "高雄", Aliases: []string{"高雄", "Takao", "狼"}},
		{Canonical: "胡德", Aliases: []string{"胡德", "Hood"}},
		{Canonical: "威尔士亲王", Aliases: []string{"威尔士亲王", "Prince of Wales"}},
		{Canonical: "光辉", Aliases: []string{"光辉", "Illustrious"}},
		{Canonical: "赤城", Aliases: []string{"赤城", "Akagi"}},
		{Canonical: "加贺", Aliases: []string{"加贺", "Kaga"}},
		{Canonical: "克利夫兰", Aliases: []string{"克利夫兰", "Cleveland"}},
		{Canonical: "海伦娜", Aliases: []string{"海伦娜", "Helena"}},
		{Canonical: "华盛顿", Aliases: []string{"华盛顿", "Washington"}},
		{Canonical: "俾斯麦", Aliases: []string{"俾斯麦", "Bismarck"}},
		{Canonical: "提尔比茨", Aliases: []string{"提尔比茨", "Tirpitz"}},
		{Canonical: "齐柏林", Aliases: []string{"齐柏林", "Graf Zeppelin"}},
		{Canonical: "罗恩", Aliases: []string{"罗恩", "Roon"}},
		{Canonical: "腓特烈大帝", Aliases: []string{"腓特烈大帝", "Friedrich der Grosse"}},
		{Canonical: "欧根亲王", Aliases: []string{"欧根亲王", "Prinz Eugen"}},
		{Canonical: "独角兽", Aliases: []string{"独角兽", "Unicorn"}},
		{Canonical: "圣地亚哥", Aliases: []string{"圣地亚哥", "San Diego", "金坷垃"}},
		{Canonical: "天城", Aliases: []string{"天城", "Amagi"}},
		{Canonical: "大凤", Aliases: []string{"大凤", "Taihou"}},
		{Canonical: "皇家方舟", Aliases: []string{"皇家方舟", "Ark Royal"}},
		{Canonical: "约克城", Aliases: []string{"约克城", "Yorktown"}},
		{Canonical: "大黄蜂", Aliases: []string{"大黄蜂", "Hornet"}},
		{Canonical: "女灶神", Aliases: []string{"女灶神", "Vestal"}},
		{Canonical: "埃塞克斯", Aliases: []string{"埃塞克斯", "Essex"}},
		{Canonical: "巴尔的摩", Aliases: []string{"巴尔的摩", "Baltimore"}},
		{Canonical: "巴伐利亚", Aliases: []string{"巴伐利亚", "Bayern"}},
		{Canonical: "泽西", Aliases: []string{"泽西", "Jersey"}},
		{Canonical: "瑞吉娜", Aliases: []string{"瑞吉娜", "Regina"}},
		{Canonical: "安克雷奇", Aliases: []string{"安克雷奇", "Anchorage"}},
	}},
	{Canonical: "碧蓝档案", Variants: []string{"碧蓝档案", "蔚蓝档案", "Blue Archive", "BA"}, Characters: []CharEntry{
		{Canonical: "阿露", Aliases: []string{"阿露", "Aru"}},
		{Canonical: "白子", Aliases: []string{"白子", "Shiroko", "砂狼白子"}},
		{Canonical: "日奈", Aliases: []string{"日奈", "Hina"}},
		{Canonical: "亚子", Aliases: []string{"亚子", "Ako"}},
		{Canonical: "明日奈", Aliases: []string{"明日奈", "Asuna"}},
		{Canonical: "花凛", Aliases: []string{"花凛", "Karin"}},
		{Canonical: "妮露", Aliases: []string{"妮露", "Neru"}},
		{Canonical: "时", Aliases: []string{"时", "Toki"}},
		{Canonical: "妃雪", Aliases: []string{"妃雪", "Kisaki"}},
		{Canonical: "未花", Aliases: []string{"未花", "Mika"}},
		{Canonical: "渚", Aliases: []string{"渚", "Nagisa"}},
		{Canonical: "真白", Aliases: []string{"真白", "Miyako"}},
		{Canonical: "咲", Aliases: []string{"咲", "Saki"}},
		{Canonical: "伊织", Aliases: []string{"伊织", "Iori"}},
		{Canonical: "千夏", Aliases: []string{"千夏", "Chinatsu"}},
		{Canonical: "绫音", Aliases: []string{"绫音", "Ayane"}},
		{Canonical: "莲见", Aliases: []string{"莲见", "Hasumi"}},
		{Canonical: "爱丽丝", Aliases: []string{"爱丽丝", "Aris", "Alice"}},
		{Canonical: "椿", Aliases: []string{"椿", "Tsubaki"}},
		{Canonical: "星野", Aliases: []string{"星野", "Hoshino"}},
		{Canonical: "芹香", Aliases: []string{"芹香", "Serika"}},
		{Canonical: "切里诺", Aliases: []string{"切里诺", "Cherino"}},
		{Canonical: "泉", Aliases: []string{"泉", "Izumi"}},
		{Canonical: "纯子", Aliases: []string{"纯子", "Junko"}},
		{Canonical: "晴", Aliases: []string{"晴", "Hare"}},
		{Canonical: "小雪", Aliases: []string{"小雪", "Koyuki"}},
		{Canonical: "若叶", Aliases: []string{"若叶", "Wakamo"}},
		{Canonical: "阿兹莎", Aliases: []string{"阿兹莎", "Azusa"}},
		{Canonical: "优香", Aliases: []string{"优香", "早濑优香", "Yuuka"}},
		{Canonical: "调月莉音", Aliases: []string{"调月莉音", "Tsurumaki Tsukasa"}},
	}},
	{Canonical: "胜利女神 NIKKE", Variants: []string{"胜利女神 NIKKE", "NIKKE", "胜利女神", "Goddess of Victory Nikke", "Nikke", "妮姬"}, Characters: []CharEntry{
		{Canonical: "拉毗", Aliases: []string{"拉毗", "Rapi"}},
		{Canonical: "阿尼斯", Aliases: []string{"阿尼斯", "Anis"}},
		{Canonical: "妮恩", Aliases: []string{"妮恩", "Neon"}},
		{Canonical: "玛丽安", Aliases: []string{"玛丽安", "Marian"}},
		{Canonical: "爱丽丝", Aliases: []string{"爱丽丝", "Alice"}},
		{Canonical: "迪塞尔", Aliases: []string{"迪塞尔", "Diesel"}},
		{Canonical: "艾玛", Aliases: []string{"艾玛", "Emma"}},
		{Canonical: "维斯提", Aliases: []string{"维斯提", "Vesti"}},
		{Canonical: "银华", Aliases: []string{"银华", "Eunhwa"}},
		{Canonical: "露菲", Aliases: []string{"露菲", "Rupee"}},
		{Canonical: "安", Aliases: []string{"安", "Anne"}},
		{Canonical: "玛丽", Aliases: []string{"玛丽", "Mary"}},
		{Canonical: "佩珀", Aliases: []string{"佩珀", "Pepper"}},
		{Canonical: "舒格", Aliases: []string{"舒格", "Sugar"}},
		{Canonical: "米尔克", Aliases: []string{"米尔克", "Milk"}},
		{Canonical: "沃尔姆", Aliases: []string{"沃尔姆", "Volume"}},
		{Canonical: "吉尔蒂", Aliases: []string{"吉尔蒂", "Guilty"}},
		{Canonical: "辛", Aliases: []string{"辛", "Sin"}},
		{Canonical: "赫尔姆", Aliases: []string{"赫尔姆", "Helm"}},
		{Canonical: "马斯塔", Aliases: []string{"马斯塔", "Mast"}},
		{Canonical: "安克", Aliases: []string{"安克", "Anchor"}},
		{Canonical: "布丽德", Aliases: []string{"布丽德", "Brid"}},
		{Canonical: "红莲", Aliases: []string{"红莲", "Scarlet"}},
		{Canonical: "长发公主", Aliases: []string{"长发公主", "Rapunzel"}},
		{Canonical: "白雪公主", Aliases: []string{"白雪公主", "Snow White"}},
		{Canonical: "玫瑰", Aliases: []string{"玫瑰", "Rose"}},
		{Canonical: "白", Aliases: []string{"白", "Weiss"}},
		{Canonical: "黑", Aliases: []string{"黑", "Noir"}},
		{Canonical: "小红帽", Aliases: []string{"小红帽", "Red Hood"}},
		{Canonical: "王冠", Aliases: []string{"王冠", "Crown"}},
		{Canonical: "铃铛", Aliases: []string{"铃铛", "Chime"}},
		{Canonical: "娜迦", Aliases: []string{"娜迦", "Naga"}},
		{Canonical: "提亚", Aliases: []string{"提亚", "Tia"}},
		{Canonical: "D", Aliases: []string{"D"}},
		{Canonical: "K", Aliases: []string{"K"}},
		{Canonical: "艾莉格", Aliases: []string{"艾莉格", "Elegg"}},
		{Canonical: "樱花", Aliases: []string{"樱花", "Sakura"}},
		{Canonical: "罗莎娜", Aliases: []string{"罗莎娜", "Rosanna"}},
		{Canonical: "莫兰", Aliases: []string{"莫兰", "Moran"}},
		{Canonical: "多萝西", Aliases: []string{"多萝西", "Dorothy"}},
		{Canonical: "哈兰", Aliases: []string{"哈兰", "Harran"}},
		{Canonical: "伊莎贝尔", Aliases: []string{"伊莎贝尔", "Isabel"}},
		{Canonical: "诺亚", Aliases: []string{"诺亚", "Noah"}},
		{Canonical: "现代者", Aliases: []string{"现代者", "Modernia"}},
		{Canonical: "虚无者", Aliases: []string{"虚无者", "Nihilister"}},
		{Canonical: "灰姑娘", Aliases: []string{"灰姑娘", "Cinderella"}},
	}},
	{Canonical: "鸣潮", Variants: []string{"鸣潮", "Wuthering Waves", "WW"}, Characters: []CharEntry{
		{Canonical: "秧秧", Aliases: []string{"秧秧", "Yangyang"}},
		{Canonical: "赤霞", Aliases: []string{"赤霞", "Chixia"}},
		{Canonical: "白芷", Aliases: []string{"白芷", "Baizhi"}},
		{Canonical: "吟霖", Aliases: []string{"吟霖", "Yinlin"}},
		{Canonical: "鉴心", Aliases: []string{"鉴心", "Jianxin"}},
		{Canonical: "安可", Aliases: []string{"安可", "Encore"}},
		{Canonical: "散华", Aliases: []string{"散华", "Sanhua"}},
		{Canonical: "丹瑾", Aliases: []string{"丹瑾", "Danjin"}},
		{Canonical: "卡梅莉亚", Aliases: []string{"卡梅莉亚", "Camellya"}},
		{Canonical: "灯灯", Aliases: []string{"灯灯", "Lumi"}},
		{Canonical: "桃祈", Aliases: []string{"桃祈", "Taoqi"}},
		{Canonical: "釉瑚", Aliases: []string{"釉瑚", "Youhu"}},
		{Canonical: "折枝", Aliases: []string{"折枝", "Zhezhi"}},
		{Canonical: "守岸人", Aliases: []string{"守岸人", "Shorekeeper"}},
		{Canonical: "卡洛塔", Aliases: []string{"卡洛塔", "Carlotta"}},
		{Canonical: "罗西亚", Aliases: []string{"罗西亚", "Roccia"}},
		{Canonical: "坎塔蕾拉", Aliases: []string{"坎塔蕾拉", "Cantarella"}},
		{Canonical: "长离", Aliases: []string{"长离", "Changli"}},
		{Canonical: "千咲", Aliases: []string{"千咲", "Chisato"}},
		{Canonical: "夏空", Aliases: []string{"夏空"}},
		{Canonical: "尤诺", Aliases: []string{"尤诺"}},
		{Canonical: "西格莉卡", Aliases: []string{"西格莉卡"}},
		{Canonical: "卡提希娅", Aliases: []string{"卡提希娅"}},
		{Canonical: "露帕", Aliases: []string{"露帕"}},
		{Canonical: "珂莱塔", Aliases: []string{"珂莱塔", "Carlotta Montelli"}},
		{Canonical: "菲比", Aliases: []string{"菲比", "Phoebe"}},
	}},
	{Canonical: "战双帕弥什", Variants: []string{"战双帕弥什", "Punishing Gray Raven", "PGR"}, Characters: []CharEntry{
		{Canonical: "露西亚", Aliases: []string{"露西亚", "Lucia"}},
		{Canonical: "丽芙", Aliases: []string{"丽芙", "Liv"}},
		{Canonical: "七实", Aliases: []string{"七实", "Nanami"}},
		{Canonical: "卡列尼娜", Aliases: []string{"卡列尼娜", "Karenina"}},
		{Canonical: "比安卡", Aliases: []string{"比安卡", "Bianca"}},
		{Canonical: "艾丽莎", Aliases: []string{"艾丽莎", "Alisa"}},
		{Canonical: "罗塞塔", Aliases: []string{"罗塞塔", "Rosetta"}},
		{Canonical: "苏菲亚", Aliases: []string{"苏菲亚", "Sophia"}},
		{Canonical: "薇拉", Aliases: []string{"薇拉", "Vera"}},
		{Canonical: "曲", Aliases: []string{"曲", "Qu"}},
		{Canonical: "蒲牢", Aliases: []string{"蒲牢", "Pulao"}},
		{Canonical: "露娜", Aliases: []string{"露娜", "Luna"}},
		{Canonical: "塞琳娜", Aliases: []string{"塞琳娜", "Selena"}},
		{Canonical: "21号", Aliases: []string{"21号", "No 21"}},
		{Canonical: "万世", Aliases: []string{"万世", "Wanshi"}},
		{Canonical: "艾拉", Aliases: []string{"艾拉", "Ayla"}},
		{Canonical: "邦比娜塔", Aliases: []string{"邦比娜塔", "Bambinata"}},
		{Canonical: "亚里莎", Aliases: []string{"亚里莎", "Arisa"}},
	}},
	{Canonical: "少女前线", Variants: []string{"少女前线", "Girls Frontline", "GFL", "少前"}, Characters: []CharEntry{
		{Canonical: "M4A1", Aliases: []string{"M4A1"}},
		{Canonical: "AR15", Aliases: []string{"AR15", "AR-15"}},
		{Canonical: "M16A1", Aliases: []string{"M16A1"}},
		{Canonical: "SOPMOD2", Aliases: []string{"SOPMOD2", "SOPMOD II", "狗子"}},
		{Canonical: "UMP45", Aliases: []string{"UMP45", "45"}},
		{Canonical: "UMP9", Aliases: []string{"UMP9", "9"}},
		{Canonical: "HK416", Aliases: []string{"HK416", "416"}},
		{Canonical: "WA2000", Aliases: []string{"WA2000", "WA"}},
		{Canonical: "春田", Aliases: []string{"春田", "Springfield"}},
		{Canonical: "DSR50", Aliases: []string{"DSR50", "DSR-50"}},
		{Canonical: "M200", Aliases: []string{"M200"}},
		{Canonical: "AN94", Aliases: []string{"AN94", "AN-94"}},
		{Canonical: "AK12", Aliases: []string{"AK12", "AK-12"}},
		{Canonical: "RPK16", Aliases: []string{"RPK16", "RPK-16"}},
		{Canonical: "雷电", Aliases: []string{"雷电", "Thunder"}},
		{Canonical: "竞争者", Aliases: []string{"竞争者", "Contender"}},
		{Canonical: "李恩菲尔德", Aliases: []string{"李恩菲尔德", "Lee-Enfield"}},
		{Canonical: "莫辛纳甘", Aliases: []string{"莫辛纳甘", "Mosin-Nagat"}},
		{Canonical: "SVD", Aliases: []string{"SVD"}},
		{Canonical: "PPK", Aliases: []string{"PPK"}},
		{Canonical: "M1911", Aliases: []string{"M1911"}},
		{Canonical: "丹德莱", Aliases: []string{"丹德莱", "Dandelion"}},
		{Canonical: "M4 SOPMOD II", Aliases: []string{"M4 SOPMOD II"}},
	}},
	{Canonical: "无期迷途", Variants: []string{"无期迷途", "Path to Nowhere", "PtN"}, Characters: []CharEntry{
		{Canonical: "沙利叶", Aliases: []string{"沙利叶", "Shalom"}},
		{Canonical: "卓雅", Aliases: []string{"卓雅", "Zoya"}},
		{Canonical: "赫卡忒", Aliases: []string{"赫卡忒", "Hecate"}},
		{Canonical: "爱丽妮", Aliases: []string{"爱丽妮", "Eirene"}},
		{Canonical: "渡鸦", Aliases: []string{"渡鸦", "Raven"}},
		{Canonical: "德蕾雅", Aliases: []string{"德蕾雅", "Dreya"}},
		{Canonical: "观星者", Aliases: []string{"观星者", "Stargazer"}},
		{Canonical: "阿黛拉", Aliases: []string{"阿黛拉", "Adela"}},
		{Canonical: "白逸", Aliases: []string{"白逸", "Baiyi"}},
		{Canonical: "伊琳娜", Aliases: []string{"伊琳娜", "Irina"}},
		{Canonical: "麦昆", Aliases: []string{"麦昆", "McQueen"}},
		{Canonical: "恩菲尔", Aliases: []string{"恩菲尔", "Enfer"}},
		{Canonical: "可可莉克", Aliases: []string{"可可莉克", "Coquelic"}},
		{Canonical: "瑟琳", Aliases: []string{"瑟琳", "Shalom"}},
		{Canonical: "雷比尼斯", Aliases: []string{"雷比尼斯", "Labyrinth"}},
		{Canonical: "佩姬", Aliases: []string{"佩姬", "Pearl"}},
		{Canonical: "卡门", Aliases: []string{"卡门", "Carmen"}},
		{Canonical: "兰利", Aliases: []string{"兰利", "Langley"}},
		{Canonical: "哈梅尔", Aliases: []string{"哈梅尔", "Hamel"}},
		{Canonical: "黛伦", Aliases: []string{"黛伦", "Deren"}},
		{Canonical: "安", Aliases: []string{"安", "Anne"}},
	}},
	{Canonical: "尘白禁区", Variants: []string{"尘白禁区", "Snowbreak"}, Characters: []CharEntry{
		{Canonical: "里芙", Aliases: []string{"里芙", "Lyris"}},
		{Canonical: "芬妮", Aliases: []string{"芬妮", "Fenny"}},
		{Canonical: "瑟瑞斯", Aliases: []string{"瑟瑞斯", "Siris"}},
		{Canonical: "茉莉安", Aliases: []string{"茉莉安", "Mauxir"}},
		{Canonical: "卡提娅", Aliases: []string{"卡提娅", "Katya"}},
		{Canonical: "瑶", Aliases: []string{"瑶", "Yao"}},
		{Canonical: "凌", Aliases: []string{"凌", "Ling"}},
		{Canonical: "辰", Aliases: []string{"辰", "Chen"}},
		{Canonical: "玛利亚", Aliases: []string{"玛利亚", "Marian"}},
		{Canonical: "妮塔", Aliases: []string{"妮塔", "Nita"}},
		{Canonical: "恩雅", Aliases: []string{"恩雅", "Enya"}},
		{Canonical: "阿克娅", Aliases: []string{"阿克娅", "Acacia"}},
		{Canonical: "苔丝", Aliases: []string{"苔丝", "Tess"}},
		{Canonical: "晴", Aliases: []string{"晴", "Haru"}},
	}},
	{Canonical: "千年之旅", Variants: []string{"千年之旅", "Aether Gazer"}, Characters: []CharEntry{
		{Canonical: "波塞冬", Aliases: []string{"波塞冬", "Poseidon"}},
		{Canonical: "雅典娜", Aliases: []string{"雅典娜", "Athena"}},
		{Canonical: "赫拉", Aliases: []string{"赫拉", "Hera"}},
		{Canonical: "阿尔忒弥斯", Aliases: []string{"阿尔忒弥斯", "Artemis"}},
		{Canonical: "天照", Aliases: []string{"天照", "Amaterasu"}},
		{Canonical: "月读", Aliases: []string{"月读", "Tsukuyomi"}},
		{Canonical: "女娲", Aliases: []string{"女娲", "Nuwa"}},
		{Canonical: "书", Aliases: []string{"书", "Shu"}},
		{Canonical: "赫利俄斯", Aliases: []string{"赫利俄斯", "Hel"}},
	}},
	{Canonical: "白夜极光", Variants: []string{"白夜极光", "Alchemy Stars"}, Characters: []CharEntry{
		{Canonical: "维多利亚", Aliases: []string{"维多利亚", "Victoria"}},
		{Canonical: "伊芙", Aliases: []string{"伊芙", "Eve"}},
		{Canonical: "拉斐尔", Aliases: []string{"拉斐尔", "Raphael"}},
		{Canonical: "绯螺", Aliases: []string{"绯螺", "Hiiro"}},
		{Canonical: "奥菲娜", Aliases: []string{"奥菲娜", "Ophina"}},
		{Canonical: "蕾奥娜", Aliases: []string{"蕾奥娜", "Leona"}},
	}},
	{Canonical: "阴阳师", Variants: []string{"阴阳师", "Onmyoji"}, Characters: []CharEntry{
		{Canonical: "不知火", Aliases: []string{"不知火", "Shiranui"}},
		{Canonical: "妖刀姬", Aliases: []string{"妖刀姬", "Yoto Hime"}},
		{Canonical: "姑获鸟", Aliases: []string{"姑获鸟", "Ubume"}},
		{Canonical: "青行灯", Aliases: []string{"青行灯", "Aooni"}},
		{Canonical: "辉夜姬", Aliases: []string{"辉夜姬", "Kaguyahime"}},
		{Canonical: "玉藻前", Aliases: []string{"玉藻前", "Tamamo no Mae", "大舅妈"}},
		{Canonical: "鬼切", Aliases: []string{"鬼切", "Onikiri"}},
		{Canonical: "铃鹿御前", Aliases: []string{"铃鹿御前", "Suzuka Gozen"}},
		{Canonical: "紧那罗", Aliases: []string{"紧那罗", "Kinnara"}},
		{Canonical: "帝释天", Aliases: []string{"帝释天", "Taishakuten"}},
		{Canonical: "阿修罗", Aliases: []string{"阿修罗", "Asura"}},
		{Canonical: "千姬", Aliases: []string{"千姬", "Senhime"}},
		{Canonical: "缘结神", Aliases: []string{"缘结神", "Musubi"}},
		{Canonical: "食灵", Aliases: []string{"食灵", "Shokurei"}},
		{Canonical: "雪女", Aliases: []string{"雪女", "Yuki Onna"}},
		{Canonical: "清姬", Aliases: []string{"清姬", "Kiyohime"}},
		{Canonical: "红叶", Aliases: []string{"红叶", "Momiji"}},
		{Canonical: "面灵气", Aliases: []string{"面灵气", "Menreiki"}},
		{Canonical: "大天狗", Aliases: []string{"大天狗", "Ootengu"}},
		{Canonical: "酒吞童子", Aliases: []string{"酒吞童子", "Shuten Doji"}},
		{Canonical: "茨木童子", Aliases: []string{"茨木童子", "Ibaraki Doji"}},
	}},
	{Canonical: "第五人格", Variants: []string{"第五人格", "Identity V"}, Characters: []CharEntry{
		{Canonical: "特蕾西", Aliases: []string{"特蕾西", "Tracy", "机械师"}},
		{Canonical: "艾玛", Aliases: []string{"艾玛", "Emma", "园丁"}},
		{Canonical: "玛尔塔", Aliases: []string{"玛尔塔", "Martha", "空军"}},
		{Canonical: "海伦娜", Aliases: []string{"海伦娜", "Helena", "盲女"}},
		{Canonical: "薇拉", Aliases: []string{"薇拉", "Vera", "调香师"}},
		{Canonical: "帕特丽夏", Aliases: []string{"帕特丽夏", "Patricia", "祭司"}},
		{Canonical: "莉莉", Aliases: []string{"莉莉", "Lily", "入殓师"}},
		{Canonical: "黛米", Aliases: []string{"黛米", "Demi", "调酒师"}},
		{Canonical: "艾达", Aliases: []string{"艾达", "Ada", "心理学家"}},
		{Canonical: "艾米丽", Aliases: []string{"艾米丽", "Emily", "医生"}},
		{Canonical: "菲欧娜", Aliases: []string{"菲欧娜", "Fiona", "祭司"}},
		{Canonical: "玛格丽莎", Aliases: []string{"玛格丽莎", "Margaretha", "舞女"}},
	}},
	{Canonical: "永劫无间", Variants: []string{"永劫无间", "Naraka Bladepoint"}, Characters: []CharEntry{
		{Canonical: "宁红夜", Aliases: []string{"宁红夜", "Viper Ning"}},
		{Canonical: "胡桃", Aliases: []string{"胡桃", "Kurumi"}},
		{Canonical: "迦南", Aliases: []string{"迦南", "Canaan"}},
		{Canonical: "季沧海", Aliases: []string{"季沧海", "Tarka Ji"}},
		{Canonical: "天海", Aliases: []string{"天海", "Tianhai"}},
		{Canonical: "妖刀姬", Aliases: []string{"妖刀姬", "Yoto Hime"}},
		{Canonical: "崔三娘", Aliases: []string{"崔三娘", "Valda Cui"}},
		{Canonical: "顾清寒", Aliases: []string{"顾清寒", "Justina Gu"}},
		{Canonical: "武运", Aliases: []string{"武运", "Wuchen"}},
		{Canonical: "阴佩真", Aliases: []string{"阴佩真", "Ziping Yin"}},
		{Canonical: "席拉", Aliases: []string{"席拉", "Tessa"}},
	}},
	{Canonical: "幻塔", Variants: []string{"幻塔", "Tower of Fantasy", "TOF"}, Characters: []CharEntry{
		{Canonical: "奈美西斯", Aliases: []string{"奈美西斯", "Nemesis"}},
		{Canonical: "钴蓝", Aliases: []string{"钴蓝", "Cobalt B"}},
		{Canonical: "克劳迪娅", Aliases: []string{"克劳迪娅", "Claudia"}},
		{Canonical: "弗丽嘉", Aliases: []string{"弗丽嘉", "Frigg"}},
		{Canonical: "莱茵", Aliases: []string{"莱茵", "Lyra"}},
		{Canonical: "红莲", Aliases: []string{"红莲", "Ruby"}},
		{Canonical: "凛夜", Aliases: []string{"凛夜", "Saki Fuwa"}},
		{Canonical: "琳", Aliases: []string{"琳", "Lin"}},
		{Canonical: "安娜贝拉", Aliases: []string{"安娜贝拉", "Annabella"}},
		{Canonical: "伊卡洛斯", Aliases: []string{"伊卡洛斯", "Icarus"}},
		{Canonical: "天琅", Aliases: []string{"天琅", "Tianlang"}},
		{Canonical: "乌米", Aliases: []string{"乌米", "Umi"}},
		{Canonical: "菲欧娜", Aliases: []string{"菲欧娜", "Fiona"}},
		{Canonical: "格温", Aliases: []string{"格温", "Gwen"}},
		{Canonical: "白凌", Aliases: []string{"白凌", "Bai Ling"}},
		{Canonical: "梅丽尔", Aliases: []string{"梅丽尔", "Meryl"}},
		{Canonical: "赛弥尔", Aliases: []string{"赛弥尔", "Samir"}},
		{Canonical: "修玛", Aliases: []string{"修玛", "Huma"}},
		{Canonical: "可可丽特", Aliases: []string{"可可丽特", "Cocoritter"}},
		{Canonical: "零", Aliases: []string{"零", "Zero"}},
		{Canonical: "希尔达", Aliases: []string{"希尔达", "Hilda"}},
		{Canonical: "佩佩", Aliases: []string{"佩佩", "Pepper"}},
	}},
	{Canonical: "Fate Grand Order", Variants: []string{"Fate Grand Order", "Fate GO", "FGO", "Fate"}, Characters: []CharEntry{
		{Canonical: "阿尔托莉雅", Aliases: []string{"阿尔托莉雅", "Artoria", "Saber", "呆毛王", "亚瑟王"}},
		{Canonical: "贞德", Aliases: []string{"贞德", "Jeanne", "圣女"}},
		{Canonical: "斯卡哈", Aliases: []string{"斯卡哈", "Scathach", "师匠"}},
		{Canonical: "玉藻前", Aliases: []string{"玉藻前", "Tamamo", "Caster", "狐狸"}},
		{Canonical: "源赖光", Aliases: []string{"源赖光", "Raikou", "乳光"}},
		{Canonical: "宫本武藏", Aliases: []string{"宫本武藏", "Musashi"}},
		{Canonical: "冲田总司", Aliases: []string{"冲田总司", "Okita"}},
		{Canonical: "织田信长", Aliases: []string{"织田信长", "Nobunaga", "信长"}},
		{Canonical: "溶解莉莉丝", Aliases: []string{"溶解莉莉丝", "Meltlilith", "Melt"}},
		{Canonical: "热情迷唇", Aliases: []string{"热情迷唇", "Passionlip", "Lip"}},
		{Canonical: "BB", Aliases: []string{"BB"}},
		{Canonical: "伊什塔尔", Aliases: []string{"伊什塔尔", "Ishtar", "远坂凛"}},
		{Canonical: "埃列什基伽勒", Aliases: []string{"埃列什基伽勒", "Ereshkigal", "艾蕾"}},
		{Canonical: "魁札尔科亚特尔", Aliases: []string{"魁札尔科亚特尔", "Quetzalcoatl"}},
		{Canonical: "梅芙", Aliases: []string{"梅芙", "Medb"}},
		{Canonical: "布狄卡", Aliases: []string{"布狄卡", "Boudica"}},
		{Canonical: "玛塔哈丽", Aliases: []string{"玛塔哈丽", "Mata Hari"}},
		{Canonical: "尼禄", Aliases: []string{"尼禄", "Nero", "赤Saber"}},
		{Canonical: "伊丽莎白", Aliases: []string{"伊丽莎白", "Elizabeth"}},
		{Canonical: "美杜莎", Aliases: []string{"美杜莎", "Medusa", "Rider"}},
		{Canonical: "戈尔贡", Aliases: []string{"戈尔贡", "Gorgon"}},
		{Canonical: "安娜", Aliases: []string{"安娜", "Ana"}},
		{Canonical: "紫式部", Aliases: []string{"紫式部", "Murasaki"}},
		{Canonical: "清少纳言", Aliases: []string{"清少纳言", "Sei Shonagon"}},
		{Canonical: "杨贵妃", Aliases: []string{"杨贵妃", "Yang Guifei"}},
		{Canonical: "虞美人", Aliases: []string{"虞美人", "Yu Miaoyi"}},
		{Canonical: "燕青", Aliases: []string{"燕青", "Qin Liangyu"}},
		{Canonical: "加雷斯", Aliases: []string{"加雷斯", "Gareth"}},
		{Canonical: "阿比盖尔", Aliases: []string{"阿比盖尔", "Abigail"}},
		{Canonical: "赛蕾娜", Aliases: []string{"赛蕾娜", "Sitonai"}},
		{Canonical: "太空伊什塔尔", Aliases: []string{"太空伊什塔尔", "Space Ishtar"}},
		{Canonical: "奥德修斯", Aliases: []string{"奥德修斯", "Odysseus"}},
	}},
	{Canonical: "Fate Stay Night", Variants: []string{"Fate Stay Night", "FSN"}, Characters: []CharEntry{
		{Canonical: "Saber", Aliases: []string{"Saber", "阿尔托莉雅", "Artoria", "呆毛"}},
		{Canonical: "远坂凛", Aliases: []string{"远坂凛", "Rin", "凛"}},
		{Canonical: "间桐樱", Aliases: []string{"间桐樱", "Sakura", "樱"}},
		{Canonical: "伊莉雅", Aliases: []string{"伊莉雅", "Illya", "伊莉雅斯菲尔"}},
		{Canonical: "Rider", Aliases: []string{"Rider", "美杜莎", "Medusa"}},
		{Canonical: "Caster", Aliases: []string{"Caster", "美狄亚", "Medea"}},
		{Canonical: "藤村大河", Aliases: []string{"藤村大河", "Taiga", "老虎"}},
	}},
	{Canonical: "Fate Zero", Variants: []string{"Fate Zero"}, Characters: []CharEntry{
		{Canonical: "爱丽丝菲尔", Aliases: []string{"爱丽丝菲尔", "Irisviel", "切嗣太太"}},
		{Canonical: "索拉乌", Aliases: []string{"索拉乌", "Sola Ui"}},
		{Canonical: "舞弥", Aliases: []string{"舞弥", "Maiya"}},
	}},
	{Canonical: "碧蓝幻想", Variants: []string{"碧蓝幻想", "Granblue Fantasy", "GBF"}, Characters: []CharEntry{
		{Canonical: "姬塔", Aliases: []string{"姬塔", "Djeeta"}},
		{Canonical: "卡塔莉娜", Aliases: []string{"卡塔莉娜", "Katalina"}},
		{Canonical: "伊欧", Aliases: []string{"伊欧", "Io"}},
		{Canonical: "露莉亚", Aliases: []string{"露莉亚", "Lyria"}},
		{Canonical: "萝塞塔", Aliases: []string{"萝塞塔", "Rosetta"}},
		{Canonical: "娜露梅", Aliases: []string{"娜露梅", "Narumea"}},
		{Canonical: "尤艾尔", Aliases: []string{"尤艾尔", "Yuel"}},
		{Canonical: "索希艾", Aliases: []string{"索希艾", "Socie"}},
		{Canonical: "维拉", Aliases: []string{"维拉", "Vira"}},
		{Canonical: "菲莉", Aliases: []string{"菲莉", "Ferry"}},
		{Canonical: "贝阿特丽克斯", Aliases: []string{"贝阿特丽克斯", "Beatrix"}},
		{Canonical: "泽塔", Aliases: []string{"泽塔", "Zeta"}},
		{Canonical: "夏洛特", Aliases: []string{"夏洛特", "Charlotta"}},
		{Canonical: "席尔瓦", Aliases: []string{"席尔瓦", "Silva"}},
		{Canonical: "安", Aliases: []string{"安", "Anne"}},
	}},
	{Canonical: "公主连结", Variants: []string{"公主连结", "Princess Connect", "PCR", "公主连接"}, Characters: []CharEntry{
		{Canonical: "佩可莉姆", Aliases: []string{"佩可莉姆", "Pecorine", "吃货"}},
		{Canonical: "可可萝", Aliases: []string{"可可萝", "Kokkoro"}},
		{Canonical: "凯留", Aliases: []string{"凯留", "Kyaru", "凯露", "黑猫"}},
		{Canonical: "优衣", Aliases: []string{"优衣", "Yui", "抖M"}},
		{Canonical: "日日莉", Aliases: []string{"日日莉", "Hiyori"}},
		{Canonical: "怜", Aliases: []string{"怜", "Rei"}},
		{Canonical: "栞", Aliases: []string{"栞", "Shiori"}},
		{Canonical: "未奏希", Aliases: []string{"未奏希", "Mitsuki"}},
		{Canonical: "莫妮卡", Aliases: []string{"莫妮卡", "Monika"}},
		{Canonical: "纱织", Aliases: []string{"纱织", "Saren"}},
		{Canonical: "望", Aliases: []string{"望", "Nozomi"}},
		{Canonical: "千歌", Aliases: []string{"千歌", "Chika"}},
		{Canonical: "真步", Aliases: []string{"真步", "Mahomahu", "狐狸"}},
		{Canonical: "璃乃", Aliases: []string{"璃乃", "Rino"}},
		{Canonical: "美里", Aliases: []string{"美里", "Miri"}},
		{Canonical: "茜里", Aliases: []string{"茜里", "Akari"}},
		{Canonical: "美美", Aliases: []string{"美美", "Mimi"}},
		{Canonical: "露娜", Aliases: []string{"露娜", "Luna"}},
		{Canonical: "克莉丝提娜", Aliases: []string{"克莉丝提娜", "Christina"}},
		{Canonical: "杏奈", Aliases: []string{"杏奈", "Anna"}},
	}},
	{Canonical: "魔法纪录", Variants: []string{"魔法纪录", "Magia Record"}, Characters: []CharEntry{
		{Canonical: "环伊吕波", Aliases: []string{"环伊吕波", "Iroha"}},
		{Canonical: "七海八千代", Aliases: []string{"七海八千代", "Yachiyo"}},
		{Canonical: "由比鹤乃", Aliases: []string{"由比鹤乃", "Tsuruno"}},
		{Canonical: "二叶莎奈", Aliases: []string{"二叶莎奈", "Sana"}},
		{Canonical: "深月菲莉希亚", Aliases: []string{"深月菲莉希亚", "Felicia"}},
		{Canonical: "十咎桃子", Aliases: []string{"十咎桃子", "Momoko"}},
	}},
	{Canonical: "Apex Legends", Variants: []string{"Apex Legends", "Apex", "APEX"}, Characters: []CharEntry{
		{Canonical: "萝芭", Aliases: []string{"萝芭", "Loba"}},
		{Canonical: "沃特森", Aliases: []string{"沃特森", "Wattson"}},
		{Canonical: "恶灵", Aliases: []string{"恶灵", "Wraith"}},
		{Canonical: "班加罗尔", Aliases: []string{"班加罗尔", "Bangalore"}},
		{Canonical: "催化姬", Aliases: []string{"催化姬", "Catalyst"}},
		{Canonical: "瓦尔基里", Aliases: []string{"瓦尔基里", "Valkyrie"}},
		{Canonical: "地平线", Aliases: []string{"地平线", "Horizon"}},
		{Canonical: "疯玛吉", Aliases: []string{"疯玛吉", "Mad Maggie"}},
		{Canonical: "万蒂奇", Aliases: []string{"万蒂奇", "Vantage"}},
		{Canonical: "导线管", Aliases: []string{"导线管", "Conduit"}},
		{Canonical: "生命线", Aliases: []string{"生命线", "Lifeline"}},
		{Canonical: "暴雷", Aliases: []string{"暴雷", "Fuse"}},
	}},
	{Canonical: "Valorant", Variants: []string{"Valorant", "瓦罗兰特", "无畏契约", "VAL"}, Characters: []CharEntry{
		{Canonical: "捷风", Aliases: []string{"捷风", "Jett"}},
		{Canonical: "贤者", Aliases: []string{"贤者", "Sage"}},
		{Canonical: "蝰蛇", Aliases: []string{"蝰蛇", "Viper"}},
		{Canonical: "蕾娜", Aliases: []string{"蕾娜", "Reyna"}},
		{Canonical: "奇乐", Aliases: []string{"奇乐", "Killjoy"}},
		{Canonical: "雷兹", Aliases: []string{"雷兹", "Raze"}},
		{Canonical: "星礈", Aliases: []string{"星礈", "Astra"}},
		{Canonical: "斯凯", Aliases: []string{"斯凯", "Skye"}},
		{Canonical: "霓虹", Aliases: []string{"霓虹", "Neon"}},
		{Canonical: "黑梦", Aliases: []string{"黑梦", "Fade"}},
		{Canonical: "死锁", Aliases: []string{"死锁", "Deadlock"}},
		{Canonical: "珂乐芙", Aliases: []string{"珂乐芙", "Clove"}},
	}},
	{Canonical: "街头霸王", Variants: []string{"街头霸王", "街霸6", "街霸", "Street Fighter 6", "Street Fighter", "SF6", "SF"}, Characters: []CharEntry{
		{Canonical: "春丽", Aliases: []string{"春丽", "Chun Li", "春丽"}},
		{Canonical: "卡米", Aliases: []string{"卡米", "Cammy"}},
		{Canonical: "朱莉", Aliases: []string{"朱莉", "Juri", "韩蛛俐"}},
		{Canonical: "劳拉", Aliases: []string{"劳拉", "Laura"}},
		{Canonical: "神月卡琳", Aliases: []string{"神月卡琳", "Karin"}},
		{Canonical: "伊吹", Aliases: []string{"伊吹", "Ibuki"}},
		{Canonical: "真琴", Aliases: []string{"真琴", "Makoto"}},
		{Canonical: "樱", Aliases: []string{"樱", "Sakura"}},
		{Canonical: "萝丝", Aliases: []string{"萝丝", "Rose"}},
		{Canonical: "梅纳特", Aliases: []string{"梅纳特", "Menat"}},
		{Canonical: "毒药", Aliases: []string{"毒药", "Poison"}},
		{Canonical: "艾莲娜", Aliases: []string{"艾莲娜", "Elena"}},
		{Canonical: "C Viper", Aliases: []string{"C Viper", "Viper"}},
		{Canonical: "不知火舞", Aliases: []string{"不知火舞", "Mai Shiranui", "舞", "Mai"}},
	}},
	{Canonical: "拳皇", Variants: []string{"拳皇", "King of Fighters", "KOF"}, Characters: []CharEntry{
		{Canonical: "不知火舞", Aliases: []string{"不知火舞", "Mai Shiranui", "舞", "Mai"}},
		{Canonical: "坂崎百合", Aliases: []string{"坂崎百合", "Yuri Sakazaki", "百合"}},
		{Canonical: "雅典娜", Aliases: []string{"雅典娜", "Athena Asamiya", "麻宫雅典娜"}},
		{Canonical: "莉安娜", Aliases: []string{"莉安娜", "Leona Heidern"}},
		{Canonical: "库拉", Aliases: []string{"库拉", "Kula Diamond"}},
		{Canonical: "安琪儿", Aliases: []string{"安琪儿", "Angel"}},
		{Canonical: "布鲁玛丽", Aliases: []string{"布鲁玛丽", "Blue Mary", "玛丽"}},
		{Canonical: "凡妮莎", Aliases: []string{"凡妮莎", "Vanessa"}},
		{Canonical: "鞭", Aliases: []string{"鞭", "Whip"}},
		{Canonical: "神乐千鹤", Aliases: []string{"神乐千鹤", "Chizuru Kagura"}},
		{Canonical: "夏尔美", Aliases: []string{"夏尔美", "Shermie"}},
		{Canonical: "麦卓", Aliases: []string{"麦卓", "Mature"}},
		{Canonical: "薇思", Aliases: []string{"薇思", "Vice"}},
	}},
	{Canonical: "死或生", Variants: []string{"死或生", "生或死", "生或死5", "Dead or Alive 5", "Dead or Alive", "DOA5", "DOA"}, Characters: []CharEntry{
		{Canonical: "霞", Aliases: []string{"霞", "Kasumi"}},
		{Canonical: "绫音", Aliases: []string{"绫音", "Ayane"}},
		{Canonical: "瞳", Aliases: []string{"瞳", "Hitomi"}},
		{Canonical: "雷芳", Aliases: []string{"雷芳", "Lei Fang"}},
		{Canonical: "蒂娜", Aliases: []string{"蒂娜", "Tina"}},
		{Canonical: "海莲娜", Aliases: []string{"海莲娜", "Helena"}},
		{Canonical: "克里斯蒂", Aliases: []string{"克里斯蒂", "Christie"}},
		{Canonical: "红叶", Aliases: []string{"红叶", "Momiji"}},
		{Canonical: "瑞秋", Aliases: []string{"瑞秋", "Rachel"}},
		{Canonical: "穗乃果", Aliases: []string{"穗乃果", "Honoka"}},
		{Canonical: "玛丽萝丝", Aliases: []string{"玛丽萝丝", "Marie Rose"}},
		{Canonical: "女天狗", Aliases: []string{"女天狗", "Nyotengu"}},
		{Canonical: "Phase4", Aliases: []string{"Phase4", "Phase 4"}},
		{Canonical: "美咲", Aliases: []string{"美咲", "Misaki"}},
		{Canonical: "露娜", Aliases: []string{"露娜", "Luna"}},
		{Canonical: "环", Aliases: []string{"环", "Tamaki"}},
		{Canonical: "雪乃", Aliases: []string{"雪乃", "Yukino"}},
		{Canonical: "菲欧娜", Aliases: []string{"菲欧娜", "Fiona"}},
		{Canonical: "凪", Aliases: []string{"凪", "Nagisa"}},
		{Canonical: "小百合", Aliases: []string{"小百合", "Sayuri"}},
		{Canonical: "帕蒂", Aliases: []string{"帕蒂", "Patty"}},
		{Canonical: "莫妮卡", Aliases: []string{"莫妮卡", "Monica"}},
		{Canonical: "洛贝利亚", Aliases: []string{"洛贝利亚", "Lobelia"}},
		{Canonical: "奈奈美", Aliases: []string{"奈奈美", "Nanami"}},
		{Canonical: "艾莉丝", Aliases: []string{"艾莉丝", "Elise"}},
		{Canonical: "艾米", Aliases: []string{"艾米", "Amy"}},
		{Canonical: "香迪", Aliases: []string{"香迪", "Shandy"}},
		{Canonical: "小春", Aliases: []string{"小春", "Koharu"}},
		{Canonical: "蒂娜", Aliases: []string{"蒂娜", "Tina"}},
	}},
	{Canonical: "死或生 沙滩排球", Variants: []string{"死或生 沙滩排球", "DOAX", "DOAXVV"}, Characters: []CharEntry{
		{Canonical: "霞", Aliases: []string{"霞", "Kasumi"}},
		{Canonical: "绫音", Aliases: []string{"绫音", "Ayane"}},
		{Canonical: "瞳", Aliases: []string{"瞳", "Hitomi"}},
		{Canonical: "玛丽萝丝", Aliases: []string{"玛丽萝丝", "Marie Rose"}},
		{Canonical: "穗乃果", Aliases: []string{"穗乃果", "Honoka"}},
		{Canonical: "女天狗", Aliases: []string{"女天狗", "Nyotengu"}},
	}},
	{Canonical: "灵魂能力", Variants: []string{"灵魂能力", "Soul Calibur", "SC"}, Characters: []CharEntry{
		{Canonical: "索菲蒂亚", Aliases: []string{"索菲蒂亚", "Sophitia"}},
		{Canonical: "艾薇", Aliases: []string{"艾薇", "Ivy", "伊莎贝拉"}},
		{Canonical: "多喜", Aliases: []string{"多喜", "Taki"}},
		{Canonical: "成美那", Aliases: []string{"成美那", "Seong Mi Na"}},
		{Canonical: "卡珊德拉", Aliases: []string{"卡珊德拉", "Cassandra"}},
		{Canonical: "雪华", Aliases: []string{"雪华", "Setsuka"}},
		{Canonical: "提拉", Aliases: []string{"提拉", "Tira"}},
		{Canonical: "希尔德", Aliases: []string{"希尔德", "Hilde"}},
		{Canonical: "艾米", Aliases: []string{"艾米", "Amy"}},
		{Canonical: "薇奥拉", Aliases: []string{"薇奥拉", "Viola"}},
		{Canonical: "蕾夏", Aliases: []string{"蕾夏", "Leixia"}},
		{Canonical: "凪", Aliases: []string{"凪", "Natsu"}},
	}},
	{Canonical: "真人快打", Variants: []string{"真人快打", "Mortal Kombat", "MK"}, Characters: []CharEntry{
		{Canonical: "索妮娅", Aliases: []string{"索妮娅", "Sonya", "Sonya Blade"}},
		{Canonical: "吉塔娜", Aliases: []string{"吉塔娜", "Kitana"}},
		{Canonical: "米莉娜", Aliases: []string{"米莉娜", "Mileena"}},
		{Canonical: "翡翠", Aliases: []string{"翡翠", "Jade"}},
		{Canonical: "辛黛尔", Aliases: []string{"辛黛尔", "Sindel"}},
		{Canonical: "斯卡蕾特", Aliases: []string{"斯卡蕾特", "Skarlet"}},
		{Canonical: "卡西凯奇", Aliases: []string{"卡西凯奇", "Cassie Cage"}},
		{Canonical: "弗萝", Aliases: []string{"弗萝", "Frost"}},
		{Canonical: "阿什拉", Aliases: []string{"阿什拉", "Ashrah"}},
		{Canonical: "李梅", Aliases: []string{"李梅", "Li Mei"}},
		{Canonical: "塔尼亚", Aliases: []string{"塔尼亚", "Tanya"}},
		{Canonical: "妮塔拉", Aliases: []string{"妮塔拉", "Nitara"}},
		{Canonical: "希瓦", Aliases: []string{"希瓦", "Sheeva"}},
	}},
	{Canonical: "猎天使魔女", Variants: []string{"猎天使魔女", "Bayonetta", "蓓优妮塔"}, Characters: []CharEntry{
		{Canonical: "贝优妮塔", Aliases: []string{"贝优妮塔", "Bayonetta", "贝姐", "Cereza"}},
		{Canonical: "贞德", Aliases: []string{"贞德", "Jeanne"}},
		{Canonical: "罗莎", Aliases: []string{"罗莎", "Rosa"}},
		{Canonical: "薇奥拉", Aliases: []string{"薇奥拉", "Viola"}},
	}},
	{Canonical: "鬼泣", Variants: []string{"鬼泣5", "鬼泣", "Devil May Cry 5", "Devil May Cry", "DMC"}, Characters: []CharEntry{
		{Canonical: "翠西", Aliases: []string{"翠西", "Trish"}},
		{Canonical: "蕾蒂", Aliases: []string{"蕾蒂", "Lady", "玛丽"}},
		{Canonical: "妮可", Aliases: []string{"妮可", "Nico"}},
		{Canonical: "露西亚", Aliases: []string{"露西亚", "Lucia"}},
		{Canonical: "凯特", Aliases: []string{"凯特", "Kat"}},
	}},
	{Canonical: "女神异闻录", Variants: []string{"女神异闻录5", "女神异闻录 5", "女神异闻录3", "女神异闻录4", "女神异闻录", "Persona 5", "Persona 4", "Persona 3", "Persona", "P5", "P4", "P3"}, Characters: []CharEntry{
		{Canonical: "高卷杏", Aliases: []string{"高卷杏", "杏", "Ann", "Panther"}},
		{Canonical: "新岛真", Aliases: []string{"新岛真", "真", "Makoto", "Queen"}},
		{Canonical: "佐仓双叶", Aliases: []string{"佐仓双叶", "双叶", "Futaba", "Navi"}},
		{Canonical: "奥村春", Aliases: []string{"奥村春", "春", "Haru", "Noir"}},
		{Canonical: "芳泽霞", Aliases: []string{"芳泽霞", "霞", "Kasumi", "Violet"}},
		{Canonical: "拉雯妲", Aliases: []string{"拉雯妲", "Lavenza"}},
		{Canonical: "卡萝莉娜", Aliases: []string{"卡萝莉娜", "Caroline"}},
		{Canonical: "贾斯蒂丝", Aliases: []string{"贾斯蒂丝", "Justine"}},
		{Canonical: "新岛冴", Aliases: []string{"新岛冴", "Sae"}},
		{Canonical: "武见妙", Aliases: []string{"武见妙", "Tae", "死神医生"}},
		{Canonical: "一色若叶", Aliases: []string{"一色若叶", "Ichiko"}},
		{Canonical: "久须美", Aliases: []string{"久须美", "Hifumi"}},
		{Canonical: "千早", Aliases: []string{"千早", "Chihaya"}},
		{Canonical: "川上", Aliases: []string{"川上", "Sadayo"}},
		{Canonical: "花村阳子", Aliases: []string{"花村阳子", "Chie", "P4"}},
		{Canonical: "里中千枝", Aliases: []string{"里中千枝", "Chie Satonaka"}},
		{Canonical: "天城雪子", Aliases: []string{"天城雪子", "Yukiko"}},
		{Canonical: "巽完二", Aliases: []string{"巽完二", "Rise", "理世"}},
		{Canonical: "白钟直斗", Aliases: []string{"白钟直斗", "Naoto"}},
		{Canonical: "玛丽", Aliases: []string{"玛丽", "Marie"}},
		{Canonical: "桐条美鹤", Aliases: []string{"桐条美鹤", "Mitsuru"}},
		{Canonical: "岳羽由加莉", Aliases: []string{"岳羽由加莉", "Yukari"}},
		{Canonical: "山岸风花", Aliases: []string{"山岸风花", "Fuuka"}},
		{Canonical: "埃癸斯", Aliases: []string{"埃癸斯", "Aigis", "艾吉斯"}},
		{Canonical: "伊丽莎白", Aliases: []string{"伊丽莎白", "Elizabeth"}},
	}},
	{Canonical: "塞尔达传说", Variants: []string{"塞尔达传说 王国之泪", "塞尔达传说 旷野之息", "塞尔达传说", "塞尔达", "Zelda", "Breath of the Wild", "BOTW", "TOTK"}, Characters: []CharEntry{
		{Canonical: "塞尔达", Aliases: []string{"塞尔达", "Zelda", "公主"}},
		{Canonical: "英帕", Aliases: []string{"英帕", "Impa"}},
		{Canonical: "米法", Aliases: []string{"米法", "Mipha"}},
		{Canonical: "乌尔波扎", Aliases: []string{"乌尔波扎", "Urbosa"}},
		{Canonical: "露珠", Aliases: []string{"露珠", "Riju"}},
		{Canonical: "帕雅", Aliases: []string{"帕雅", "Paya"}},
		{Canonical: "普尔亚", Aliases: []string{"普尔亚", "Purah"}},
		{Canonical: "中庭", Aliases: []string{"中庭", "Midna"}},
		{Canonical: "泰特拉", Aliases: []string{"泰特拉", "Tetra"}},
		{Canonical: "希克", Aliases: []string{"希克", "Sheik"}},
	}},
	{Canonical: "火焰纹章", Variants: []string{"火焰纹章", "Fire Emblem", "FE"}, Characters: []CharEntry{
		{Canonical: "贝雷特", Aliases: []string{"贝雷特", "Byleth", "老师"}},
		{Canonical: "艾黛尔贾特", Aliases: []string{"艾黛尔贾特", "Edelgard", "皇女"}},
		{Canonical: "露米娜", Aliases: []string{"露米娜", "Lucina"}},
		{Canonical: "卡米拉", Aliases: []string{"卡米拉", "Camilla"}},
		{Canonical: "亚莎", Aliases: []string{"亚莎", "Azura"}},
		{Canonical: "神威", Aliases: []string{"神威", "Corrin"}},
		{Canonical: "赛莉卡", Aliases: []string{"赛莉卡", "Celica"}},
		{Canonical: "琳", Aliases: []string{"琳", "Lyn"}},
		{Canonical: "蒂亚莫", Aliases: []string{"蒂亚莫", "Tharja"}},
		{Canonical: "索提斯", Aliases: []string{"索提斯", "Sothis"}},
		{Canonical: "蕾雅", Aliases: []string{"蕾雅", "Rhea"}},
		{Canonical: "多萝西娅", Aliases: []string{"多萝西娅", "Dorothea"}},
		{Canonical: "英谷莉特", Aliases: []string{"英谷莉特", "Ingrid"}},
		{Canonical: "贝尔娜提塔", Aliases: []string{"贝尔娜提塔", "Bernadetta"}},
		{Canonical: "佩托拉", Aliases: []string{"佩托拉", "Petra"}},
		{Canonical: "梅尔赛德丝", Aliases: []string{"梅尔赛德丝", "Mercedes"}},
		{Canonical: "莉丝缇亚", Aliases: []string{"莉丝缇亚", "Lysithea"}},
		{Canonical: "玛丽安", Aliases: []string{"玛丽安", "Marianne"}},
		{Canonical: "希尔妲", Aliases: []string{"希尔妲", "Hilda"}},
		{Canonical: "雷欧妮", Aliases: []string{"雷欧妮", "Leonie"}},
		{Canonical: "萨米亚", Aliases: []string{"萨米亚", "Shamir"}},
	}},
	{Canonical: "异度神剑", Variants: []string{"异度神剑3", "异度神剑2", "异度神剑", "Xenoblade", "XB2", "XB3"}, Characters: []CharEntry{
		{Canonical: "焰", Aliases: []string{"焰", "Pyra", "_homura"}},
		{Canonical: "光", Aliases: []string{"光", "Mythra", "hikari"}},
		{Canonical: "尼亚", Aliases: []string{"尼亚", "Nia"}},
		{Canonical: "花", Aliases: []string{"花", "Poppi"}},
		{Canonical: "菲奥伦", Aliases: []string{"菲奥伦", "Fiora"}},
		{Canonical: "梅莉亚", Aliases: []string{"梅莉亚", "Melia"}},
		{Canonical: "莎尔拉特", Aliases: []string{"莎尔拉特", "Sharla"}},
		{Canonical: "布里吉德", Aliases: []string{"布里吉德", "Brighid"}},
		{Canonical: "潘多利亚", Aliases: []string{"潘多利亚", "Pandoria"}}, //nolint:misspell // "Pandoria" 是源数据原文的角色英文名（专有名词），非 Pandora 拼写错误
		{Canonical: "梅蕾芙", Aliases: []string{"梅蕾芙", "Morag"}},
		{Canonical: "萝拉", Aliases: []string{"萝拉", "Lora"}},
		{Canonical: "米奥", Aliases: []string{"米奥", "Mio"}},
		{Canonical: "安洁", Aliases: []string{"安洁", "Eunie"}},
		{Canonical: "圣奈", Aliases: []string{"圣奈", "Sena"}},
	}},
	{Canonical: "宝可梦", Variants: []string{"宝可梦", "精灵宝可梦", "Pokemon", "口袋妖怪", "神奇宝贝"}, Characters: []CharEntry{
		{Canonical: "竹兰", Aliases: []string{"竹兰", "Cynthia", "希罗娜"}},
		{Canonical: "小光", Aliases: []string{"小光", "Dawn", "光"}},
		{Canonical: "小遥", Aliases: []string{"小遥", "May"}},
		{Canonical: "莎莉娜", Aliases: []string{"莎莉娜", "Serena"}},
		{Canonical: "莉莉艾", Aliases: []string{"莉莉艾", "Lillie"}},
		{Canonical: "玛奥", Aliases: []string{"玛奥", "Marnie"}},
		{Canonical: "格洛丽亚", Aliases: []string{"格洛丽亚", "Gloria"}},
		{Canonical: "妮莫", Aliases: []string{"妮莫", "Nemona"}},
		{Canonical: "莉科", Aliases: []string{"莉科", "Liko"}},
		{Canonical: "内莎", Aliases: []string{"内莎", "Nessa"}},
		{Canonical: "比音", Aliases: []string{"比音", "Bea"}},
		{Canonical: "卡瑚", Aliases: []string{"卡瑚", "Korrina"}},
		{Canonical: "希特隆", Aliases: []string{"希特隆", "Clemont"}},
		{Canonical: "露莎米涅", Aliases: []string{"露莎米涅", "Lusamine"}},
		{Canonical: "茜紫拉", Aliases: []string{"茜紫拉", "Zinnia"}},
		{Canonical: "莉莉丝", Aliases: []string{"莉莉丝", "Lisia"}},
	}},
	{Canonical: "密特罗德", Variants: []string{"密特罗德", "Metroid", "银河战士"}, Characters: []CharEntry{
		{Canonical: "萨姆斯", Aliases: []string{"萨姆斯", "Samus", "萨姆斯阿兰"}},
	}},
	{Canonical: "魔兽世界", Variants: []string{"魔兽世界", "World of Warcraft", "WoW"}, Characters: []CharEntry{
		{Canonical: "吉安娜", Aliases: []string{"吉安娜", "Jaina", "吉安娜普罗德摩尔"}},
		{Canonical: "希尔瓦娜斯", Aliases: []string{"希尔瓦娜斯", "Sylvanas", "女妖之王"}},
		{Canonical: "泰兰德", Aliases: []string{"泰兰德", "Tyrande", "月之女祭司"}},
		{Canonical: "亚历山德拉萨斯", Aliases: []string{"亚历山德拉萨斯", "Alexstrasza", "红龙女王"}},
		{Canonical: "艾萨拉", Aliases: []string{"艾萨拉", "Azshara"}},
		{Canonical: "瓦莉拉", Aliases: []string{"瓦莉拉", "Valeera"}},
		{Canonical: "莉亚德琳", Aliases: []string{"莉亚德琳", "Liadrin"}},
		{Canonical: "玛维", Aliases: []string{"玛维", "Maiev", "守望者"}},
		{Canonical: "维蕾萨", Aliases: []string{"维蕾萨", "Vereesa"}},
		{Canonical: "瓦丝琪", Aliases: []string{"瓦丝琪", "Vashj"}},
		{Canonical: "奥妮克希亚", Aliases: []string{"奥妮克希亚", "Onyxia"}},
		{Canonical: "凡妮莎", Aliases: []string{"凡妮莎", "Vanessa"}},
		{Canonical: "加罗娜", Aliases: []string{"加罗娜", "Garona"}},
	}},
	{Canonical: "星际争霸", Variants: []string{"星际争霸", "StarCraft", "SC"}, Characters: []CharEntry{
		{Canonical: "凯瑞甘", Aliases: []string{"凯瑞甘", "Kerrigan", "刀锋女王"}},
		{Canonical: "诺娃", Aliases: []string{"诺娃", "Nova"}},
		{Canonical: "莎拉", Aliases: []string{"莎拉", "Sarah"}},
	}},
	{Canonical: "暗黑破坏神", Variants: []string{"暗黑破坏神4", "暗黑破坏神3", "暗黑破坏神", "Diablo 4", "Diablo 3", "Diablo", "D4", "D3"}, Characters: []CharEntry{
		{Canonical: "莉莉丝", Aliases: []string{"莉莉丝", "Lilith", "暗黑之母"}},
		{Canonical: "伊雷娜", Aliases: []string{"伊雷娜", "Eirena", "魔女"}},
		{Canonical: "艾希拉", Aliases: []string{"艾希拉", "Ashera"}},
	}},
	{Canonical: "质量效应", Variants: []string{"质量效应", "Mass Effect", "ME"}, Characters: []CharEntry{
		{Canonical: "莉亚拉", Aliases: []string{"莉亚拉", "Liara"}},
		{Canonical: "塔莉", Aliases: []string{"塔莉", "Tali"}},
		{Canonical: "阿什丽", Aliases: []string{"阿什丽", "Ashley"}},
		{Canonical: "米兰达", Aliases: []string{"米兰达", "Miranda"}},
		{Canonical: "杰克", Aliases: []string{"杰克", "Jack"}},
		{Canonical: "萨玛拉", Aliases: []string{"萨玛拉", "Samara"}},
		{Canonical: "霞", Aliases: []string{"霞", "Kasumi"}},
		{Canonical: "EDI", Aliases: []string{"EDI"}},
		{Canonical: "皮比", Aliases: []string{"皮比", "Peebee"}},
		{Canonical: "科拉", Aliases: []string{"科拉", "Cora"}},
		{Canonical: "维特拉", Aliases: []string{"维特拉", "Vetra"}},
	}},
	{Canonical: "龙腾世纪", Variants: []string{"龙腾世纪", "Dragon Age", "DA"}, Characters: []CharEntry{
		{Canonical: "莫瑞甘", Aliases: []string{"莫瑞甘", "Morrigan"}},
		{Canonical: "蕾莉安娜", Aliases: []string{"蕾莉安娜", "Leliana"}},
		{Canonical: "卡珊德拉", Aliases: []string{"卡珊德拉", "Cassandra"}},
		{Canonical: "塞拉", Aliases: []string{"塞拉", "Sera"}},
		{Canonical: "约瑟芬", Aliases: []string{"约瑟芬", "Josephine"}},
		{Canonical: "薇薇安", Aliases: []string{"薇薇安", "Vivienne"}},
		{Canonical: "梅丽尔", Aliases: []string{"梅丽尔", "Merrill"}},
		{Canonical: "伊莎贝拉", Aliases: []string{"伊莎贝拉", "Isabela"}},
	}},
	{Canonical: "刺客信条", Variants: []string{"刺客信条", "Assassins Creed", "AC"}, Characters: []CharEntry{
		{Canonical: "艾芙琳", Aliases: []string{"艾芙琳", "Aveline"}},
		{Canonical: "艾莉丝", Aliases: []string{"艾莉丝", "Elise"}},
		{Canonical: "伊薇", Aliases: []string{"伊薇", "Evie"}},
		{Canonical: "卡珊德拉", Aliases: []string{"卡珊德拉", "Kassandra"}},
		{Canonical: "艾雅", Aliases: []string{"艾雅", "Aya", "阿蒙内特"}},
		{Canonical: "艾沃尔", Aliases: []string{"艾沃尔", "Eivor"}},
		{Canonical: "蕾拉", Aliases: []string{"蕾拉", "Layla"}},
	}},
	{Canonical: "GTA", Variants: []string{"GTA5", "GTA6", "GTA", "Grand Theft Auto"}, Characters: []CharEntry{
		{Canonical: "崔西", Aliases: []string{"崔西", "Tracey"}},
		{Canonical: "米歇尔", Aliases: []string{"米歇尔", "Michelle"}},
	}},
	{Canonical: "荒野大镖客", Variants: []string{"荒野大镖客2", "荒野大镖客", "Red Dead Redemption", "RDR2", "RDR"}, Characters: []CharEntry{
		{Canonical: "赛迪", Aliases: []string{"赛迪", "Sadie"}},
		{Canonical: "阿比盖尔", Aliases: []string{"阿比盖尔", "Abigail"}},
		{Canonical: "邦妮", Aliases: []string{"邦妮", "Bonnie"}},
	}},
	{Canonical: "战神", Variants: []string{"战神", "战神 诸神黄昏", "God of War", "God of War Ragnarok"}, Characters: []CharEntry{
		{Canonical: "芙蕾雅", Aliases: []string{"芙蕾雅", "Freya"}},
		{Canonical: "丝露德", Aliases: []string{"丝露德", "Thrud"}},
		{Canonical: "菲", Aliases: []string{"菲", "Faye"}},
		{Canonical: "安格尔伯达", Aliases: []string{"安格尔伯达", "Angrboda"}},
	}},
	{Canonical: "地平线", Variants: []string{"地平线 西之绝境", "地平线 零之曙光", "地平线", "Horizon Forbidden West", "Horizon Zero Dawn", "Horizon"}, Characters: []CharEntry{
		{Canonical: "埃洛伊", Aliases: []string{"埃洛伊", "Aloy"}},
		{Canonical: "塔拉娜", Aliases: []string{"塔拉娜", "Talanah"}},
		{Canonical: "索娜", Aliases: []string{"索娜", "Sona"}},
	}},
	{Canonical: "死亡搁浅", Variants: []string{"死亡搁浅", "Death Stranding"}, Characters: []CharEntry{
		{Canonical: "芙拉吉尔", Aliases: []string{"芙拉吉尔", "Fragile"}},
		{Canonical: "玛玛", Aliases: []string{"玛玛", "Mama"}},
		{Canonical: "洛克妮", Aliases: []string{"洛克妮", "Lockne"}},
		{Canonical: "亚美莉", Aliases: []string{"亚美莉", "Amelie"}},
	}},
	{Canonical: "只狼", Variants: []string{"只狼", "只狼 影逝二度", "Sekiro"}, Characters: []CharEntry{
		{Canonical: "永真", Aliases: []string{"永真", "Emma"}},
		{Canonical: "九郎", Aliases: []string{"九郎", "Kuro"}},
	}},
	{Canonical: "对马岛之魂", Variants: []string{"对马岛之魂", "对马岛", "Ghost of Tsushima"}, Characters: []CharEntry{
		{Canonical: "结奈", Aliases: []string{"结奈", "Yuna"}},
		{Canonical: "政子", Aliases: []string{"政子", "Masako"}},
	}},
	{Canonical: "尼尔 人工生命", Variants: []string{"尼尔 人工生命", "尼尔人工生命", "NieR Replicant"}, Characters: []CharEntry{
		{Canonical: "凯妮", Aliases: []string{"凯妮", "Kaine"}},
		{Canonical: "艾米尔", Aliases: []string{"艾米尔", "Emil"}},
	}},
	{Canonical: "超次元游戏 海王星", Variants: []string{"超次元游戏 海王星", "海王星", "Neptunia"}, Characters: []CharEntry{
		{Canonical: "涅普缇努", Aliases: []string{"涅普缇努", "Neptune", "涅普", "紫色之心"}},
		{Canonical: "涅普姬雅", Aliases: []string{"涅普姬雅", "Nepgear", "紫色妹妹"}},
		{Canonical: "诺瓦露", Aliases: []string{"诺瓦露", "Noire", "黑色之心"}},
		{Canonical: "布兰", Aliases: []string{"布兰", "Blanc", "白色之心"}},
		{Canonical: "贝露", Aliases: []string{"贝露", "Vert", "绿色之心"}},
		{Canonical: "普露露特", Aliases: []string{"普露露特", "Plutia", "澪色之心"}},
		{Canonical: "优妮", Aliases: []string{"优妮", "Uni", "黑色妹妹"}},
		{Canonical: "萝姆", Aliases: []string{"萝姆", "Rom", "白色妹妹"}},
		{Canonical: "拉姆", Aliases: []string{"拉姆", "Ram", "白色妹妹"}},
		{Canonical: "空", Aliases: []string{"空", "Uzume", "澄色之心"}},
		{Canonical: "康帕", Aliases: []string{"康帕", "Compa"}},
		{Canonical: "IF", Aliases: []string{"IF", "爱耶芙"}},
	}},
	{Canonical: "闪乱神乐", Variants: []string{"闪乱神乐", "Senran Kagura"}, Characters: []CharEntry{
		{Canonical: "飞鸟", Aliases: []string{"飞鸟", "Asuka"}},
		{Canonical: "焰", Aliases: []string{"焰", "Homura"}},
		{Canonical: "雪泉", Aliases: []string{"雪泉", "Yumi"}},
		{Canonical: "雅绯", Aliases: []string{"雅绯", "Miyabi"}},
		{Canonical: "斑鸠", Aliases: []string{"斑鸠", "Ikaruga"}},
		{Canonical: "葛城", Aliases: []string{"葛城", "Katsuragi"}},
		{Canonical: "柳生", Aliases: []string{"柳生", "Yagyuu"}},
		{Canonical: "云雀", Aliases: []string{"云雀", "Hibari"}},
		{Canonical: "未来", Aliases: []string{"未来", "Mirai"}},
		{Canonical: "春花", Aliases: []string{"春花", "Haruka"}},
		{Canonical: "日影", Aliases: []string{"日影", "Hikage"}},
		{Canonical: "咏", Aliases: []string{"咏", "Yozakura"}},
		{Canonical: "紫", Aliases: []string{"紫", "Murasaki"}},
		{Canonical: "两姬", Aliases: []string{"两姬", "Ryouna"}},
		{Canonical: "两备", Aliases: []string{"两备", "Ryoubi"}},
		{Canonical: "神乐", Aliases: []string{"神乐", "Murakumo"}},
		{Canonical: "四季", Aliases: []string{"四季", "Shiki"}},
		{Canonical: "莲华", Aliases: []string{"莲华", "Renka"}},
		{Canonical: "烟花", Aliases: []string{"烟花", "Hanabi"}},
		{Canonical: "河童", Aliases: []string{"河童", "Kafuru"}},
		{Canonical: "大道寺", Aliases: []string{"大道寺", "Daidouji"}},
		{Canonical: "铃音", Aliases: []string{"铃音", "Rin"}},
		{Canonical: "雪不归", Aliases: []string{"雪不归", "Sayuri"}},
	}},
	{Canonical: "新世纪福音战士", Variants: []string{"新世纪福音战士", "福音战士", "EVA", "Evangelion"}, Characters: []CharEntry{
		{Canonical: "绫波丽", Aliases: []string{"绫波丽", "Rei", "丽", "绫波零"}},
		{Canonical: "明日香", Aliases: []string{"明日香", "Asuka", "式波"}},
		{Canonical: "葛城美里", Aliases: []string{"葛城美里", "Misato", "美里"}},
		{Canonical: "赤木律子", Aliases: []string{"赤木律子", "Ritsuko"}},
		{Canonical: "真希波", Aliases: []string{"真希波", "Mari"}},
		{Canonical: "铃原樱", Aliases: []string{"铃原樱", "Sakura"}},
		{Canonical: "伊吹玛雅", Aliases: []string{"伊吹玛雅", "Maya"}},
	}},
	{Canonical: "魔法少女小圆", Variants: []string{"魔法少女小圆", "Puella Magi Madoka Magica", "小圆"}, Characters: []CharEntry{
		{Canonical: "鹿目圆", Aliases: []string{"鹿目圆", "圆", "Madoka"}},
		{Canonical: "晓美焰", Aliases: []string{"晓美焰", "焰", "Homura", "吼姆拉"}},
		{Canonical: "巴麻美", Aliases: []string{"巴麻美", "麻美", "Mami", "学姐"}},
		{Canonical: "美树沙耶香", Aliases: []string{"美树沙耶香", "沙耶香", "Sayaka"}},
		{Canonical: "佐仓杏子", Aliases: []string{"佐仓杏子", "杏子", "Kyoko"}},
		{Canonical: "百江渚", Aliases: []string{"百江渚", "渚", "Nagisa"}},
	}},
	{Canonical: "鬼灭之刃", Variants: []string{"鬼灭之刃", "Demon Slayer", "Kimetsu no Yaiba"}, Characters: []CharEntry{
		{Canonical: "灶门祢豆子", Aliases: []string{"祢豆子", "Nezuko", "豆子"}},
		{Canonical: "蝴蝶忍", Aliases: []string{"蝴蝶忍", "忍", "Shinobu"}},
		{Canonical: "甘露寺蜜璃", Aliases: []string{"甘露寺蜜璃", "蜜璃", "Mitsuri", "恋柱"}},
		{Canonical: "栗花落香奈乎", Aliases: []string{"香奈乎", "Kanao"}},
		{Canonical: "珠世", Aliases: []string{"珠世", "Tamayo"}},
		{Canonical: "堕姬", Aliases: []string{"堕姬", "Daki"}},
		{Canonical: "胡蝶香奈惠", Aliases: []string{"香奈惠", "Kanae"}},
		{Canonical: "真妃", Aliases: []string{"真妃", "Makomo"}},
		{Canonical: "雏鹤", Aliases: []string{"雏鹤", "Hinatsuru"}},
		{Canonical: "牧绪", Aliases: []string{"牧绪", "Makio"}},
		{Canonical: "须磨", Aliases: []string{"须磨", "Suma"}},
	}},
	{Canonical: "咒术回战", Variants: []string{"咒术回战", "Jujutsu Kaisen", "JJK"}, Characters: []CharEntry{
		{Canonical: "钉崎野蔷薇", Aliases: []string{"钉崎", "野蔷薇", "Nobara"}},
		{Canonical: "禅院真希", Aliases: []string{"真希", "Maki"}},
		{Canonical: "冥冥", Aliases: []string{"冥冥", "Mei Mei"}},
		{Canonical: "家入硝子", Aliases: []string{"硝子", "Shoko"}},
		{Canonical: "庵歌姬", Aliases: []string{"歌姬", "Utahime"}},
		{Canonical: "三轮霞", Aliases: []string{"三轮", "Miwa"}},
		{Canonical: "理子", Aliases: []string{"理子", "Riko"}},
	}},
	{Canonical: "电锯人", Variants: []string{"电锯人", "Chainsaw Man", "CSM"}, Characters: []CharEntry{
		{Canonical: "玛奇玛", Aliases: []string{"玛奇玛", "Makima", "支配恶魔"}},
		{Canonical: "帕瓦", Aliases: []string{"帕瓦", "Power", "血之魔人"}},
		{Canonical: "姬野", Aliases: []string{"姬野", "Himeno"}},
		{Canonical: "小夜子", Aliases: []string{"小夜子", "Kobeni"}},
		{Canonical: "蕾塞", Aliases: []string{"蕾塞", "Reze"}},
		{Canonical: "光希", Aliases: []string{"光希", "Quanxi"}},
		{Canonical: "三鹰朝", Aliases: []string{"三鹰朝", "Asa"}},
		{Canonical: "战争恶魔", Aliases: []string{"战争恶魔", "Yoru"}},
		{Canonical: "那由多", Aliases: []string{"那由多", "Nayuta"}},
	}},
	{Canonical: "间谍过家家", Variants: []string{"间谍过家家", "Spy x Family"}, Characters: []CharEntry{
		{Canonical: "约尔", Aliases: []string{"约尔", "Yor", "杀手太太"}},
		{Canonical: "阿尼亚", Aliases: []string{"阿尼亚", "Anya"}},
		{Canonical: "菲奥娜", Aliases: []string{"菲奥娜", "Fiona"}},
		{Canonical: "贝琪", Aliases: []string{"贝琪", "Becky"}},
	}},
	{Canonical: "刀剑神域", Variants: []string{"刀剑神域", "Sword Art Online", "SAO"}, Characters: []CharEntry{
		{Canonical: "亚丝娜", Aliases: []string{"亚丝娜", "Asuna", "闪光"}},
		{Canonical: "莉法", Aliases: []string{"莉法", "Leafa", "直叶"}},
		{Canonical: "诗乃", Aliases: []string{"诗乃", "Sinon", "朝田诗乃"}},
		{Canonical: "优纪", Aliases: []string{"优纪", "Yuuki"}},
		{Canonical: "爱丽丝", Aliases: []string{"爱丽丝", "Alice", "整合骑士"}},
		{Canonical: "葵妮拉", Aliases: []string{"葵妮拉", "Quinella", "管理员"}},
		{Canonical: "利涅娜", Aliases: []string{"利涅娜", "Liena"}},
		{Canonical: "索尔蒂蕾娜", Aliases: []string{"索尔蒂蕾娜", "Sortiliena"}},
	}},
	{Canonical: "进击的巨人", Variants: []string{"进击的巨人", "Attack on Titan", "AOT", "进击"}, Characters: []CharEntry{
		{Canonical: "三笠", Aliases: []string{"三笠", "Mikasa", "三笠阿克曼"}},
		{Canonical: "阿尼", Aliases: []string{"阿尼", "Annie", "女型巨人"}},
		{Canonical: "希斯特莉亚", Aliases: []string{"希斯特莉亚", "Historia", "克里斯塔"}},
		{Canonical: "莎夏", Aliases: []string{"莎夏", "Sasha", "土豆女"}},
		{Canonical: "尤弥尔", Aliases: []string{"尤弥尔", "Ymir"}},
		{Canonical: "韩吉", Aliases: []string{"韩吉", "Hange"}},
		{Canonical: "皮克", Aliases: []string{"皮克", "Pieck", "车力巨人"}},
		{Canonical: "贾碧", Aliases: []string{"贾碧", "Gabi"}},
		{Canonical: "卡露拉", Aliases: []string{"卡露拉", "Carla"}},
	}},
	{Canonical: "火影忍者", Variants: []string{"火影忍者", "Naruto", "火影", "BORUTO"}, Characters: []CharEntry{
		{Canonical: "日向雏田", Aliases: []string{"雏田", "Hinata", "日向"}},
		{Canonical: "春野樱", Aliases: []string{"小樱", "樱", "Sakura"}},
		{Canonical: "纲手", Aliases: []string{"纲手", "Tsunade", "五代火影"}},
		{Canonical: "山中井野", Aliases: []string{"井野", "Ino"}},
		{Canonical: "日向花火", Aliases: []string{"花火", "Hanabi"}},
		{Canonical: "手鞠", Aliases: []string{"手鞠", "Temari"}},
		{Canonical: "漩涡玖辛奈", Aliases: []string{"玖辛奈", "Kushina"}},
		{Canonical: "小南", Aliases: []string{"小南", "Konan"}},
		{Canonical: "照美冥", Aliases: []string{"照美冥", "Mei"}},
		{Canonical: "夕日红", Aliases: []string{"夕日红", "Kurenai"}},
		{Canonical: "萨达拉", Aliases: []string{"萨达拉", "Sarada"}},
		{Canonical: "香磷", Aliases: []string{"香磷", "Karin"}},
		{Canonical: "黑土", Aliases: []string{"黑土", "Kurotsuchi"}},
	}},
	{Canonical: "海贼王", Variants: []string{"海贼王", "One Piece", "航海王"}, Characters: []CharEntry{
		{Canonical: "娜美", Aliases: []string{"娜美", "Nami", "猫贼"}},
		{Canonical: "妮可罗宾", Aliases: []string{"罗宾", "Robin", "妮可罗宾"}},
		{Canonical: "波雅汉库克", Aliases: []string{"汉库克", "Boa Hancock", "女帝"}},
		{Canonical: "薇薇", Aliases: []string{"薇薇", "Vivi", "奈菲鲁塔丽"}},
		{Canonical: "白星", Aliases: []string{"白星", "Shirahoshi"}},
		{Canonical: "佩罗娜", Aliases: []string{"佩罗娜", "Perona"}},
		{Canonical: "达斯琪", Aliases: []string{"达斯琪", "Tashigi"}},
		{Canonical: "大和", Aliases: []string{"大和", "Yamato"}},
		{Canonical: "加洛特", Aliases: []string{"加洛特", "Carrot"}},
		{Canonical: "卡莉法", Aliases: []string{"卡莉法", "Kalifa"}},
		{Canonical: "凯米", Aliases: []string{"凯米", "Camie"}},
		{Canonical: "蕾玖", Aliases: []string{"蕾玖", "Reiju"}},
		{Canonical: "布丁", Aliases: []string{"布丁", "Pudding"}},
	}},
	{Canonical: "龙珠", Variants: []string{"龙珠", "Dragon Ball", "DB", "龙珠Z", "龙珠超"}, Characters: []CharEntry{
		{Canonical: "布尔玛", Aliases: []string{"布尔玛", "Bulma"}},
		{Canonical: "人造人18号", Aliases: []string{"人造人18号", "18号", "Android 18"}},
		{Canonical: "比迪丽", Aliases: []string{"比迪丽", "Videl"}},
		{Canonical: "琪琪", Aliases: []string{"琪琪", "Chi Chi"}},
		{Canonical: "兰琪", Aliases: []string{"兰琪", "Launch"}},
		{Canonical: "小芳", Aliases: []string{"小芳", "Pan"}},
		{Canonical: "开尔弗拉", Aliases: []string{"开尔弗拉", "Caulifla"}},
		{Canonical: "卡莉芙拉", Aliases: []string{"卡莉芙拉", "Kale"}},
		{Canonical: "凯芙拉", Aliases: []string{"凯芙拉", "Kefla"}},
		{Canonical: "托娃", Aliases: []string{"托娃", "Towa"}},
		{Canonical: "人造人21号", Aliases: []string{"人造人21号", "21号", "Android 21"}},
	}},
	{Canonical: "死神", Variants: []string{"死神", "Bleach"}, Characters: []CharEntry{
		{Canonical: "朽木露琪亚", Aliases: []string{"露琪亚", "Rukia"}},
		{Canonical: "井上织姬", Aliases: []string{"织姬", "Orihime"}},
		{Canonical: "四枫院夜一", Aliases: []string{"夜一", "Yoruichi"}},
		{Canonical: "松本乱菊", Aliases: []string{"乱菊", "Rangiku"}},
		{Canonical: "碎蜂", Aliases: []string{"碎蜂", "Soi Fon"}},
		{Canonical: "雏森桃", Aliases: []string{"雏森桃", "Hinamori"}},
		{Canonical: "蒂雅赫丽贝尔", Aliases: []string{"赫丽贝尔", "Halibel", "Tier"}},
		{Canonical: "涅莉艾露", Aliases: []string{"涅莉艾露", "Nel"}},
		{Canonical: "卯之花烈", Aliases: []string{"卯之花", "Unohana"}},
		{Canonical: "伊势七绪", Aliases: []string{"七绪", "Nanao"}},
		{Canonical: "平子真子", Aliases: []string{"平子", "Lisa"}},
		{Canonical: "日世里", Aliases: []string{"日世里", "Hiyori"}},
		{Canonical: "白哉", Aliases: []string{"白哉", "Mashiro"}},
		{Canonical: "志波空鹤", Aliases: []string{"空鹤", "Kukaku"}},
		{Canonical: "黑崎夏梨", Aliases: []string{"夏梨", "Tatsuki"}},
	}},
	{Canonical: "JOJO的奇妙冒险", Variants: []string{"JOJO的奇妙冒险", "JOJO"}, Characters: []CharEntry{
		{Canonical: "徐伦", Aliases: []string{"徐伦", "Jolyne"}},
		{Canonical: "丽莎丽莎", Aliases: []string{"丽莎丽莎", "Lisa Lisa"}},
		{Canonical: "特莉休", Aliases: []string{"特莉休", "Trish"}},
		{Canonical: "康一", Aliases: []string{"康一", "Yukako"}},
		{Canonical: "玛丽亚", Aliases: []string{"玛丽亚", "Mariah"}},
	}},
	{Canonical: "我的英雄学院", Variants: []string{"我的英雄学院", "My Hero Academia", "MHA", "小英雄"}, Characters: []CharEntry{
		{Canonical: "丽日御茶子", Aliases: []string{"丽日", "御茶子", "Uraraka", "茶子"}},
		{Canonical: "蛙吹梅雨", Aliases: []string{"蛙吹", "梅雨", "Tsuyu", "青蛙"}},
		{Canonical: "八百万百", Aliases: []string{"八百万", "百", "Momo", "创造"}},
		{Canonical: "耳郎响香", Aliases: []string{"耳郎", "响香", "Jiro"}},
		{Canonical: "芦户三奈", Aliases: []string{"芦户", "三奈", "Ashido"}},
		{Canonical: "叶隐透", Aliases: []string{"叶隐", "透", "Hagakure"}},
		{Canonical: "渡我身子", Aliases: []string{"渡我", "身子", "Toga", "托加"}},
		{Canonical: "午夜", Aliases: []string{"午夜", "Midnight", "布雷萨米"}},
		{Canonical: "密丽欧", Aliases: []string{"密丽欧", "Mirko", "米尔科"}},
	}},
	{Canonical: "七大罪", Variants: []string{"七大罪", "Seven Deadly Sins"}, Characters: []CharEntry{
		{Canonical: "伊丽莎白", Aliases: []string{"伊丽莎白", "Elizabeth"}},
		{Canonical: "黛安", Aliases: []string{"黛安", "Diane"}},
		{Canonical: "梅林", Aliases: []string{"梅林", "Merlin"}},
		{Canonical: "伊莲恩", Aliases: []string{"伊莲恩", "Elaine"}},
		{Canonical: "吉拉", Aliases: []string{"吉拉", "Guila"}},
		{Canonical: "杰莉科", Aliases: []string{"杰莉科", "Jericho"}},
	}},
	{Canonical: "妖精的尾巴", Variants: []string{"妖精的尾巴", "Fairy Tail"}, Characters: []CharEntry{
		{Canonical: "露西", Aliases: []string{"露西", "Lucy", "露西哈特菲利亚"}},
		{Canonical: "艾尔莎", Aliases: []string{"艾尔莎", "Erza", "艾尔莎舒卡勒托", "Titania"}},
		{Canonical: "朱毕安", Aliases: []string{"朱毕安", "Juvia"}},
		{Canonical: "温蒂", Aliases: []string{"温蒂", "Wendy"}},
		{Canonical: "米拉珍", Aliases: []string{"米拉珍", "Mirajane"}},
		{Canonical: "蕾比", Aliases: []string{"蕾比", "Levy"}},
		{Canonical: "卡娜", Aliases: []string{"卡娜", "Cana"}},
		{Canonical: "梅维斯", Aliases: []string{"梅维斯", "Mavis"}},
		{Canonical: "莉莎娜", Aliases: []string{"莉莎娜", "Lisanna"}},
		{Canonical: "艾芭格琳", Aliases: []string{"艾芭格琳", "Evergreen"}},
	}},
	{Canonical: "一拳超人", Variants: []string{"一拳超人", "One Punch Man", "OPM"}, Characters: []CharEntry{
		{Canonical: "吹雪", Aliases: []string{"吹雪", "Fubuki", "地狱吹雪"}},
		{Canonical: "龙卷", Aliases: []string{"龙卷", "Tatsumaki", "战栗的龙卷"}},
		{Canonical: "蚊女", Aliases: []string{"蚊女", "Mosquito Girl"}},
		{Canonical: "水树", Aliases: []string{"水树", "Mizuki"}},
		{Canonical: "急冻弹", Aliases: []string{"急冻弹", "Do S"}},
		{Canonical: "翠子", Aliases: []string{"翠子", "Suiko"}},
	}},
	{Canonical: "Re Zero", Variants: []string{"Re Zero", "Re从零开始的异世界生活", "Re0"}, Characters: []CharEntry{
		{Canonical: "艾米莉亚", Aliases: []string{"艾米莉亚", "Emilia", "艾米"}},
		{Canonical: "雷姆", Aliases: []string{"雷姆", "Rem"}},
		{Canonical: "拉姆", Aliases: []string{"拉姆", "Ram"}},
		{Canonical: "碧翠丝", Aliases: []string{"碧翠丝", "Beatrice", "贝阿"}},
		{Canonical: "库珥修", Aliases: []string{"库珥修", "Crusch"}},
		{Canonical: "菲鲁特", Aliases: []string{"菲鲁特", "Felt"}},
		{Canonical: "普莉希拉", Aliases: []string{"普莉希拉", "Priscilla"}},
		{Canonical: "安娜塔西亚", Aliases: []string{"安娜塔西亚", "Anastasia"}},
		{Canonical: "芙蕾德莉卡", Aliases: []string{"芙蕾德莉卡", "Frederica"}},
		{Canonical: "佩特拉", Aliases: []string{"佩特拉", "Petra"}},
		{Canonical: "艾姬多娜", Aliases: []string{"艾姬多娜", "Echidna", "魔女"}},
	}},
	{Canonical: "辉夜大小姐", Variants: []string{"辉夜大小姐", "辉夜姬想让人告白"}, Characters: []CharEntry{
		{Canonical: "四宫辉夜", Aliases: []string{"辉夜", "Kaguya", "四宫"}},
		{Canonical: "藤原千花", Aliases: []string{"千花", "Chika", "藤原"}},
		{Canonical: "早坂爱", Aliases: []string{"早坂", "Hayasaka"}},
	}},
	{Canonical: "科学超电磁炮", Variants: []string{"科学超电磁炮", "A Certain Scientific Railgun", "超电磁炮", "御坂"}, Characters: []CharEntry{
		{Canonical: "御坂美琴", Aliases: []string{"御坂美琴", "美琴", "Misaka", "炮姐", "Bilibili"}},
		{Canonical: "白井黑子", Aliases: []string{"白井黑子", "黑子", "Kuroko"}},
		{Canonical: "初春饰利", Aliases: []string{"初春", "Uiharu"}},
		{Canonical: "佐天泪子", Aliases: []string{"佐天", "Saten"}},
	}},
	{Canonical: "魔法禁书目录", Variants: []string{"魔法禁书目录", "A Certain Magical Index", "禁书目录"}, Characters: []CharEntry{
		{Canonical: "御坂美琴", Aliases: []string{"御坂美琴", "美琴", "Misaka"}},
		{Canonical: "茵蒂克丝", Aliases: []string{"茵蒂克丝", "Index"}},
		{Canonical: "白井黑子", Aliases: []string{"白井黑子", "黑子", "Kuroko"}},
	}},
	{Canonical: "王国之心", Variants: []string{"王国之心", "Kingdom Hearts", "KH"}, Characters: []CharEntry{
		{Canonical: "凯莉", Aliases: []string{"凯莉", "Kairi"}},
		{Canonical: "娜米妮", Aliases: []string{"娜米妮", "Namine"}},
		{Canonical: "希恩", Aliases: []string{"希恩", "Xion"}},
		{Canonical: "阿库娅", Aliases: []string{"阿库娅", "Aqua"}},
		{Canonical: "拉尔克努", Aliases: []string{"拉尔克努", "Larxene"}},
	}},
	{Canonical: "勇者斗恶龙", Variants: []string{"勇者斗恶龙", "Dragon Quest", "DQ"}, Characters: []CharEntry{
		{Canonical: "杰西卡", Aliases: []string{"杰西卡", "Jessica"}},
		{Canonical: "比安卡", Aliases: []string{"比安卡", "Bianca"}},
		{Canonical: "芙洛拉", Aliases: []string{"芙洛拉", "Flora"}},
		{Canonical: "阿莉娜", Aliases: []string{"阿莉娜", "Alena"}},
		{Canonical: "玛雅", Aliases: []string{"玛雅", "Maya"}},
		{Canonical: "蜜娜", Aliases: []string{"蜜娜", "Meena"}},
		{Canonical: "黛博拉", Aliases: []string{"黛博拉", "Debora"}},
		{Canonical: "赛蕾娜", Aliases: []string{"赛蕾娜", "Serena"}},
		{Canonical: "维罗妮卡", Aliases: []string{"维罗妮卡", "Veronica"}},
		{Canonical: "玛尔蒂娜", Aliases: []string{"玛尔蒂娜", "Martina"}},
		{Canonical: "洁德", Aliases: []string{"洁德", "Jade"}},
	}},
	{Canonical: "合金装备", Variants: []string{"合金装备", "Metal Gear Solid", "Metal Gear", "MGS"}, Characters: []CharEntry{
		{Canonical: "梅丽尔", Aliases: []string{"梅丽尔", "Meryl"}},
		{Canonical: "狙击狼", Aliases: []string{"狙击狼", "Sniper Wolf"}},
		{Canonical: "艾娃", Aliases: []string{"艾娃", "EVA"}},
		{Canonical: "The Boss", Aliases: []string{"The Boss", "首领"}},
		{Canonical: "静静", Aliases: []string{"静静", "Quiet"}},
		{Canonical: "帕兹", Aliases: []string{"帕兹", "Paz"}},
		{Canonical: "奥尔加", Aliases: []string{"奥尔加", "Olga"}},
		{Canonical: "幸运", Aliases: []string{"幸运", "Fortune"}},
	}},
	{Canonical: "星之海洋", Variants: []string{"星之海洋", "Star Ocean"}, Characters: []CharEntry{
		{Canonical: "蕾娜", Aliases: []string{"蕾娜", "Rena"}},
		{Canonical: "赛琳", Aliases: []string{"赛琳", "Celine"}},
		{Canonical: "普蕾希斯", Aliases: []string{"普蕾希斯", "Precis"}},
		{Canonical: "莉姆露", Aliases: []string{"莉姆露", "Lymle"}},
		{Canonical: "缪莉亚", Aliases: []string{"缪莉亚", "Myuria"}},
		{Canonical: "蕾咪", Aliases: []string{"蕾咪", "Reimi"}},
		{Canonical: "莎拉", Aliases: []string{"莎拉", "Sarah"}},
		{Canonical: "菲欧蕾", Aliases: []string{"菲欧蕾", "Fiore"}},
	}},
	{Canonical: "传说系列", Variants: []string{"传说系列", "Tales of", "TOZ", "TOB", "TOA"}, Characters: []CharEntry{
		{Canonical: "柯蕾特", Aliases: []string{"柯蕾特", "Colette"}},
		{Canonical: "藤林铃", Aliases: []string{"藤林铃", "Sheena"}},
		{Canonical: "莉菲尔", Aliases: []string{"莉菲尔", "Raine"}},
		{Canonical: "普蕾赛亚", Aliases: []string{"普蕾赛亚", "Presea"}},
		{Canonical: "缇亚", Aliases: []string{"缇亚", "Tear"}},
		{Canonical: "娜塔莉亚", Aliases: []string{"娜塔莉亚", "Natalia"}},
		{Canonical: "安妮丝", Aliases: []string{"安妮丝", "Anise"}},
		{Canonical: "茱蒂丝", Aliases: []string{"茱蒂丝", "Judith"}},
		{Canonical: "莉塔", Aliases: []string{"莉塔", "Rita"}},
		{Canonical: "艾丝缇莉洁", Aliases: []string{"艾丝缇莉洁", "Estelle"}},
		{Canonical: "帕蒂", Aliases: []string{"帕蒂", "Patty"}},
		{Canonical: "索菲", Aliases: []string{"索菲", "Sophie"}},
		{Canonical: "雪莉亚", Aliases: []string{"雪莉亚", "Cheria"}},
		{Canonical: "帕斯卡尔", Aliases: []string{"帕斯卡尔", "Pascal"}},
		{Canonical: "米拉", Aliases: []string{"米拉", "Milla"}},
		{Canonical: "蕾雅", Aliases: []string{"蕾雅", "Leia"}},
		{Canonical: "艾莉洁", Aliases: []string{"艾莉洁", "Elize"}},
		{Canonical: "萝丝", Aliases: []string{"萝丝", "Rose"}},
		{Canonical: "艾莉莎", Aliases: []string{"艾莉莎", "Alisha"}},
		{Canonical: "莱拉", Aliases: []string{"莱拉", "Lailah"}},
		{Canonical: "艾德娜", Aliases: []string{"艾德娜", "Edna"}},
		{Canonical: "玛吉露", Aliases: []string{"玛吉露", "Magilou"}},
		{Canonical: "薇尔贝特", Aliases: []string{"薇尔贝特", "Velvet"}},
		{Canonical: "艾蕾诺亚", Aliases: []string{"艾蕾诺亚", "Eleanor"}},
		{Canonical: "琳薇儿", Aliases: []string{"琳薇儿", "Rinwell"}},
		{Canonical: "希侬", Aliases: []string{"希侬", "Shionne"}},
		{Canonical: "奇莎拉", Aliases: []string{"奇莎拉", "Kisara"}},
	}},
	{Canonical: "Fortnite", Variants: []string{"Fortnite", "堡垒之夜"}, Characters: []CharEntry{
		{Canonical: "暗影", Aliases: []string{"暗影", "Shadow"}},
		{Canonical: "中野", Aliases: []string{"中野", "Raven"}},
		{Canonical: "艾思梅", Aliases: []string{"艾思梅"}},
	}},
	{Canonical: "PUBG", Variants: []string{"PUBG", "绝地求生"}},
	{Canonical: "CS2", Variants: []string{"CS2", "CSGO", "反恐精英", "Counter Strike"}},
	{Canonical: "星际战甲", Variants: []string{"星际战甲", "Warframe"}, Characters: []CharEntry{
		{Canonical: "女武神", Aliases: []string{"女武神", "Valkyr"}},
		{Canonical: "赛娃", Aliases: []string{"赛娃", "Saryn"}},
		{Canonical: "小精灵", Aliases: []string{"小精灵", "Wisp"}},
		{Canonical: "夜灵", Aliases: []string{"夜灵", "Garuda"}},
		{Canonical: "弥桑", Aliases: []string{"弥桑", "Mesa"}},
		{Canonical: "魅影", Aliases: []string{"魅影", "Revenant"}},
		{Canonical: "翠玉", Aliases: []string{"翠玉", "Jade"}},
	}},
	{Canonical: "命运", Variants: []string{"命运2", "命运", "Destiny 2", "Destiny"}, Characters: []CharEntry{
		{Canonical: "玛拉", Aliases: []string{"玛拉", "Mara Sov"}},
		{Canonical: "艾可拉", Aliases: []string{"艾可拉", "Ikora"}},
		{Canonical: "阿曼达", Aliases: []string{"阿曼达", "Amanda"}},
		{Canonical: "艾瑞丝", Aliases: []string{"艾瑞丝", "Eris"}},
	}},
	{Canonical: "光环", Variants: []string{"光环", "Halo"}, Characters: []CharEntry{
		{Canonical: "科塔娜", Aliases: []string{"科塔娜", "Cortana"}},
	}},
	{Canonical: "看门狗", Variants: []string{"看门狗", "Watch Dogs"}, Characters: []CharEntry{
		{Canonical: "克拉拉", Aliases: []string{"克拉拉", "Clara"}},
		{Canonical: "西塔拉", Aliases: []string{"西塔拉", "Sitara"}},
	}},
	{Canonical: "如龙", Variants: []string{"如龙8", "如龙7", "如龙0", "如龙", "Yakuza 8", "Yakuza 7", "Yakuza 0", "Yakuza", "人中之龙8", "人中之龙7", "人中之龙0", "人中之龙", "如龙8无尽财富", "Like a Dragon"}, Characters: []CharEntry{
		{Canonical: "向田纱荣子", Aliases: []string{"向田纱荣子", "纱荣子", "Saeko"}},
		{Canonical: "狭山薰", Aliases: []string{"狭山薰", "Kaoru"}},
		{Canonical: "泽村遥", Aliases: []string{"泽村遥", "Haruka"}},
	}},
	{Canonical: "仙剑奇侠传", Variants: []string{"仙剑奇侠传", "仙剑"}, Characters: []CharEntry{
		{Canonical: "赵灵儿", Aliases: []string{"赵灵儿", "灵儿"}},
		{Canonical: "林月如", Aliases: []string{"林月如", "月如"}},
		{Canonical: "阿奴", Aliases: []string{"阿奴", "Anu"}},
		{Canonical: "唐雪见", Aliases: []string{"唐雪见", "雪见"}},
		{Canonical: "龙葵", Aliases: []string{"龙葵"}},
		{Canonical: "紫萱", Aliases: []string{"紫萱"}},
		{Canonical: "柳梦璃", Aliases: []string{"柳梦璃", "梦璃"}},
		{Canonical: "韩菱纱", Aliases: []string{"韩菱纱", "菱纱"}},
		{Canonical: "越祈", Aliases: []string{"越祈"}},
	}},
	{Canonical: "古剑奇谭", Variants: []string{"古剑奇谭", "古剑"}, Characters: []CharEntry{
		{Canonical: "风晴雪", Aliases: []string{"风晴雪", "晴雪"}},
		{Canonical: "襄铃", Aliases: []string{"襄铃"}},
		{Canonical: "闻人羽", Aliases: []string{"闻人羽"}},
		{Canonical: "乐无异", Aliases: []string{"乐无异"}},
		{Canonical: "北洛", Aliases: []string{"北洛"}},
	}},
	{Canonical: "逆水寒", Variants: []string{"逆水寒"}, Characters: []CharEntry{
		{Canonical: "苏梦枕", Aliases: []string{"苏梦枕"}},
		{Canonical: "温柔", Aliases: []string{"温柔"}},
	}},
	{Canonical: "剑网3", Variants: []string{"剑网3", "剑网 3", "剑侠情缘3"}, Characters: []CharEntry{
		{Canonical: "洛风", Aliases: []string{"洛风"}},
		{Canonical: "叶芷青", Aliases: []string{"叶芷青"}},
		{Canonical: "李复", Aliases: []string{"李复"}},
	}},
	{Canonical: "黑神话 悟空", Variants: []string{"黑神话 悟空", "黑神话悟空", "Black Myth Wukong"}, Characters: []CharEntry{
		{Canonical: "四妹", Aliases: []string{"四妹"}},
		{Canonical: "萍萍", Aliases: []string{"萍萍"}},
		{Canonical: "铁扇公主", Aliases: []string{"铁扇公主"}},
		{Canonical: "蜘蛛精", Aliases: []string{"蜘蛛精"}},
	}},
	{Canonical: "饿狼传说", Variants: []string{"饿狼传说", "Fatal Fury", "Garou", "饿狼传说群狼之证", "Garou Mark of the Wolves"}, Characters: []CharEntry{
		{Canonical: "不知火舞", Aliases: []string{"不知火舞", "Mai Shiranui", "舞", "Mai"}},
		{Canonical: "布鲁玛丽", Aliases: []string{"布鲁玛丽", "Blue Mary", "玛丽"}},
		{Canonical: "李香绯", Aliases: []string{"李香绯", "Li Xiangfei"}},
		{Canonical: "邦妮", Aliases: []string{"邦妮", "Bonne Jenet", "Jenet"}},
	}},
	{Canonical: "葬送的芙莉莲", Variants: []string{"葬送的芙莉莲", "芙莉莲", "Frieren", "Sousou no Frieren"}, Characters: []CharEntry{
		{Canonical: "芙莉莲", Aliases: []string{"芙莉莲", "Frieren"}},
		{Canonical: "菲伦", Aliases: []string{"菲伦", "Fern"}},
		{Canonical: "修塔尔克", Aliases: []string{"修塔尔克", "Stark"}},
		{Canonical: "古拉欧萨", Aliases: []string{"古拉欧萨", "Lügner"}},
		{Canonical: "莉涅尔", Aliases: []string{"莉涅尔", "Liene"}},
		{Canonical: "拉奥芬", Aliases: []string{"拉奥芬", "Lawine"}},
		{Canonical: "克蕾芙", Aliases: []string{"克蕾芙", "Kraft"}},
	}},
	{Canonical: "第一后裔", Variants: []string{"第一后裔", "The First Descendant", "第一后裔 邦尼"}, Characters: []CharEntry{
		{Canonical: "邦妮", Aliases: []string{"邦妮", "Bunny", "邦尼"}},
		{Canonical: "维艾莎", Aliases: []string{"维艾莎", "Viessa"}},
		{Canonical: "雷普西", Aliases: []string{"雷普西", "Lepic"}},
		{Canonical: "弗蕾娜", Aliases: []string{"弗蕾娜", "Freyna"}},
		{Canonical: "布莱尔", Aliases: []string{"布莱尔", "Blair"}},
		{Canonical: "沙迪克", Aliases: []string{"沙迪克", "Sharen"}},
		{Canonical: "露娜", Aliases: []string{"露娜", "Luna"}},
		{Canonical: "席莲", Aliases: []string{"席莲", "Sienne"}},
		{Canonical: "瓦尔比", Aliases: []string{"瓦尔比", "Valby"}},
		{Canonical: "耶娜", Aliases: []string{"耶娜", "Yujin"}},
	}},
	{Canonical: "最后的生还者", Variants: []string{"最后的生还者", "美国末日", "The Last of Us", "TLOU", "The Last of Us Part 1", "The Last of Us Part 2", "最后生还者"}, Characters: []CharEntry{
		{Canonical: "艾莉", Aliases: []string{"艾莉", "Ellie"}},
		{Canonical: "泰丝", Aliases: []string{"泰丝", "Tess"}},
		{Canonical: "迪娜", Aliases: []string{"迪娜", "Dina"}},
		{Canonical: "艾比", Aliases: []string{"艾比", "Abby"}},
		{Canonical: "莱莉", Aliases: []string{"莱莉", "Riley"}},
		{Canonical: "玛琳", Aliases: []string{"玛琳", "Marlene"}},
	}},
	{Canonical: "无限暖暖", Variants: []string{"无限暖暖", "Infinity Nikki", "暖暖", "奇迹暖暖", "闪耀暖暖"}, Characters: []CharEntry{
		{Canonical: "暖暖", Aliases: []string{"暖暖", "Nikki"}},
	}},
	{Canonical: "漫威争锋", Variants: []string{"漫威争锋", "Marvel Rivals"}, Characters: []CharEntry{
		{Canonical: "黑寡妇", Aliases: []string{"黑寡妇", "Black Widow", "娜塔莎"}},
		{Canonical: "猩红女巫", Aliases: []string{"猩红女巫", "绯红女巫", "Scarlet Witch", "旺达", "Wanda"}},
		{Canonical: "魔卡娜", Aliases: []string{"魔卡娜", "Magik", "伊利亚娜"}},
		{Canonical: "灵蝶", Aliases: []string{"灵蝶", "Psylocke", "蝶"}},
		{Canonical: "隐形女", Aliases: []string{"隐形女", "Invisible Woman", "苏珊"}},
		{Canonical: "松鼠女", Aliases: []string{"松鼠女", "Squirrel Girl"}},
		{Canonical: "暴风女", Aliases: []string{"暴风女", "Storm"}},
		{Canonical: "琴格雷", Aliases: []string{"琴格雷", "Jean Grey", "琴", "凤凰女"}},
		{Canonical: "海拉", Aliases: []string{"海拉", "Hela"}},
		{Canonical: "魔形女", Aliases: []string{"魔形女", "Mystique"}},
	}},
	{Canonical: "名侦探柯南", Variants: []string{"名侦探柯南", "柯南", "Detective Conan", "Case Closed"}, Characters: []CharEntry{
		{Canonical: "毛利兰", Aliases: []string{"毛利兰", "小兰", "兰", "Ran", "Ran Mouri"}},
		{Canonical: "灰原哀", Aliases: []string{"灰原哀", "小哀", "哀", "Haibara", "Ai Haibara", "宫野志保", "雪莉"}},
		{Canonical: "铃木园子", Aliases: []string{"铃木园子", "园子", "Sonoko"}},
		{Canonical: "远山和叶", Aliases: []string{"远山和叶", "和叶", "Kazuha"}},
		{Canonical: "工藤有希子", Aliases: []string{"工藤有希子", "有希子", "Yukiko"}},
		{Canonical: "贝尔摩德", Aliases: []string{"贝尔摩德", "苦艾酒", "Vermouth", "莎朗温亚德"}},
		{Canonical: "水无怜奈", Aliases: []string{"水无怜奈", "基尔", "Kir", "Mizunashi Rena"}},
		{Canonical: "世良真纯", Aliases: []string{"世良真纯", "真纯", "Sera", "Mary"}},
	}},
	{Canonical: "银魂", Variants: []string{"银魂", "Gintama", "银之魂"}, Characters: []CharEntry{
		{Canonical: "神乐", Aliases: []string{"神乐", "Kagura", "夜兔神乐"}},
		{Canonical: "志村妙", Aliases: []string{"志村妙", "阿妙", "Tae", "Otae"}},
		{Canonical: "猿飞菖蒲", Aliases: []string{"猿飞菖蒲", "菖蒲", "Sacchan", "Saigou"}},
		{Canonical: "月咏", Aliases: []string{"月咏", "Tsukuyo"}},
		{Canonical: "柳生九兵卫", Aliases: []string{"柳生九兵卫", "九兵卫", "Kyubei"}},
	}},
	{Canonical: "犬夜叉", Variants: []string{"犬夜叉", "Inuyasha"}, Characters: []CharEntry{
		{Canonical: "日暮戈薇", Aliases: []string{"日暮戈薇", "戈薇", "Kagome"}},
		{Canonical: "桔梗", Aliases: []string{"桔梗", "Kikyo", "Kikyou"}},
		{Canonical: "珊瑚", Aliases: []string{"珊瑚", "Sango"}},
	}},
	{Canonical: "美少女战士", Variants: []string{"美少女战士", "Sailor Moon", "美战"}, Characters: []CharEntry{
		{Canonical: "月野兔", Aliases: []string{"月野兔", "水手月亮", "Sailor Moon", "Usagi", "小兔"}},
		{Canonical: "水野亚美", Aliases: []string{"水野亚美", "水手水星", "Sailor Mercury", "Ami"}},
		{Canonical: "火野丽", Aliases: []string{"火野丽", "水手火星", "Sailor Mars", "Rei"}},
		{Canonical: "木野真琴", Aliases: []string{"木野真琴", "水手木星", "Sailor Jupiter", "Makoto"}},
		{Canonical: "爱野美奈子", Aliases: []string{"爱野美奈子", "水手金星", "Sailor Venus", "Minako"}},
	}},
	{Canonical: "钢之炼金术师", Variants: []string{"钢之炼金术师", "钢炼", "Fullmetal Alchemist", "FMA"}, Characters: []CharEntry{
		{Canonical: "温莉", Aliases: []string{"温莉", "Winry", "温莉洛克贝尔"}},
		{Canonical: "莉莎", Aliases: []string{"莉莎", "Riza", "莉莎霍克艾", "霍克艾"}},
		{Canonical: "兰芳", Aliases: []string{"兰芳", "Lan Fan"}},
		{Canonical: "罗莎", Aliases: []string{"罗莎", "Rosé"}},
	}},
	{Canonical: "东京喰种", Variants: []string{"东京喰种", "东京食尸鬼", "Tokyo Ghoul"}, Characters: []CharEntry{
		{Canonical: "雾嶋董香", Aliases: []string{"雾嶋董香", "董香", "Touka"}},
		{Canonical: "神代利世", Aliases: []string{"神代利世", "利世", "Rize"}},
		{Canonical: "芳村艾特", Aliases: []string{"芳村艾特", "艾特", "Eto", "独眼枭"}},
	}},
	{Canonical: "排球少年", Variants: []string{"排球少年", "Haikyuu", "排球"}, Characters: []CharEntry{
		{Canonical: "清水洁子", Aliases: []string{"清水洁子", "洁子", "Kiyoko"}},
		{Canonical: "谷地仁花", Aliases: []string{"谷地仁花", "仁花", "Yachi", "谷地"}},
	}},
	{Canonical: "猫娘乐园", Variants: []string{"猫娘乐园", "Nekopara"}, Characters: []CharEntry{
		{Canonical: "巧克力", Aliases: []string{"巧克力", "Chocola"}},
		{Canonical: "香草", Aliases: []string{"香草", "Vanilla"}},
		{Canonical: "肉桂", Aliases: []string{"肉桂", "Cinnamon"}},
		{Canonical: "枫糖", Aliases: []string{"枫糖", "Maple"}},
		{Canonical: "椰子", Aliases: []string{"椰子", "Coconut"}},
	}},
	{Canonical: "虚拟主播", Variants: []string{"虚拟主播", "VTuber", "ホロライブ", "Hololive"}, Characters: []CharEntry{
		{Canonical: "宝钟玛琳", Aliases: []string{"宝钟玛琳", "Marine", "船长"}},
		{Canonical: "Fuwawa", Aliases: []string{"Fuwawa", "fuwawa"}},
		{Canonical: "Mococo", Aliases: []string{"Mococo", "mococo"}},
	}},
	{Canonical: "我独自升级", Variants: []string{"我独自升级", "Solo Leveling"}, Characters: []CharEntry{
		{Canonical: "成珍雅", Aliases: []string{"成珍雅", "Cha Hae-In"}},
	}},
	{Canonical: "黑暗之魂3", Variants: []string{"黑暗之魂3", "Dark Souls 3", "黑魂3"}, Characters: []CharEntry{
		{Canonical: "防火女", Aliases: []string{"防火女", "Fire Keeper"}},
	}},
	{Canonical: "明日方舟 终末地", Variants: []string{"明日方舟 终末地", "Arknights Endfield"}, Characters: []CharEntry{
		{Canonical: "伊冯", Aliases: []string{"伊冯"}},
	}},
	{Canonical: "斗罗大陆", Variants: []string{"斗罗大陆"}, Characters: []CharEntry{
		{Canonical: "王冬儿", Aliases: []string{"王冬儿", "霍雨浩"}},
	}},
	{Canonical: "原创角色", Variants: []string{"原创角色", "OC", "Original Character"}, Characters: []CharEntry{
		{Canonical: "Primrose", Aliases: []string{"Primrose", "普丽姆罗丝"}},
	}},
}
