// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"
	"database/sql"
)

const getAsset = `-- name: GetAsset :one
SELECT asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at FROM assets WHERE asset_id = ?
`

func (q *Queries) GetAsset(ctx context.Context, assetID string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, assetID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.LibraryID,
		&i.RelPath,
		&i.FileName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Mtime,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByPath = `-- name: GetAssetByPath :one

SELECT asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at FROM assets WHERE library_id = ? AND rel_path = ?
`

type GetAssetByPathParams struct {
	LibraryID string
	RelPath   string
}

// GetAssetByPath: used by the scanner's move-merge heuristic
// (old path gone + new path seen + size/mtime match -> keep identity,
// update path attribute; see adr/0004).
func (q *Queries) GetAssetByPath(ctx context.Context, arg GetAssetByPathParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByPath, arg.LibraryID, arg.RelPath)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.LibraryID,
		&i.RelPath,
		&i.FileName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Mtime,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetsAfterCursor = `-- name: ListAssetsAfterCursor :many
SELECT asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at FROM assets
WHERE created_at < ? OR (created_at = ? AND asset_id < ?)
ORDER BY created_at DESC, asset_id DESC
LIMIT ?
`

type ListAssetsAfterCursorParams struct {
	CreatedAt   string
	CreatedAt_2 string
	AssetID     string
	Limit       int64
}

func (q *Queries) ListAssetsAfterCursor(ctx context.Context, arg ListAssetsAfterCursorParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsAfterCursor,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.AssetID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsFirstPage = `-- name: ListAssetsFirstPage :many

SELECT asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at FROM assets
ORDER BY created_at DESC, asset_id DESC
LIMIT ?
`

// ListAssetsFirstPage / ListAssetsAfterCursor: keyset pagination.
// Composite order (created_at DESC, asset_id DESC): created_at alone is
// not unique (batch scans share the same millisecond), so pagination
// would lose/duplicate rows; asset_id is the deterministic tiebreaker.
// Cursor = (created_at, asset_id) of the last row of the previous page;
// the WHERE clause is the strict expansion of the row-value comparison
// (created_at, asset_id) < (?, ?). OFFSET is never used: deep OFFSET is
// O(n) on NAS disks, cursor seek is O(log n).
func (q *Queries) ListAssetsFirstPage(ctx context.Context, limit int64) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAsset = `-- name: UpsertAsset :one


INSERT INTO assets (
    asset_id, library_id, rel_path, file_name, media_type,
    size_bytes, mtime, duration_ms, width, height, source,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (library_id, rel_path) DO UPDATE SET
    file_name    = excluded.file_name,
    media_type   = excluded.media_type,
    size_bytes   = excluded.size_bytes,
    mtime        = excluded.mtime,
    duration_ms  = excluded.duration_ms,
    width        = excluded.width,
    height       = excluded.height,
    source       = excluded.source,
    updated_at   = excluded.updated_at
RETURNING asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at
`

type UpsertAssetParams struct {
	AssetID    string
	LibraryID  string
	RelPath    string
	FileName   string
	MediaType  string
	SizeBytes  int64
	Mtime      string
	DurationMs sql.NullInt64
	Width      sql.NullInt64
	Height     sql.NullInt64
	Source     sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

// assets queries (M1 minimal set: scanner ingestion + list pagination).
//
// NOTE (why English comments here): sqlc v1.31.1's SQLite parser has a
// column-accounting bug with multi-byte (Chinese) comment text -- parse
// failures trigger non-deterministically depending on comment length.
// Chinese explanations live in migrations/0001_init.up.sql and
// docs/adr/0004; keep comments in this directory ASCII-only.
// UpsertAsset: the single ingestion entry point (adr/0004 identity).
// Conflict target is the PATH (library_id, rel_path); on conflict only
// metadata attributes are refreshed. asset_id / created_at keep their
// first-seen values (identity is for life; ingest time frozen for the
// freshness scoring). Change detection (size+mtime) is the scanner's
// job before calling this.
func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, upsertAsset,
		arg.AssetID,
		arg.LibraryID,
		arg.RelPath,
		arg.FileName,
		arg.MediaType,
		arg.SizeBytes,
		arg.Mtime,
		arg.DurationMs,
		arg.Width,
		arg.Height,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.LibraryID,
		&i.RelPath,
		&i.FileName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Mtime,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
