// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authors.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addAssetAuthor = `-- name: AddAssetAuthor :exec
INSERT INTO asset_authors (asset_id, author_id)
VALUES (?, ?)
ON CONFLICT (asset_id, author_id) DO NOTHING
`

type AddAssetAuthorParams struct {
	AssetID  string
	AuthorID string
}

// Idempotent many-to-many link (PK asset_id+author_id in 0001). Used by
// the TXT unified rebuild and by COS scanning (author -> files mapping
// recorded at scan time, GUIDE_AUTHOR).
func (q *Queries) AddAssetAuthor(ctx context.Context, arg AddAssetAuthorParams) error {
	_, err := q.db.ExecContext(ctx, addAssetAuthor, arg.AssetID, arg.AuthorID)
	return err
}

const addAssetCharacter = `-- name: AddAssetCharacter :exec
INSERT INTO asset_characters (asset_id, character_name)
VALUES (?, ?)
ON CONFLICT (asset_id, character_name) DO NOTHING
`

type AddAssetCharacterParams struct {
	AssetID       string
	CharacterName string
}

// One row per matched character canonical name (multi-character assets
// get multiple rows; PK asset_id+character_name dedupes).
func (q *Queries) AddAssetCharacter(ctx context.Context, arg AddAssetCharacterParams) error {
	_, err := q.db.ExecContext(ctx, addAssetCharacter, arg.AssetID, arg.CharacterName)
	return err
}

const deleteAssetAuthorsByAssetID = `-- name: DeleteAssetAuthorsByAssetID :exec
DELETE FROM asset_authors WHERE asset_id = ?
`

// Single-asset link removal (EnrichAsset COS branch recompute:
// delete-then-insert, same overwrite semantics as asset_characters).
func (q *Queries) DeleteAssetAuthorsByAssetID(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetAuthorsByAssetID, assetID)
	return err
}

const deleteAssetAuthorsByAuthorIds = `-- name: DeleteAssetAuthorsByAuthorIds :exec
DELETE FROM asset_authors
WHERE author_id IN (/*SLICE:author_ids*/?)
`

// Unified rebuild step 1: drop every existing link of all authors that
// appear in any imported TXT source, then the caller re-inserts the
// fully merged set (cross-TXT union semantics: no single TXT may
// overwrite another TXT's links; old-project
// rebuildAssociationsFromBlocks behavior).
func (q *Queries) DeleteAssetAuthorsByAuthorIds(ctx context.Context, authorIds []string) error {
	query := deleteAssetAuthorsByAuthorIds
	var queryParams []interface{}
	if len(authorIds) > 0 {
		for _, v := range authorIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:author_ids*/?", strings.Repeat(",?", len(authorIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:author_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteAssetCharacters = `-- name: DeleteAssetCharacters :exec
DELETE FROM asset_characters WHERE asset_id = ?
`

// Character rows are scanner-recomputed output: delete-then-insert on
// every (re)ingest = upsert-with-overwrite semantics. Rename/ moves that
// change mtime re-ingest through UpsertAsset (whose DO UPDATE already
// overwrites the source column via excluded.source) followed by this
// delete+insert, so both enrichment columns are recomputed from the new
// file name.
func (q *Queries) DeleteAssetCharacters(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetCharacters, assetID)
	return err
}

const deleteOrphanCosAuthors = `-- name: DeleteOrphanCosAuthors :execrows
DELETE FROM authors
WHERE type = 'cos'
  AND NOT EXISTS (SELECT 1 FROM asset_authors aa WHERE aa.author_id = authors.id)
`

// Post-scan garbage collection: COS authors arise from scanned directory
// structure; once every file of an author directory is gone (rename/delete
// at the filesystem level), the author row has zero links and must be
// removed (old-project deleteOrphanCosAuthors semantics; the authors.type
// CHECK on 'cos' is more reliable than a LIKE 'cos\\_%' prefix).
func (q *Queries) DeleteOrphanCosAuthors(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanCosAuthors)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAssetsForEnrichmentByLibrary = `-- name: ListAssetsForEnrichmentByLibrary :many
SELECT asset_id, file_name, rel_path FROM assets WHERE library_id = ?
`

type ListAssetsForEnrichmentByLibraryRow struct {
	AssetID  string
	FileName string
	RelPath  string
}

// Full-library asset rows for explicit recomputation (custom_sources
// change: already-ingested assets are skipped by a rescan because
// size+mtime match, so enrichment must be recomputed on the write path).
func (q *Queries) ListAssetsForEnrichmentByLibrary(ctx context.Context, libraryID string) ([]ListAssetsForEnrichmentByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsForEnrichmentByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsForEnrichmentByLibraryRow
	for rows.Next() {
		var i ListAssetsForEnrichmentByLibraryRow
		if err := rows.Scan(&i.AssetID, &i.FileName, &i.RelPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorNamesForAssets = `-- name: ListAuthorNamesForAssets :many
SELECT aa.asset_id, au.display_name
FROM asset_authors aa JOIN authors au ON au.id = aa.author_id
WHERE aa.asset_id IN (SELECT value FROM json_each(?1))
ORDER BY aa.asset_id, au.display_name
`

type ListAuthorNamesForAssetsRow struct {
	AssetID     string
	DisplayName string
}

// Batch author-name lookup for list endpoints (AssetSummary.authorNames):
// every author (regular + COS, no type filter) of the given assets, one
// row per (asset_id, author) pair. asset_ids_json is a JSON array
// consumed by json_each -- same parameter shape as the browse filter
// params (see browse.sql header for the sqlc parser constraints that
// dictate it). Names sort by display_name, same convention as the
// detail-side ListAssetAuthorRefs.
func (q *Queries) ListAuthorNamesForAssets(ctx context.Context, assetIdsJson interface{}) ([]ListAuthorNamesForAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorNamesForAssets, assetIdsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorNamesForAssetsRow
	for rows.Next() {
		var i ListAuthorNamesForAssetsRow
		if err := rows.Scan(&i.AssetID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthors = `-- name: ListAuthors :many

SELECT au.id, au.display_name, au.type, au.followed,
       COUNT(aa.asset_id) AS file_count,
       COALESCE(SUM(CASE WHEN aa.asset_id IS NULL THEN 0 ELSE
           (SELECT COUNT(*) FROM view_events ve
            WHERE ve.asset_id = aa.asset_id AND ve.kind = 'open') END), 0) AS view_count
FROM authors au
LEFT JOIN asset_authors aa ON aa.author_id = au.id
GROUP BY au.id
ORDER BY au.display_name
`

type ListAuthorsRow struct {
	ID          string
	DisplayName string
	Type        string
	Followed    int64
	FileCount   int64
	ViewCount   interface{}
}

// authors.sql: business-side author queries (M3 author system,
// DOMAIN_RULES 6). The one-shot legacy import channel owns the Import*
// prefixed queries in legacy_import.sql; every query here is deliberately
// named outside that namespace (sqlc would collide otherwise).
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug) and migrations/0001_init.up.sql for
// Chinese explanations of the schema.
//
// NOTE: the asset_characters write queries live in this file too (not
// assets.sql) because this task's change scope names authors.sql as the
// only new query file; they are the scanner-side output of the source
// matching engine and read back via browse.sql ListAssetCharacterNames.
// GET /authors: every author (regular + COS unified, DOMAIN_RULES 6)
// with its linked-asset count, cumulative view count and follow flag.
// Sort = display_name ascending, same convention as GET /tags
// (ListTags ORDER BY t.name, DOMAIN_RULES 7 name ordering).
// view_count = author's works' total kind='open' events (one scalar
// subquery per linked row; aa.asset_id NULL rows contribute 0, so the
// SUM never yields NULL; COALESCE keeps the aggregate defensive).
func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Type,
			&i.Followed,
			&i.FileCount,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNormalAssetsForAuthorMatch = `-- name: ListNormalAssetsForAuthorMatch :many
SELECT a.asset_id, a.file_name
FROM assets a
JOIN libraries l ON l.id = a.library_id
WHERE l.kind = 'normal'
`

type ListNormalAssetsForAuthorMatchRow struct {
	AssetID  string
	FileName string
}

// The TXT work-name matching domain: all assets of normal libraries.
// COS assets are excluded by the DOMAIN_RULES 6 isolation rule (regular
// authors only ever match non-COS files).
func (q *Queries) ListNormalAssetsForAuthorMatch(ctx context.Context) ([]ListNormalAssetsForAuthorMatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listNormalAssetsForAuthorMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNormalAssetsForAuthorMatchRow
	for rows.Next() {
		var i ListNormalAssetsForAuthorMatchRow
		if err := rows.Scan(&i.AssetID, &i.FileName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAuthorFollow = `-- name: SetAuthorFollow :execrows
UPDATE authors SET followed = ? WHERE id = ?
`

type SetAuthorFollowParams struct {
	Followed int64
	ID       string
}

// Follow is an author-level boolean (DOMAIN_RULES 5/6: no counter,
// unsetting just clears it). 0 rows affected = unknown authorId; the
// caller maps that to 404.
func (q *Queries) SetAuthorFollow(ctx context.Context, arg SetAuthorFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAuthorFollow, arg.Followed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetCosWork = `-- name: UpdateAssetCosWork :exec
UPDATE assets SET cos_work = ?, updated_at = ? WHERE asset_id = ?
`

type UpdateAssetCosWorkParams struct {
	CosWork   sql.NullString
	UpdatedAt string
	AssetID   string
}

// Single-asset COS work refresh (migration 0008). recomputeCosAuthor calls
// it on every path that changes rel_path without re-ingesting (API
// move/rename via EnrichAsset, scan move-merge): the work is derived from
// rel_path, so it must be recomputed together with the author links.
// NULL work = file sits directly under the author directory (old-app
// "other" bucket, DOMAIN_RULES 6) -- the refresh is overwrite-in-full,
// including the NULL case, so a file moved out of a work directory
// unlinks from it.
func (q *Queries) UpdateAssetCosWork(ctx context.Context, arg UpdateAssetCosWorkParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetCosWork, arg.CosWork, arg.UpdatedAt, arg.AssetID)
	return err
}

const updateAssetSource = `-- name: UpdateAssetSource :exec
UPDATE assets SET source = ?, updated_at = ? WHERE asset_id = ?
`

type UpdateAssetSourceParams struct {
	Source    sql.NullString
	UpdatedAt string
	AssetID   string
}

// Single-asset source refresh (EnrichAsset after API move/rename:
// the file name changes but size+mtime do not, so no re-ingest would
// happen; the write path must recompute explicitly).
func (q *Queries) UpdateAssetSource(ctx context.Context, arg UpdateAssetSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetSource, arg.Source, arg.UpdatedAt, arg.AssetID)
	return err
}

const upsertAuthor = `-- name: UpsertAuthor :exec
INSERT INTO authors (id, display_name, type, followed, created_at)
VALUES (?, ?, ?, 0, ?)
ON CONFLICT (id) DO UPDATE SET
    display_name = excluded.display_name
`

type UpsertAuthorParams struct {
	ID          string
	DisplayName string
	Type        string
	CreatedAt   string
}

// TXT import / COS scan author upsert keyed by the authoring-generated
// id (GenerateAuthorID / GenerateCosAuthorID). Re-import never
// duplicates authors; display_name tracks the (re)imported value. id is
// the identity, so the ON CONFLICT branch must not touch followed
// (re-importing a TXT must not reset the follow flag) nor created_at
// (cold-start freshness, same rule as UpsertAsset).
func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthor,
		arg.ID,
		arg.DisplayName,
		arg.Type,
		arg.CreatedAt,
	)
	return err
}
