// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authors.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addAssetAuthor = `-- name: AddAssetAuthor :exec
INSERT INTO asset_authors (asset_id, author_id)
VALUES (?, ?)
ON CONFLICT (asset_id, author_id) DO NOTHING
`

type AddAssetAuthorParams struct {
	AssetID  string
	AuthorID string
}

// Idempotent many-to-many link (PK asset_id+author_id in 0001). Used by
// the TXT unified rebuild and by COS scanning (author -> files mapping
// recorded at scan time, GUIDE_AUTHOR).
func (q *Queries) AddAssetAuthor(ctx context.Context, arg AddAssetAuthorParams) error {
	_, err := q.db.ExecContext(ctx, addAssetAuthor, arg.AssetID, arg.AuthorID)
	return err
}

const addAssetCharacter = `-- name: AddAssetCharacter :exec
INSERT INTO asset_characters (asset_id, character_name)
VALUES (?, ?)
ON CONFLICT (asset_id, character_name) DO NOTHING
`

type AddAssetCharacterParams struct {
	AssetID       string
	CharacterName string
}

// One row per matched character canonical name (multi-character assets
// get multiple rows; PK asset_id+character_name dedupes).
func (q *Queries) AddAssetCharacter(ctx context.Context, arg AddAssetCharacterParams) error {
	_, err := q.db.ExecContext(ctx, addAssetCharacter, arg.AssetID, arg.CharacterName)
	return err
}

const deleteAssetAuthorsByAuthorIds = `-- name: DeleteAssetAuthorsByAuthorIds :exec
DELETE FROM asset_authors
WHERE author_id IN (/*SLICE:author_ids*/?)
`

// Unified rebuild step 1: drop every existing link of all authors that
// appear in any imported TXT source, then the caller re-inserts the
// fully merged set (cross-TXT union semantics: no single TXT may
// overwrite another TXT's links; old-project
// rebuildAssociationsFromBlocks behavior).
func (q *Queries) DeleteAssetAuthorsByAuthorIds(ctx context.Context, authorIds []string) error {
	query := deleteAssetAuthorsByAuthorIds
	var queryParams []interface{}
	if len(authorIds) > 0 {
		for _, v := range authorIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:author_ids*/?", strings.Repeat(",?", len(authorIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:author_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteAssetCharacters = `-- name: DeleteAssetCharacters :exec
DELETE FROM asset_characters WHERE asset_id = ?
`

// Character rows are scanner-recomputed output: delete-then-insert on
// every (re)ingest = upsert-with-overwrite semantics. Rename/ moves that
// change mtime re-ingest through UpsertAsset (whose DO UPDATE already
// overwrites the source column via excluded.source) followed by this
// delete+insert, so both enrichment columns are recomputed from the new
// file name.
func (q *Queries) DeleteAssetCharacters(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetCharacters, assetID)
	return err
}

const listAuthors = `-- name: ListAuthors :many

SELECT au.id, au.display_name, au.type, au.followed,
       COUNT(aa.asset_id) AS file_count
FROM authors au
LEFT JOIN asset_authors aa ON aa.author_id = au.id
GROUP BY au.id
ORDER BY au.display_name
`

type ListAuthorsRow struct {
	ID          string
	DisplayName string
	Type        string
	Followed    int64
	FileCount   int64
}

// authors.sql: business-side author queries (M3 author system,
// DOMAIN_RULES 6). The one-shot legacy import channel owns the Import*
// prefixed queries in legacy_import.sql; every query here is deliberately
// named outside that namespace (sqlc would collide otherwise).
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug) and migrations/0001_init.up.sql for
// Chinese explanations of the schema.
//
// NOTE: the asset_characters write queries live in this file too (not
// assets.sql) because this task's change scope names authors.sql as the
// only new query file; they are the scanner-side output of the source
// matching engine and read back via browse.sql ListAssetCharacterNames.
// GET /authors: every author (regular + COS unified, DOMAIN_RULES 6)
// with its linked-asset count and follow flag. Sort = display_name
// ascending, same convention as GET /tags (ListTags ORDER BY t.name,
// DOMAIN_RULES 7 name ordering).
func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Type,
			&i.Followed,
			&i.FileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNormalAssetsForAuthorMatch = `-- name: ListNormalAssetsForAuthorMatch :many
SELECT a.asset_id, a.file_name
FROM assets a
JOIN libraries l ON l.id = a.library_id
WHERE l.kind = 'normal'
`

type ListNormalAssetsForAuthorMatchRow struct {
	AssetID  string
	FileName string
}

// The TXT work-name matching domain: all assets of normal libraries.
// COS assets are excluded by the DOMAIN_RULES 6 isolation rule (regular
// authors only ever match non-COS files).
func (q *Queries) ListNormalAssetsForAuthorMatch(ctx context.Context) ([]ListNormalAssetsForAuthorMatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listNormalAssetsForAuthorMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNormalAssetsForAuthorMatchRow
	for rows.Next() {
		var i ListNormalAssetsForAuthorMatchRow
		if err := rows.Scan(&i.AssetID, &i.FileName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAuthorFollow = `-- name: SetAuthorFollow :execrows
UPDATE authors SET followed = ? WHERE id = ?
`

type SetAuthorFollowParams struct {
	Followed int64
	ID       string
}

// Follow is an author-level boolean (DOMAIN_RULES 5/6: no counter,
// unsetting just clears it). 0 rows affected = unknown authorId; the
// caller maps that to 404.
func (q *Queries) SetAuthorFollow(ctx context.Context, arg SetAuthorFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAuthorFollow, arg.Followed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetSource = `-- name: UpdateAssetSource :exec
UPDATE assets SET source = ?, updated_at = ? WHERE asset_id = ?
`

type UpdateAssetSourceParams struct {
	Source    sql.NullString
	UpdatedAt string
	AssetID   string
}

// Single-asset source refresh (EnrichAsset after API move/rename:
// the file name changes but size+mtime do not, so no re-ingest would
// happen; the write path must recompute explicitly).
func (q *Queries) UpdateAssetSource(ctx context.Context, arg UpdateAssetSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetSource, arg.Source, arg.UpdatedAt, arg.AssetID)
	return err
}

const upsertAuthor = `-- name: UpsertAuthor :exec
INSERT INTO authors (id, display_name, type, followed, created_at)
VALUES (?, ?, ?, 0, ?)
ON CONFLICT (id) DO UPDATE SET
    display_name = excluded.display_name
`

type UpsertAuthorParams struct {
	ID          string
	DisplayName string
	Type        string
	CreatedAt   string
}

// TXT import / COS scan author upsert keyed by the authoring-generated
// id (GenerateAuthorID / GenerateCosAuthorID). Re-import never
// duplicates authors; display_name tracks the (re)imported value. id is
// the identity, so the ON CONFLICT branch must not touch followed
// (re-importing a TXT must not reset the follow flag) nor created_at
// (cold-start freshness, same rule as UpsertAsset).
func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthor,
		arg.ID,
		arg.DisplayName,
		arg.Type,
		arg.CreatedAt,
	)
	return err
}
