// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browse.sql

package db

import (
	"context"
	"database/sql"
)

const countAssetsFiltered = `-- name: CountAssetsFiltered :one
SELECT COUNT(*) FROM assets a
WHERE
    (?1 IS NULL OR a.library_id = ?1)
    AND (?2 IS NULL OR a.media_type = ?2)
    AND (?3 IS NULL
         OR (?4 = 1 AND a.source IS NULL)
         OR a.source = ?3)
    AND (?5 = 1 OR NOT EXISTS (
        SELECT 1 FROM asset_authors aa
        JOIN authors au ON au.id = aa.author_id
        WHERE aa.asset_id = a.asset_id AND au.type = 'cos'))
    AND (?6 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?6) c
        WHERE NOT EXISTS (
            SELECT 1 FROM asset_characters ac
            WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
    AND (?7 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?7))
    AND (?8 IS NULL OR (
        CASE WHEN ?9 = 'exact' THEN
            NOT EXISTS (
                SELECT 1 FROM json_each(?8) jt
                WHERE NOT EXISTS (
                    SELECT 1 FROM asset_tags at2
                    WHERE at2.asset_id = a.asset_id AND at2.tag_id = jt.value))
        ELSE
            EXISTS (
                SELECT 1 FROM json_each(?8) jt
                WHERE EXISTS (
                    SELECT 1 FROM asset_tags at2
                    WHERE at2.asset_id = a.asset_id AND at2.tag_id = jt.value))
        END))
    AND (?10 IS NULL OR (
        CASE WHEN ?10 = 1 THEN
            EXISTS(SELECT 1 FROM favorites fv2 WHERE fv2.asset_id = a.asset_id)
        ELSE
            NOT EXISTS(SELECT 1 FROM favorites fv2 WHERE fv2.asset_id = a.asset_id)
        END))
    AND (?11 IS NULL OR a.mtime >= ?11)
    AND (?12 IS NULL OR a.mtime <= ?12)
    AND (?13 IS NULL OR CAST(substr(a.mtime, 1, 4) AS INTEGER) >= ?13)
    AND (?14 IS NULL OR CAST(substr(a.mtime, 1, 4) AS INTEGER) <= ?14)
    AND (?15 IS NULL OR (
        CASE ?15
            WHEN 'none' THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') = 0
            WHEN 'low'  THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') BETWEEN 1 AND 5
            WHEN 'mid'  THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') BETWEEN 5 AND 20
            WHEN 'high' THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') > 20
            ELSE 1
        END))
    AND (?16 IS NULL OR (
        CASE ?16
            WHEN 'none' THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') = 0
            WHEN 'low'  THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') BETWEEN 1 AND 5
            WHEN 'mid'  THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') BETWEEN 5 AND 20
            WHEN 'high' THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') > 20
            ELSE 1
        END))
    AND (?17 IS NULL OR (
        CASE ?17
            WHEN 'lt1m'    THEN a.size_bytes < 1048576
            WHEN 'm1to10'  THEN a.size_bytes >= 1048576 AND a.size_bytes < 10485760
            WHEN 'm10to50' THEN a.size_bytes >= 10485760 AND a.size_bytes < 52428800
            WHEN 'gt50m'   THEN a.size_bytes >= 52428800
            ELSE 1
        END))
    -- Full-text search (DOMAIN_RULES 3) -- keep in sync with the two list
    -- queries above (same AND clause).
    AND (?18 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?18) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
`

type CountAssetsFilteredParams struct {
	LibraryID      interface{}
	MediaType      interface{}
	Source         interface{}
	SourceIsOther  interface{}
	IncludeCos     interface{}
	CharactersJson interface{}
	AuthorID       interface{}
	TagIdsJson     interface{}
	TagMode        interface{}
	Favorite       interface{}
	MtimeFrom      interface{}
	MtimeTo        interface{}
	YearFrom       interface{}
	YearTo         interface{}
	ViewRange      interface{}
	PlayRange      interface{}
	SizeRange      interface{}
	QJson          interface{}
}

// Same filter matrix minus cursor/order/limit (totalMatched field of
// the AssetPage response). Keep the WHERE clauses in sync with the two
// list queries above.
func (q *Queries) CountAssetsFiltered(ctx context.Context, arg CountAssetsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetsFiltered,
		arg.LibraryID,
		arg.MediaType,
		arg.Source,
		arg.SourceIsOther,
		arg.IncludeCos,
		arg.CharactersJson,
		arg.AuthorID,
		arg.TagIdsJson,
		arg.TagMode,
		arg.Favorite,
		arg.MtimeFrom,
		arg.MtimeTo,
		arg.YearFrom,
		arg.YearTo,
		arg.ViewRange,
		arg.PlayRange,
		arg.SizeRange,
		arg.QJson,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLibraryMedia = `-- name: CountLibraryMedia :many

SELECT media_type, COUNT(*) AS cnt FROM assets
WHERE library_id = ?
GROUP BY media_type
`

type CountLibraryMediaRow struct {
	MediaType string
	Cnt       int64
}

// CountLibraryMedia: per-library media_type counters for the Library
// response (fileCount = sum of the three rows; absent rows = 0).
func (q *Queries) CountLibraryMedia(ctx context.Context, libraryID string) ([]CountLibraryMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, countLibraryMedia, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLibraryMediaRow
	for rows.Next() {
		var i CountLibraryMediaRow
		if err := rows.Scan(&i.MediaType, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetWithLibrary = `-- name: GetAssetWithLibrary :one

SELECT
    a.asset_id, a.library_id, a.rel_path, a.file_name, a.media_type,
    a.size_bytes, a.mtime, a.duration_ms, a.width, a.height, a.source,
    a.created_at, a.updated_at, l.root_path
FROM assets a
JOIN libraries l ON l.id = a.library_id
WHERE a.asset_id = ?
`

type GetAssetWithLibraryRow struct {
	AssetID    string
	LibraryID  string
	RelPath    string
	FileName   string
	MediaType  string
	SizeBytes  int64
	Mtime      string
	DurationMs sql.NullInt64
	Width      sql.NullInt64
	Height     sql.NullInt64
	Source     sql.NullString
	CreatedAt  string
	UpdatedAt  string
	RootPath   string
}

// GetAssetWithLibrary: detail/media-serving join -- serving /media/**
// needs the library root to rebuild the absolute path. Explicit column
// list (not a.*) to avoid ambiguous created_at between the two tables.
func (q *Queries) GetAssetWithLibrary(ctx context.Context, assetID string) (GetAssetWithLibraryRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetWithLibrary, assetID)
	var i GetAssetWithLibraryRow
	err := row.Scan(
		&i.AssetID,
		&i.LibraryID,
		&i.RelPath,
		&i.FileName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Mtime,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootPath,
	)
	return i, err
}

const lastViewedAt = `-- name: LastViewedAt :one
SELECT MAX(started_at) FROM view_events
WHERE asset_id = ? AND kind = 'open'
`

func (q *Queries) LastViewedAt(ctx context.Context, assetID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, lastViewedAt, assetID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const listAssetAuthorRefs = `-- name: ListAssetAuthorRefs :many
SELECT au.id, au.display_name, au.type
FROM asset_authors aa JOIN authors au ON au.id = aa.author_id
WHERE aa.asset_id = ?
ORDER BY au.display_name
`

type ListAssetAuthorRefsRow struct {
	ID          string
	DisplayName string
	Type        string
}

func (q *Queries) ListAssetAuthorRefs(ctx context.Context, assetID string) ([]ListAssetAuthorRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetAuthorRefs, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetAuthorRefsRow
	for rows.Next() {
		var i ListAssetAuthorRefsRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetCharacterNames = `-- name: ListAssetCharacterNames :many

SELECT character_name FROM asset_characters
WHERE asset_id = ?
ORDER BY character_name
`

// Detail assembly queries (tags / authors / characters / stats).
func (q *Queries) ListAssetCharacterNames(ctx context.Context, assetID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAssetCharacterNames, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var character_name string
		if err := rows.Scan(&character_name); err != nil {
			return nil, err
		}
		items = append(items, character_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetTagRefs = `-- name: ListAssetTagRefs :many
SELECT t.id, t.name
FROM asset_tags at JOIN tags t ON t.id = at.tag_id
WHERE at.asset_id = ?
ORDER BY t.name
`

type ListAssetTagRefsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListAssetTagRefs(ctx context.Context, assetID string) ([]ListAssetTagRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetTagRefs, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetTagRefsRow
	for rows.Next() {
		var i ListAssetTagRefsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsFilteredAsc = `-- name: ListAssetsFilteredAsc :many
SELECT
    a.asset_id, a.library_id, a.rel_path, a.file_name, a.media_type,
    a.size_bytes, a.mtime, a.duration_ms, a.width, a.height, a.source,
    a.created_at, a.updated_at,
    EXISTS(SELECT 1 FROM favorites fv WHERE fv.asset_id = a.asset_id) AS is_favorite,
    (SELECT COUNT(*) FROM likes l WHERE l.asset_id = a.asset_id) AS like_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'open') AS view_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'play') AS play_count,
    CASE
        WHEN ?1 = 'fileDate'  THEN a.mtime
        WHEN ?1 = 'name'      THEN a.file_name
        WHEN ?1 = 'sizeBytes' THEN printf('%020d', a.size_bytes)
        WHEN ?1 = 'viewCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v2 WHERE v2.asset_id = a.asset_id AND v2.kind = 'open'))
        WHEN ?1 = 'playCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v3 WHERE v3.asset_id = a.asset_id AND v3.kind = 'play'))
        ELSE a.created_at
    END AS sort_key
FROM assets a
WHERE
    (?2 IS NULL OR a.library_id = ?2)
    AND (?3 IS NULL OR a.media_type = ?3)
    AND (?4 IS NULL
         OR (?5 = 1 AND a.source IS NULL)
         OR a.source = ?4)
    AND (?6 = 1 OR NOT EXISTS (
        SELECT 1 FROM asset_authors aa
        JOIN authors au ON au.id = aa.author_id
        WHERE aa.asset_id = a.asset_id AND au.type = 'cos'))
    AND (?7 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?7) c
        WHERE NOT EXISTS (
            SELECT 1 FROM asset_characters ac
            WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
    AND (?8 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?8))
    AND (?9 IS NULL OR (
        CASE WHEN ?10 = 'exact' THEN
            NOT EXISTS (
                SELECT 1 FROM json_each(?9) jt
                WHERE NOT EXISTS (
                    SELECT 1 FROM asset_tags at2
                    WHERE at2.asset_id = a.asset_id AND at2.tag_id = jt.value))
        ELSE
            EXISTS (
                SELECT 1 FROM json_each(?9) jt
                WHERE EXISTS (
                    SELECT 1 FROM asset_tags at2
                    WHERE at2.asset_id = a.asset_id AND at2.tag_id = jt.value))
        END))
    AND (?11 IS NULL OR (
        CASE WHEN ?11 = 1 THEN
            EXISTS(SELECT 1 FROM favorites fv2 WHERE fv2.asset_id = a.asset_id)
        ELSE
            NOT EXISTS(SELECT 1 FROM favorites fv2 WHERE fv2.asset_id = a.asset_id)
        END))
    AND (?12 IS NULL OR a.mtime >= ?12)
    AND (?13 IS NULL OR a.mtime <= ?13)
    AND (?14 IS NULL OR CAST(substr(a.mtime, 1, 4) AS INTEGER) >= ?14)
    AND (?15 IS NULL OR CAST(substr(a.mtime, 1, 4) AS INTEGER) <= ?15)
    AND (?16 IS NULL OR (
        CASE ?16
            WHEN 'none' THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') = 0
            WHEN 'low'  THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') BETWEEN 1 AND 5
            WHEN 'mid'  THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') BETWEEN 5 AND 20
            WHEN 'high' THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') > 20
            ELSE 1
        END))
    AND (?17 IS NULL OR (
        CASE ?17
            WHEN 'none' THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') = 0
            WHEN 'low'  THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') BETWEEN 1 AND 5
            WHEN 'mid'  THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') BETWEEN 5 AND 20
            WHEN 'high' THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') > 20
            ELSE 1
        END))
    AND (?18 IS NULL OR (
        CASE ?18
            WHEN 'lt1m'    THEN a.size_bytes < 1048576
            WHEN 'm1to10'  THEN a.size_bytes >= 1048576 AND a.size_bytes < 10485760
            WHEN 'm10to50' THEN a.size_bytes >= 10485760 AND a.size_bytes < 52428800
            WHEN 'gt50m'   THEN a.size_bytes >= 52428800
            ELSE 1
        END))
    -- Full-text search (DOMAIN_RULES 3) -- keep in sync with the DESC
    -- variant above (same AND clause; see its comment for semantics).
    AND (?19 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?19) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
    -- keyset cursor (ASC variant).
    AND (?20 IS NULL
        OR (CASE
                WHEN ?1 = 'fileDate'  THEN a.mtime
                WHEN ?1 = 'name'      THEN a.file_name
                WHEN ?1 = 'sizeBytes' THEN printf('%020d', a.size_bytes)
                WHEN ?1 = 'viewCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v6 WHERE v6.asset_id = a.asset_id AND v6.kind = 'open'))
                WHEN ?1 = 'playCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v7 WHERE v7.asset_id = a.asset_id AND v7.kind = 'play'))
                ELSE a.created_at
            END) > ?20
        OR ((CASE
                WHEN ?1 = 'fileDate'  THEN a.mtime
                WHEN ?1 = 'name'      THEN a.file_name
                WHEN ?1 = 'sizeBytes' THEN printf('%020d', a.size_bytes)
                WHEN ?1 = 'viewCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v6 WHERE v6.asset_id = a.asset_id AND v6.kind = 'open'))
                WHEN ?1 = 'playCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v7 WHERE v7.asset_id = a.asset_id AND v7.kind = 'play'))
                ELSE a.created_at
            END) = ?20
            AND a.asset_id > ?21))
ORDER BY sort_key ASC, a.asset_id ASC
LIMIT ?22
`

type ListAssetsFilteredAscParams struct {
	Sort           interface{}
	LibraryID      interface{}
	MediaType      interface{}
	Source         interface{}
	SourceIsOther  interface{}
	IncludeCos     interface{}
	CharactersJson interface{}
	AuthorID       interface{}
	TagIdsJson     interface{}
	TagMode        interface{}
	Favorite       interface{}
	MtimeFrom      interface{}
	MtimeTo        interface{}
	YearFrom       interface{}
	YearTo         interface{}
	ViewRange      interface{}
	PlayRange      interface{}
	SizeRange      interface{}
	QJson          interface{}
	CursorKey      interface{}
	CursorID       sql.NullString
	RowLimit       int64
}

type ListAssetsFilteredAscRow struct {
	AssetID    string
	LibraryID  string
	RelPath    string
	FileName   string
	MediaType  string
	SizeBytes  int64
	Mtime      string
	DurationMs sql.NullInt64
	Width      sql.NullInt64
	Height     sql.NullInt64
	Source     sql.NullString
	CreatedAt  string
	UpdatedAt  string
	IsFavorite bool
	LikeCount  int64
	ViewCount  int64
	PlayCount  int64
	SortKey    interface{}
}

func (q *Queries) ListAssetsFilteredAsc(ctx context.Context, arg ListAssetsFilteredAscParams) ([]ListAssetsFilteredAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsFilteredAsc,
		arg.Sort,
		arg.LibraryID,
		arg.MediaType,
		arg.Source,
		arg.SourceIsOther,
		arg.IncludeCos,
		arg.CharactersJson,
		arg.AuthorID,
		arg.TagIdsJson,
		arg.TagMode,
		arg.Favorite,
		arg.MtimeFrom,
		arg.MtimeTo,
		arg.YearFrom,
		arg.YearTo,
		arg.ViewRange,
		arg.PlayRange,
		arg.SizeRange,
		arg.QJson,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsFilteredAscRow
	for rows.Next() {
		var i ListAssetsFilteredAscRow
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.LikeCount,
			&i.ViewCount,
			&i.PlayCount,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsFilteredDesc = `-- name: ListAssetsFilteredDesc :many

SELECT
    a.asset_id, a.library_id, a.rel_path, a.file_name, a.media_type,
    a.size_bytes, a.mtime, a.duration_ms, a.width, a.height, a.source,
    a.created_at, a.updated_at,
    EXISTS(SELECT 1 FROM favorites fv WHERE fv.asset_id = a.asset_id) AS is_favorite,
    (SELECT COUNT(*) FROM likes l WHERE l.asset_id = a.asset_id) AS like_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'open') AS view_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'play') AS play_count,
    CASE
        WHEN ?1 = 'fileDate'  THEN a.mtime
        WHEN ?1 = 'name'      THEN a.file_name
        WHEN ?1 = 'sizeBytes' THEN printf('%020d', a.size_bytes)
        WHEN ?1 = 'viewCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v2 WHERE v2.asset_id = a.asset_id AND v2.kind = 'open'))
        WHEN ?1 = 'playCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v3 WHERE v3.asset_id = a.asset_id AND v3.kind = 'play'))
        ELSE a.created_at
    END AS sort_key
FROM assets a
WHERE
    (?2 IS NULL OR a.library_id = ?2)
    AND (?3 IS NULL OR a.media_type = ?3)
    -- "no source group" is stored as NULL; the caller translates the
    -- user-facing OTHER bucket into source_is_other = 1 (keeps SQL
    -- literals ASCII for parser safety, see file header).
    AND (?4 IS NULL
         OR (?5 = 1 AND a.source IS NULL)
         OR a.source = ?4)
    -- Default COS exclusion (DOMAIN_RULES 6: COS files never appear in
    -- the regular browse stream); include_cos = 1 re-adds them.
    AND (?6 = 1 OR NOT EXISTS (
        SELECT 1 FROM asset_authors aa
        JOIN authors au ON au.id = aa.author_id
        WHERE aa.asset_id = a.asset_id AND au.type = 'cos'))
    -- character filter: 'a+b' is split by the caller into a JSON array
    -- of canonical names; ALL names must be attached (multi-character
    -- group semantics).
    AND (?7 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?7) c
        WHERE NOT EXISTS (
            SELECT 1 FROM asset_characters ac
            WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
    AND (?8 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?8))
    -- tag filter: fuzzy = ANY selected tag matches; exact = ALL
    -- selected tags must be attached (DOMAIN_RULES 3).
    AND (?9 IS NULL OR (
        CASE WHEN ?10 = 'exact' THEN
            NOT EXISTS (
                SELECT 1 FROM json_each(?9) jt
                WHERE NOT EXISTS (
                    SELECT 1 FROM asset_tags at2
                    WHERE at2.asset_id = a.asset_id AND at2.tag_id = jt.value))
        ELSE
            EXISTS (
                SELECT 1 FROM json_each(?9) jt
                WHERE EXISTS (
                    SELECT 1 FROM asset_tags at2
                    WHERE at2.asset_id = a.asset_id AND at2.tag_id = jt.value))
        END))
    AND (?11 IS NULL OR (
        CASE WHEN ?11 = 1 THEN
            EXISTS(SELECT 1 FROM favorites fv2 WHERE fv2.asset_id = a.asset_id)
        ELSE
            NOT EXISTS(SELECT 1 FROM favorites fv2 WHERE fv2.asset_id = a.asset_id)
        END))
    -- file-date window: TEXT comparison against the RFC3339-ms format;
    -- boundaries precomputed by the caller (dateFrom -> T00:00:00.000Z,
    -- dateTo -> T23:59:59.999Z).
    AND (?12 IS NULL OR a.mtime >= ?12)
    AND (?13 IS NULL OR a.mtime <= ?13)
    AND (?14 IS NULL OR CAST(substr(a.mtime, 1, 4) AS INTEGER) >= ?14)
    AND (?15 IS NULL OR CAST(substr(a.mtime, 1, 4) AS INTEGER) <= ?15)
    -- viewRange / playRange buckets (DOMAIN_RULES 3 literal boundaries:
    -- low = 1-5, mid = 5-20 -- the value 5 falls in both, by the book).
    AND (?16 IS NULL OR (
        CASE ?16
            WHEN 'none' THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') = 0
            WHEN 'low'  THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') BETWEEN 1 AND 5
            WHEN 'mid'  THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') BETWEEN 5 AND 20
            WHEN 'high' THEN (SELECT COUNT(*) FROM view_events v4 WHERE v4.asset_id = a.asset_id AND v4.kind = 'open') > 20
            ELSE 1
        END))
    AND (?17 IS NULL OR (
        CASE ?17
            WHEN 'none' THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') = 0
            WHEN 'low'  THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') BETWEEN 1 AND 5
            WHEN 'mid'  THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') BETWEEN 5 AND 20
            WHEN 'high' THEN (SELECT COUNT(*) FROM view_events v5 WHERE v5.asset_id = a.asset_id AND v5.kind = 'play') > 20
            ELSE 1
        END))
    -- sizeRange buckets; MB = 1024*1024 (file-size convention).
    AND (?18 IS NULL OR (
        CASE ?18
            WHEN 'lt1m'    THEN a.size_bytes < 1048576
            WHEN 'm1to10'  THEN a.size_bytes >= 1048576 AND a.size_bytes < 10485760
            WHEN 'm10to50' THEN a.size_bytes >= 10485760 AND a.size_bytes < 52428800
            WHEN 'gt50m'   THEN a.size_bytes >= 52428800
            ELSE 1
        END))
    -- Full-text search (DOMAIN_RULES 3): q is split on spaces by the
    -- caller (internal/search) into a JSON array; keywords are
    -- AND-combined and each one must substring-match at least one
    -- dimension (file/folder/tags/author/characters/source). instr +
    -- lower is a literal substring match: LIKE wildcards %/_ in user
    -- input have no magic meaning, and ASCII case is folded by lower().
    -- assets_fts is maintained by triggers (migrations/0002_search_fts);
    -- the trigram index currently only backs fast terms -- the instr
    -- scan is bounded by library size, measured ~100ms @ 30k rows
    -- (2026-08-29); revisit with MATCH if profiling says so.
    AND (?19 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?19) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
    -- keyset cursor (DESC variant): strict (sort_key, asset_id) tuple
    -- comparison. The sort_key CASE repeats inline (parser rule 3).
    AND (?20 IS NULL
        OR (CASE
                WHEN ?1 = 'fileDate'  THEN a.mtime
                WHEN ?1 = 'name'      THEN a.file_name
                WHEN ?1 = 'sizeBytes' THEN printf('%020d', a.size_bytes)
                WHEN ?1 = 'viewCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v6 WHERE v6.asset_id = a.asset_id AND v6.kind = 'open'))
                WHEN ?1 = 'playCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v7 WHERE v7.asset_id = a.asset_id AND v7.kind = 'play'))
                ELSE a.created_at
            END) < ?20
        OR ((CASE
                WHEN ?1 = 'fileDate'  THEN a.mtime
                WHEN ?1 = 'name'      THEN a.file_name
                WHEN ?1 = 'sizeBytes' THEN printf('%020d', a.size_bytes)
                WHEN ?1 = 'viewCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v6 WHERE v6.asset_id = a.asset_id AND v6.kind = 'open'))
                WHEN ?1 = 'playCount' THEN printf('%020d', (SELECT COUNT(*) FROM view_events v7 WHERE v7.asset_id = a.asset_id AND v7.kind = 'play'))
                ELSE a.created_at
            END) = ?20
            AND a.asset_id < ?21))
ORDER BY sort_key DESC, a.asset_id DESC
LIMIT ?22
`

type ListAssetsFilteredDescParams struct {
	Sort           interface{}
	LibraryID      interface{}
	MediaType      interface{}
	Source         interface{}
	SourceIsOther  interface{}
	IncludeCos     interface{}
	CharactersJson interface{}
	AuthorID       interface{}
	TagIdsJson     interface{}
	TagMode        interface{}
	Favorite       interface{}
	MtimeFrom      interface{}
	MtimeTo        interface{}
	YearFrom       interface{}
	YearTo         interface{}
	ViewRange      interface{}
	PlayRange      interface{}
	SizeRange      interface{}
	QJson          interface{}
	CursorKey      interface{}
	CursorID       sql.NullString
	RowLimit       int64
}

type ListAssetsFilteredDescRow struct {
	AssetID    string
	LibraryID  string
	RelPath    string
	FileName   string
	MediaType  string
	SizeBytes  int64
	Mtime      string
	DurationMs sql.NullInt64
	Width      sql.NullInt64
	Height     sql.NullInt64
	Source     sql.NullString
	CreatedAt  string
	UpdatedAt  string
	IsFavorite bool
	LikeCount  int64
	ViewCount  int64
	PlayCount  int64
	SortKey    interface{}
}

// browse queries (M1 httpapi browse loop: filtered/sorted/paginated asset
// list, detail assembly, engagement writes).
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug) and migrations/0001_init.up.sql for
// Chinese explanations.
//
// ============ Why this file looks the way it does ============
// The sqlc v1.31.1 SQLite parser was probed in a lab before writing
// these queries; the shapes below are exactly the subset it accepts:
//  1. Parameter macros must use the BARE form sqlc.arg(x)/sqlc.narg(x).
//     The "?sqlc.arg(x)" prefix form from the docs fails to parse.
//  2. A parameter may not be the subject of CASE ... WHEN; it must sit
//     inside a WHEN comparison (CASE WHEN sqlc.arg(sort) = 'name' ...).
//     Exception: CASE sqlc.narg(x) WHEN 'lit' (parameter as subject)
//     parses when every branch is a literal test.
//  3. WHERE cannot reference derived-table/CTE aliases ("table alias
//     does not exist") -> the queries stay SINGLE-LEVEL and repeat
//     scalar subqueries / CASE expressions inline instead of joining
//     a projection subquery.
//  4. sqlc.arg() inside ORDER BY is NOT macro-expanded (left verbatim
//     in the generated SQL, which would crash SQLite at runtime) ->
//     sort DIRECTION is baked into two query variants (Asc/Desc)
//     instead of being a runtime parameter. ORDER BY may reference
//     SELECT-projection aliases, which the sort_key column uses.
//
// ============ Sorting design ============
// 7 sort keys (openapi sort enum) collapse into ONE TEXT "sort_key"
// expression per query:
//   - TEXT keys (fileDate=mtime / addedDate=created_at / name) pass
//     through: the store-wide RFC3339-ms format keeps lexicographic
//     order == chronological order by design.
//   - INTEGER keys (sizeBytes / viewCount / playCount) go through
//     printf('%020d', n): counts and sizes are >= 0 and fit in 20
//     digits, so numeric order == lexicographic order.
//
// The unified TEXT key makes the keyset cursor generic: the cursor is
// just (sort_key, asset_id) of the last row of the previous page.
// 'default' falls back to addedDate for M1 (the real default sort is
// the recommendation algorithm, which lands with M2/M3).
//
// ============ Cursor predicate ============
// Strict tuple comparison (sort_key, asset_id) < (or >) the cursor,
// expanded row-value form, mirroring ListAssetsAfterCursor in
// assets.sql. The sort_key CASE expression is repeated inline because
// of parser rule 3 above -- THE INLINE COPIES MUST STAY IDENTICAL TO
// THE PROJECTION COPY.
//
// ============ Performance note ============
// The view/play count scalar subqueries repeat several times per query
// (projection + cursor + range buckets). Each hit is an indexed lookup
// on idx_view_events_asset, and M1 libraries are tens of thousands of
// rows; re-visit only if profiling says so.
func (q *Queries) ListAssetsFilteredDesc(ctx context.Context, arg ListAssetsFilteredDescParams) ([]ListAssetsFilteredDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsFilteredDesc,
		arg.Sort,
		arg.LibraryID,
		arg.MediaType,
		arg.Source,
		arg.SourceIsOther,
		arg.IncludeCos,
		arg.CharactersJson,
		arg.AuthorID,
		arg.TagIdsJson,
		arg.TagMode,
		arg.Favorite,
		arg.MtimeFrom,
		arg.MtimeTo,
		arg.YearFrom,
		arg.YearTo,
		arg.ViewRange,
		arg.PlayRange,
		arg.SizeRange,
		arg.QJson,
		arg.CursorKey,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsFilteredDescRow
	for rows.Next() {
		var i ListAssetsFilteredDescRow
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFavorite,
			&i.LikeCount,
			&i.ViewCount,
			&i.PlayCount,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLikeOnDay = `-- name: RemoveLikeOnDay :execrows

DELETE FROM likes WHERE asset_id = ? AND day = ?
`

type RemoveLikeOnDayParams struct {
	AssetID string
	Day     string
}

// RemoveLikeOnDay: the un-like half of the daily like toggle
// (openapi PUT .../like is a toggle; DOMAIN_RULES 5 daily reset is
// implied by the day-scoped DELETE).
func (q *Queries) RemoveLikeOnDay(ctx context.Context, arg RemoveLikeOnDayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeLikeOnDay, arg.AssetID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumBrowseSeconds = `-- name: SumBrowseSeconds :one
SELECT COALESCE(SUM(seconds), 0) FROM view_events
WHERE asset_id = ? AND kind = 'dwell'
`

func (q *Queries) SumBrowseSeconds(ctx context.Context, assetID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumBrowseSeconds, assetID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
