// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_stats.sql

package db

import (
	"context"
)

const deleteAllAssetDailyStats = `-- name: DeleteAllAssetDailyStats :exec

DELETE FROM asset_daily_stats
`

// DeleteAllAssetDailyStats: wipe the materialized table before a full
// rebuild from view_events (Go-side rebuild -- see
// httpapi.RebuildAssetDailyStatsFromEvents for why the day bucketing
// happens in Go, not in SQL).
func (q *Queries) DeleteAllAssetDailyStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAssetDailyStats)
	return err
}

const listAllAssetIDs = `-- name: ListAllAssetIDs :many

SELECT asset_id FROM assets
`

// ListAllAssetIDs: current asset identities, used by the rebuild to
// drop events whose asset was deleted (view_events has no FK, adr/0005;
// asset_daily_stats does -- the rebuild must not insert orphan rows).
func (q *Queries) ListAllAssetIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyStatsBetween = `-- name: SumDailyStatsBetween :many

SELECT asset_daily_stats.day                AS day,
       CAST(SUM(asset_daily_stats.view_count) AS INTEGER)     AS view_count,
       CAST(SUM(asset_daily_stats.play_count) AS INTEGER)     AS play_count,
       CAST(SUM(asset_daily_stats.browse_seconds) AS INTEGER) AS browse_seconds
FROM asset_daily_stats
JOIN assets ON assets.asset_id = asset_daily_stats.asset_id
WHERE asset_daily_stats.day >= ?1
  AND asset_daily_stats.day <= ?2
  AND (CAST(?3 AS TEXT) = '' OR assets.media_type = CAST(?3 AS TEXT))
GROUP BY asset_daily_stats.day
ORDER BY asset_daily_stats.day
`

type SumDailyStatsBetweenParams struct {
	FromDay   string
	ToDay     string
	MediaType string
}

type SumDailyStatsBetweenRow struct {
	Day           string
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds int64
}

// SumDailyStatsBetween: trend buckets data source -- per-day sums for a
// day range (inclusive, day = YYYY-MM-DD local calendar day). mediaType
// filter: empty string = no filter (sqlc.arg + ” sentinel, same
// convention as the empty-string params elsewhere in this project);
// otherwise exact assets.media_type match. Rows are ordered by day so
// the caller can stream them into bucketing as-is.
//
// Why no separate SumDailyStatsAll query: the stats overview counts
// views directly from view_events (kind='open'), per DOMAIN_RULES 5
// "event stream is the single source of truth" -- the materialized
// table only serves trend bucketing, and the all-range trend reuses
// SumDailyStatsBetween with an empty fromDay (day >= ” always true).
// Adding a third aggregation path would just widen the surface that
// can drift from the event-stream truth.
func (q *Queries) SumDailyStatsBetween(ctx context.Context, arg SumDailyStatsBetweenParams) ([]SumDailyStatsBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, sumDailyStatsBetween, arg.FromDay, arg.ToDay, arg.MediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumDailyStatsBetweenRow
	for rows.Next() {
		var i SumDailyStatsBetweenRow
		if err := rows.Scan(
			&i.Day,
			&i.ViewCount,
			&i.PlayCount,
			&i.BrowseSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeAssets = `-- name: SummarizeAssets :one

SELECT
    COUNT(*) AS total_files,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type IN ('image', 'animated_image') THEN 1 ELSE 0 END), 0) AS INTEGER) AS image_count,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type = 'video' THEN 1 ELSE 0 END), 0) AS INTEGER) AS video_count,
    CAST(COALESCE(SUM(assets.size_bytes), 0) AS INTEGER) AS total_size_bytes
FROM assets
`

type SummarizeAssetsRow struct {
	TotalFiles     int64
	ImageCount     int64
	VideoCount     int64
	TotalSizeBytes int64
}

// SummarizeAssets: stats overview library shape (total files, image
// count with animated_image folded in per DOMAIN_RULES 11 media types,
// video count, total size). COALESCE keeps empty-library SUMs at 0
// instead of NULL so the handler never needs null handling.
func (q *Queries) SummarizeAssets(ctx context.Context) (SummarizeAssetsRow, error) {
	row := q.db.QueryRowContext(ctx, summarizeAssets)
	var i SummarizeAssetsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.ImageCount,
		&i.VideoCount,
		&i.TotalSizeBytes,
	)
	return i, err
}

const upsertAssetDailyStats = `-- name: UpsertAssetDailyStats :exec


INSERT INTO asset_daily_stats (asset_id, day, view_count, play_count, browse_seconds)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (asset_id, day) DO UPDATE SET
    view_count     = asset_daily_stats.view_count + excluded.view_count,
    play_count     = asset_daily_stats.play_count + excluded.play_count,
    browse_seconds = asset_daily_stats.browse_seconds + excluded.browse_seconds
`

type UpsertAssetDailyStatsParams struct {
	AssetID       string
	Day           string
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds int64
}

// daily_stats queries: "asset x day" materialized aggregation table
// (migrations/0005_m3_stats_cos.up.sql section 3) + stats overview
// aggregation. The event stream (view_events) is the ONLY source of
// truth (DOMAIN_RULES 5); this table is a cache that must be derivable
// from the stream at any time.
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug) and migrations/0001_init.up.sql for
// Chinese explanations.
// UpsertAssetDailyStats: incremental delta accumulation (NOT replace).
// open/play events add +1 to view/play; dwell adds its seconds. The
// caller keeps the deltas aligned with the event it just inserted so
// the materialized table stays consistent with the event stream.
func (q *Queries) UpsertAssetDailyStats(ctx context.Context, arg UpsertAssetDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssetDailyStats,
		arg.AssetID,
		arg.Day,
		arg.ViewCount,
		arg.PlayCount,
		arg.BrowseSeconds,
	)
	return err
}
