// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_stats.sql

package db

import (
	"context"
)

const countCosLinkedAssets = `-- name: CountCosLinkedAssets :one

SELECT CAST(COUNT(*) AS INTEGER) FROM assets a
WHERE EXISTS (
    SELECT 1 FROM asset_authors aacos
    JOIN authors aucos ON aucos.id = aacos.author_id
    WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos')
`

// CountCosLinkedAssets / CountRegularAssets: overview source inventory
// (protocol batch P2, 2026-09-09). The two predicates mirror the browse
// partition switch (DOMAIN_RULES 6): cos = linked to at least one cos
// author, regular = linked to none. normal_count + cos_count == total
// files (both scan assets directly, so the sum is exact).
func (q *Queries) CountCosLinkedAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCosLinkedAssets)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRegularAssets = `-- name: CountRegularAssets :one
SELECT CAST(COUNT(*) AS INTEGER) FROM assets a
WHERE NOT EXISTS (
    SELECT 1 FROM asset_authors aa
    JOIN authors au ON au.id = aa.author_id
    WHERE aa.asset_id = a.asset_id AND au.type = 'cos')
`

func (q *Queries) CountRegularAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRegularAssets)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAllAssetDailyStats = `-- name: DeleteAllAssetDailyStats :exec

DELETE FROM asset_daily_stats
`

// DeleteAllAssetDailyStats: wipe the materialized table before a full
// rebuild from view_events (Go-side rebuild -- see
// httpapi.RebuildAssetDailyStatsFromEvents for why the day bucketing
// happens in Go, not in SQL).
func (q *Queries) DeleteAllAssetDailyStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAssetDailyStats)
	return err
}

const listAllAssetIDs = `-- name: ListAllAssetIDs :many

SELECT asset_id FROM assets
`

// ListAllAssetIDs: current asset identities, used by the rebuild to
// drop events whose asset was deleted (view_events has no FK, adr/0005;
// asset_daily_stats does -- the rebuild must not insert orphan rows).
func (q *Queries) ListAllAssetIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDailyStatsBetween = `-- name: SumDailyStatsBetween :many

SELECT asset_daily_stats.day                AS day,
       CAST(SUM(asset_daily_stats.view_count) AS INTEGER)     AS view_count,
       CAST(SUM(asset_daily_stats.play_count) AS INTEGER)     AS play_count,
       CAST(SUM(asset_daily_stats.browse_seconds) AS INTEGER) AS browse_seconds
FROM asset_daily_stats
JOIN assets ON assets.asset_id = asset_daily_stats.asset_id
WHERE asset_daily_stats.day >= ?1
  AND asset_daily_stats.day <= ?2
  AND (CAST(?3 AS TEXT) = '' OR assets.media_type = CAST(?3 AS TEXT))
  AND (CAST(?4 AS TEXT) = ''
       OR (?4 = 'cos' AND EXISTS (
           SELECT 1 FROM asset_authors aacos
           JOIN authors aucos ON aucos.id = aacos.author_id
           WHERE aacos.asset_id = asset_daily_stats.asset_id AND aucos.type = 'cos'))
       OR (?4 = 'normal' AND NOT EXISTS (
           SELECT 1 FROM asset_authors aareg
           JOIN authors aureg ON aureg.id = aareg.author_id
           WHERE aareg.asset_id = asset_daily_stats.asset_id AND aureg.type = 'cos')))
GROUP BY asset_daily_stats.day
ORDER BY asset_daily_stats.day
`

type SumDailyStatsBetweenParams struct {
	FromDay      string
	ToDay        string
	MediaType    string
	SourceBucket string
}

type SumDailyStatsBetweenRow struct {
	Day           string
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds int64
}

// SumDailyStatsBetween: trend buckets data source -- per-day sums for a
// day range (inclusive, day = YYYY-MM-DD local calendar day). mediaType
// filter: empty string = no filter (sqlc.arg + ” sentinel, same
// convention as the empty-string params elsewhere in this project);
// otherwise exact assets.media_type match. Rows are ordered by day so
// the caller can stream them into bucketing as-is.
//
// Why no separate SumDailyStatsAll query: the stats overview counts
// views directly from view_events (kind='open'), per DOMAIN_RULES 5
// "event stream is the single source of truth" -- the materialized
// table only serves trend bucketing, and the all-range trend reuses
// SumDailyStatsBetween with an empty fromDay (day >= ” always true).
// Adding a third aggregation path would just widen the surface that
// can drift from the event-stream truth.
func (q *Queries) SumDailyStatsBetween(ctx context.Context, arg SumDailyStatsBetweenParams) ([]SumDailyStatsBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, sumDailyStatsBetween,
		arg.FromDay,
		arg.ToDay,
		arg.MediaType,
		arg.SourceBucket,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumDailyStatsBetweenRow
	for rows.Next() {
		var i SumDailyStatsBetweenRow
		if err := rows.Scan(
			&i.Day,
			&i.ViewCount,
			&i.PlayCount,
			&i.BrowseSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeAssets = `-- name: SummarizeAssets :one

SELECT
    COUNT(*) AS total_files,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type IN ('image', 'animated_image') THEN 1 ELSE 0 END), 0) AS INTEGER) AS image_count,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type = 'video' THEN 1 ELSE 0 END), 0) AS INTEGER) AS video_count,
    CAST(COALESCE(SUM(assets.size_bytes), 0) AS INTEGER) AS total_size_bytes,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type = 'image' THEN assets.size_bytes ELSE 0 END), 0) AS INTEGER) AS image_size_bytes,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type = 'video' THEN assets.size_bytes ELSE 0 END), 0) AS INTEGER) AS video_size_bytes,
    CAST(COALESCE(SUM(CASE WHEN assets.media_type = 'animated_image' THEN assets.size_bytes ELSE 0 END), 0) AS INTEGER) AS animated_image_size_bytes
FROM assets
`

type SummarizeAssetsRow struct {
	TotalFiles             int64
	ImageCount             int64
	VideoCount             int64
	TotalSizeBytes         int64
	ImageSizeBytes         int64
	VideoSizeBytes         int64
	AnimatedImageSizeBytes int64
}

// SummarizeAssets: stats overview library shape (total files, image
// count with animated_image folded in per DOMAIN_RULES 11 media types,
// video count, total size, per-type size sums). Per-type sizes keep
// animated_image as its own key (physical footprint accounting: the
// three keys sum to total_size_bytes exactly). COALESCE keeps empty-
// library SUMs at 0 instead of NULL so the handler never needs null
// handling.
func (q *Queries) SummarizeAssets(ctx context.Context) (SummarizeAssetsRow, error) {
	row := q.db.QueryRowContext(ctx, summarizeAssets)
	var i SummarizeAssetsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.ImageCount,
		&i.VideoCount,
		&i.TotalSizeBytes,
		&i.ImageSizeBytes,
		&i.VideoSizeBytes,
		&i.AnimatedImageSizeBytes,
	)
	return i, err
}

const summarizeSourceSizes = `-- name: SummarizeSourceSizes :one

SELECT
    CAST(COALESCE(SUM(CASE WHEN NOT EXISTS (
        SELECT 1 FROM asset_authors aanorm
        JOIN authors aunorm ON aunorm.id = aanorm.author_id
        WHERE aanorm.asset_id = a.asset_id AND aunorm.type = 'cos')
        THEN a.size_bytes ELSE 0 END), 0) AS INTEGER) AS normal_size_bytes,
    CAST(COALESCE(SUM(CASE WHEN EXISTS (
        SELECT 1 FROM asset_authors aacos
        JOIN authors aucos ON aucos.id = aacos.author_id
        WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos')
        THEN a.size_bytes ELSE 0 END), 0) AS INTEGER) AS cos_size_bytes
FROM assets a
`

type SummarizeSourceSizesRow struct {
	NormalSizeBytes int64
	CosSizeBytes    int64
}

// SummarizeSourceSizes: overview per-source size sums (protocol batch
// 2026-09-14). Predicates mirror CountCosLinkedAssets / CountRegularAssets
// (DOMAIN_RULES 6 partition, no new criteria): normal = no cos author
// linked, cos = at least one cos author linked. The two columns sum to
// total_size_bytes (both branch on the same rows). One query instead of
// two -- same scan, two conditional SUMs.
func (q *Queries) SummarizeSourceSizes(ctx context.Context) (SummarizeSourceSizesRow, error) {
	row := q.db.QueryRowContext(ctx, summarizeSourceSizes)
	var i SummarizeSourceSizesRow
	err := row.Scan(&i.NormalSizeBytes, &i.CosSizeBytes)
	return i, err
}

const upsertAssetDailyStats = `-- name: UpsertAssetDailyStats :exec


INSERT INTO asset_daily_stats (asset_id, day, view_count, play_count, browse_seconds)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (asset_id, day) DO UPDATE SET
    view_count     = asset_daily_stats.view_count + excluded.view_count,
    play_count     = asset_daily_stats.play_count + excluded.play_count,
    browse_seconds = asset_daily_stats.browse_seconds + excluded.browse_seconds
`

type UpsertAssetDailyStatsParams struct {
	AssetID       string
	Day           string
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds int64
}

// daily_stats queries: "asset x day" materialized aggregation table
// (migrations/0005_m3_stats_cos.up.sql section 3) + stats overview
// aggregation. The event stream (view_events) is the ONLY source of
// truth (DOMAIN_RULES 5); this table is a cache that must be derivable
// from the stream at any time.
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug) and migrations/0001_init.up.sql for
// Chinese explanations.
// UpsertAssetDailyStats: incremental delta accumulation (NOT replace).
// open/play events add +1 to view/play; dwell adds its seconds. The
// caller keeps the deltas aligned with the event it just inserted so
// the materialized table stays consistent with the event stream.
func (q *Queries) UpsertAssetDailyStats(ctx context.Context, arg UpsertAssetDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssetDailyStats,
		arg.AssetID,
		arg.Day,
		arg.ViewCount,
		arg.PlayCount,
		arg.BrowseSeconds,
	)
	return err
}
