// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_shown.sql

package db

import (
	"context"
)

const incrementDailyShown = `-- name: IncrementDailyShown :exec

INSERT INTO daily_shown (asset_id, day, count)
VALUES (?, ?, 1)
ON CONFLICT (asset_id, day) DO UPDATE SET count = daily_shown.count + 1
`

type IncrementDailyShownParams struct {
	AssetID string
	Day     string
}

// daily_shown queries: daily recommendation impression counter
// (DOMAIN_RULES 1.4: dailyPenalty input; counter is cache-like and can
// be dropped/rebuilt -- see table comment in migrations/0001_init.up.sql).
// ASCII-only comments here; see assets.sql header note.
// day is YYYY-MM-DD in the server's local timezone (0001 header rule).
func (q *Queries) IncrementDailyShown(ctx context.Context, arg IncrementDailyShownParams) error {
	_, err := q.db.ExecContext(ctx, incrementDailyShown, arg.AssetID, arg.Day)
	return err
}
