// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facets.sql

package db

import (
	"context"
	"database/sql"
)

const facetAuthorCounts = `-- name: FacetAuthorCounts :many
SELECT au.id AS author_id,
       au.display_name AS author_name,
       COUNT(DISTINCT a.asset_id) AS file_count
FROM assets a
JOIN asset_authors aa ON aa.asset_id = a.asset_id
JOIN authors au ON au.id = aa.author_id
WHERE
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
    AND au.type = 'cos'
    AND (?1 = 1
         OR (?2 = 1 AND EXISTS (
             SELECT 1 FROM asset_authors aacos
             JOIN authors aucos ON aucos.id = aacos.author_id
             WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos'))
         OR (?2 = 0 AND NOT EXISTS (
             SELECT 1 FROM asset_authors aareg
             JOIN authors aureg ON aureg.id = aareg.author_id
             WHERE aareg.asset_id = a.asset_id AND aureg.type = 'cos')))
    AND (?3 IS NULL OR a.media_type = ?3)
    AND (?4 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?4) c
        WHERE NOT EXISTS (
            SELECT 1 FROM asset_characters ac
            WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
    AND (?5 IS NULL OR a.cos_work = ?5)
    AND ((?6 IS NULL AND ?7 = 0)
         OR (?7 = 1 AND a.source IS NULL
             AND NOT EXISTS (
                 SELECT 1 FROM asset_authors aaoth
                 JOIN authors auoth ON auoth.id = aaoth.author_id
                 WHERE aaoth.asset_id = a.asset_id AND auoth.type = 'cos'))
         OR a.source = ?6)
    AND (?8 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?8))
    AND (?9 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?9) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
    -- subset constraints (see file header).
    AND (?10 = 0 OR EXISTS (
        SELECT 1 FROM favorites fvs WHERE fvs.asset_id = a.asset_id))
    AND (?11 = 0 OR EXISTS (
        SELECT 1 FROM view_events veh
        WHERE veh.asset_id = a.asset_id AND veh.kind = 'open'))
GROUP BY au.id
ORDER BY file_count DESC, au.display_name
`

type FacetAuthorCountsParams struct {
	IncludeCos     interface{}
	CosOnly        interface{}
	MediaType      interface{}
	CharactersJson interface{}
	CosWork        interface{}
	Source         interface{}
	SourceIsOther  interface{}
	AuthorID       interface{}
	QJson          interface{}
	FavoriteSubset interface{}
	HistorySubset  interface{}
}

type FacetAuthorCountsRow struct {
	AuthorID   string
	AuthorName string
	FileCount  int64
}

// Author-row COS-AUTHOR buckets (old app groupByCosAuthor). Restrained
// to au.type = 'cos': regular TXT authors are NOT part of this row (user
// decision 2026-09-03 -- the row is "cos authors + regular works").
// key = author_id, ready to be fed back into GET /assets.
// source / source_is_other / author_id apply as plain narrowing keys
// (protocol 2026-09-09, same as FacetSourceCounts: exclude-self is
// client-side). The partition flags are kept for shape consistency with
// the other facet queries; with au.type='cos' the regular partition
// naturally yields no rows (cos authors only link cos-linked assets).
func (q *Queries) FacetAuthorCounts(ctx context.Context, arg FacetAuthorCountsParams) ([]FacetAuthorCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, facetAuthorCounts,
		arg.IncludeCos,
		arg.CosOnly,
		arg.MediaType,
		arg.CharactersJson,
		arg.CosWork,
		arg.Source,
		arg.SourceIsOther,
		arg.AuthorID,
		arg.QJson,
		arg.FavoriteSubset,
		arg.HistorySubset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetAuthorCountsRow
	for rows.Next() {
		var i FacetAuthorCountsRow
		if err := rows.Scan(&i.AuthorID, &i.AuthorName, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetCharacterCounts = `-- name: FacetCharacterCounts :many
SELECT ac.character_name AS character_name,
       COUNT(DISTINCT a.asset_id) AS file_count
FROM assets a
JOIN asset_characters ac ON ac.asset_id = a.asset_id
WHERE
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
    AND (?1 = 1
         OR (?2 = 1 AND EXISTS (
             SELECT 1 FROM asset_authors aacos
             JOIN authors aucos ON aucos.id = aacos.author_id
             WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos'))
         OR (?2 = 0 AND NOT EXISTS (
             SELECT 1 FROM asset_authors aareg
             JOIN authors aureg ON aureg.id = aareg.author_id
             WHERE aareg.asset_id = a.asset_id AND aureg.type = 'cos')))
    AND (?3 IS NULL OR a.media_type = ?3)
    AND (?4 IS NULL
         OR (?5 = 1 AND a.source IS NULL
             AND NOT EXISTS (
                 SELECT 1 FROM asset_authors aaoth
                 JOIN authors auoth ON auoth.id = aaoth.author_id
                 WHERE aaoth.asset_id = a.asset_id AND auoth.type = 'cos'))
         OR a.source = ?4)
    AND (?6 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?6))
    AND (?7 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?7) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
    -- subset constraints (see file header).
    AND (?8 = 0 OR EXISTS (
        SELECT 1 FROM favorites fvs WHERE fvs.asset_id = a.asset_id))
    AND (?9 = 0 OR EXISTS (
        SELECT 1 FROM view_events veh
        WHERE veh.asset_id = a.asset_id AND veh.kind = 'open'))
GROUP BY ac.character_name
ORDER BY file_count DESC, ac.character_name
`

type FacetCharacterCountsParams struct {
	IncludeCos     interface{}
	CosOnly        interface{}
	MediaType      interface{}
	Source         interface{}
	SourceIsOther  interface{}
	AuthorID       interface{}
	QJson          interface{}
	FavoriteSubset interface{}
	HistorySubset  interface{}
}

type FacetCharacterCountsRow struct {
	CharacterName string
	FileCount     int64
}

// Character-row REGULAR buckets: canonical names produced by the source
// matcher (asset_characters). character/work filters excluded (self row).
// The source filter applies (author row selection, other dimension).
func (q *Queries) FacetCharacterCounts(ctx context.Context, arg FacetCharacterCountsParams) ([]FacetCharacterCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, facetCharacterCounts,
		arg.IncludeCos,
		arg.CosOnly,
		arg.MediaType,
		arg.Source,
		arg.SourceIsOther,
		arg.AuthorID,
		arg.QJson,
		arg.FavoriteSubset,
		arg.HistorySubset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetCharacterCountsRow
	for rows.Next() {
		var i FacetCharacterCountsRow
		if err := rows.Scan(&i.CharacterName, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetCosWorkCounts = `-- name: FacetCosWorkCounts :many
SELECT a.cos_work AS work_name,
       COUNT(*) AS file_count
FROM assets a
WHERE a.cos_work IS NOT NULL
  AND EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
  AND (?1 = 1
       OR (?2 = 1 AND EXISTS (
           SELECT 1 FROM asset_authors aacos
           JOIN authors aucos ON aucos.id = aacos.author_id
           WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos'))
       OR (?2 = 0 AND NOT EXISTS (
           SELECT 1 FROM asset_authors aareg
           JOIN authors aureg ON aureg.id = aareg.author_id
           WHERE aareg.asset_id = a.asset_id AND aureg.type = 'cos')))
  AND (?3 IS NULL OR a.media_type = ?3)
  AND (?4 IS NULL
       OR (?5 = 1 AND a.source IS NULL
           AND NOT EXISTS (
               SELECT 1 FROM asset_authors aaoth
               JOIN authors auoth ON auoth.id = aaoth.author_id
               WHERE aaoth.asset_id = a.asset_id AND auoth.type = 'cos'))
       OR a.source = ?4)
  AND (?6 IS NULL OR EXISTS (
      SELECT 1 FROM asset_authors aa2
      WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?6))
  AND (?7 IS NULL OR NOT EXISTS (
      SELECT 1 FROM json_each(?7) qk
      WHERE NOT EXISTS (
          SELECT 1 FROM assets_fts f
          WHERE f.rowid = a.rowid
            AND instr(lower(f.all_text), lower(qk.value)) > 0)))
  -- subset constraints (see file header).
  AND (?8 = 0 OR EXISTS (
      SELECT 1 FROM favorites fvs WHERE fvs.asset_id = a.asset_id))
  AND (?9 = 0 OR EXISTS (
      SELECT 1 FROM view_events veh
      WHERE veh.asset_id = a.asset_id AND veh.kind = 'open'))
GROUP BY a.cos_work
ORDER BY file_count DESC, a.cos_work
`

type FacetCosWorkCountsParams struct {
	IncludeCos     interface{}
	CosOnly        interface{}
	MediaType      interface{}
	Source         interface{}
	SourceIsOther  interface{}
	AuthorID       interface{}
	QJson          interface{}
	FavoriteSubset interface{}
	HistorySubset  interface{}
}

type FacetCosWorkCountsRow struct {
	WorkName  sql.NullString
	FileCount int64
}

// Character-row COS buckets: the work directory name (migration 0008,
// `author/work/file` second segment) -- old-app "COS character = work
// name". NULL cos_work (files placed directly under the author directory)
// is the old app's "other" bucket and is left out; the web client adds
// the fallback pill. character/work filters excluded (self row); the
// source filter applies (author row selection, other dimension).
func (q *Queries) FacetCosWorkCounts(ctx context.Context, arg FacetCosWorkCountsParams) ([]FacetCosWorkCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, facetCosWorkCounts,
		arg.IncludeCos,
		arg.CosOnly,
		arg.MediaType,
		arg.Source,
		arg.SourceIsOther,
		arg.AuthorID,
		arg.QJson,
		arg.FavoriteSubset,
		arg.HistorySubset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetCosWorkCountsRow
	for rows.Next() {
		var i FacetCosWorkCountsRow
		if err := rows.Scan(&i.WorkName, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetMediaTypeCounts = `-- name: FacetMediaTypeCounts :many
SELECT a.media_type AS media_type,
       COUNT(*) AS file_count
FROM assets a
WHERE
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
  AND (?1 = 1
       OR (?2 = 1 AND EXISTS (
           SELECT 1 FROM asset_authors aacos
           JOIN authors aucos ON aucos.id = aacos.author_id
           WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos'))
       OR (?2 = 0 AND NOT EXISTS (
           SELECT 1 FROM asset_authors aareg
           JOIN authors aureg ON aureg.id = aareg.author_id
           WHERE aareg.asset_id = a.asset_id AND aureg.type = 'cos')))
  AND (?3 IS NULL OR NOT EXISTS (
      SELECT 1 FROM json_each(?3) c
      WHERE NOT EXISTS (
          SELECT 1 FROM asset_characters ac
          WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
  AND (?4 IS NULL OR a.cos_work = ?4)
  AND (?5 IS NULL
       OR (?6 = 1 AND a.source IS NULL
           AND NOT EXISTS (
               SELECT 1 FROM asset_authors aaoth
               JOIN authors auoth ON auoth.id = aaoth.author_id
               WHERE aaoth.asset_id = a.asset_id AND auoth.type = 'cos'))
       OR a.source = ?5)
  AND (?7 IS NULL OR EXISTS (
      SELECT 1 FROM asset_authors aa2
      WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?7))
  AND (?8 IS NULL OR NOT EXISTS (
      SELECT 1 FROM json_each(?8) qk
      WHERE NOT EXISTS (
          SELECT 1 FROM assets_fts f
          WHERE f.rowid = a.rowid
            AND instr(lower(f.all_text), lower(qk.value)) > 0)))
  -- subset constraints (see file header).
  AND (?9 = 0 OR EXISTS (
      SELECT 1 FROM favorites fvs WHERE fvs.asset_id = a.asset_id))
  AND (?10 = 0 OR EXISTS (
      SELECT 1 FROM view_events veh
      WHERE veh.asset_id = a.asset_id AND veh.kind = 'open'))
GROUP BY a.media_type
ORDER BY file_count DESC
`

type FacetMediaTypeCountsParams struct {
	IncludeCos     interface{}
	CosOnly        interface{}
	CharactersJson interface{}
	CosWork        interface{}
	Source         interface{}
	SourceIsOther  interface{}
	AuthorID       interface{}
	QJson          interface{}
	FavoriteSubset interface{}
	HistorySubset  interface{}
}

type FacetMediaTypeCountsRow struct {
	MediaType string
	FileCount int64
}

// Type pill: one row per media_type present, so `all` (the sum) and the
// three buckets are derived in a single scan. media_type excluded (self).
// The source filter applies (author row selection, other dimension).
func (q *Queries) FacetMediaTypeCounts(ctx context.Context, arg FacetMediaTypeCountsParams) ([]FacetMediaTypeCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, facetMediaTypeCounts,
		arg.IncludeCos,
		arg.CosOnly,
		arg.CharactersJson,
		arg.CosWork,
		arg.Source,
		arg.SourceIsOther,
		arg.AuthorID,
		arg.QJson,
		arg.FavoriteSubset,
		arg.HistorySubset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetMediaTypeCountsRow
	for rows.Next() {
		var i FacetMediaTypeCountsRow
		if err := rows.Scan(&i.MediaType, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facetPartitionCounts = `-- name: FacetPartitionCounts :one

SELECT
    COUNT(*) AS all_count,
    COALESCE(SUM(CASE WHEN EXISTS (
        SELECT 1 FROM asset_authors aac
        JOIN authors auc ON auc.id = aac.author_id
        WHERE aac.asset_id = a.asset_id AND auc.type = 'cos')
        THEN 1 ELSE 0 END), 0) AS cos_count
FROM assets a
WHERE
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
    AND (?1 IS NULL OR a.media_type = ?1)
    AND (?2 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?2) c
        WHERE NOT EXISTS (
            SELECT 1 FROM asset_characters ac
            WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
    AND (?3 IS NULL OR a.cos_work = ?3)
    AND (?4 IS NULL
         OR (?5 = 1 AND a.source IS NULL
             AND NOT EXISTS (
                 SELECT 1 FROM asset_authors aaoth
                 JOIN authors auoth ON auoth.id = aaoth.author_id
                 WHERE aaoth.asset_id = a.asset_id AND auoth.type = 'cos'))
         OR a.source = ?4)
    AND (?6 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?6))
    AND (?7 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?7) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
    -- subset constraints: favorite=1 -> only favorited assets; history=1
    -- -> only assets with a kind='open' view event (see file header).
    AND (?8 = 0 OR EXISTS (
        SELECT 1 FROM favorites fvs WHERE fvs.asset_id = a.asset_id))
    AND (?9 = 0 OR EXISTS (
        SELECT 1 FROM view_events veh
        WHERE veh.asset_id = a.asset_id AND veh.kind = 'open'))
`

type FacetPartitionCountsParams struct {
	MediaType      interface{}
	CharactersJson interface{}
	CosWork        interface{}
	Source         interface{}
	SourceIsOther  interface{}
	AuthorID       interface{}
	QJson          interface{}
	FavoriteSubset interface{}
	HistorySubset  interface{}
}

type FacetPartitionCountsRow struct {
	AllCount int64
	CosCount interface{}
}

// facets.sql: album pill-bar aggregations for GET /api/v1/assets/facets.
// Four dimensions (partition / author / character / type) following the
// old Android app's four-row pill bar ("all" page: partition / work /
// character / type, LEGACY_REQUIREMENTS + user decision 2026-09-03):
//   - the "author" row is the old app's WORK row: regular files grouped
//     by SOURCE + COS files grouped by COS AUTHOR, merged per partition
//     (regular = sources only, cos = cos authors only, all = both);
//   - the "character" row merges regular characters and COS works in the
//     all partition (regular / cos keep their single-kind candidates).
//
// ASCII-only comments; see browse.sql header for the sqlc v1.31.1 parser
// rules this file obeys (bare sqlc.arg, no CTE aliases in WHERE, parameter
// only inside WHEN comparisons).
//
// ============ Counting rule: exclude-self ============
// Every query counts its own dimension while IGNORING that dimension's
// current selection, and applies every OTHER dimension. This is standard
// faceted-search behavior and is what the old app's merged pill rows
// produced, generalized to freely order-independent selection.
//
//	FacetPartitionCounts  -> applies media_type/character/work/source/q
//	FacetSourceCounts     -> applies media_type/character/work/source/
//	                          author_id/q (protocol 2026-09-09: source
//	                          and authorId are plain narrowing keys for
//	                          EVERY row now -- the author-collection page
//	                          passes a FIXED authorId to scope its work-
//	                          row candidates; exclude-self is client-side,
//	                          callers omit their own dimension's params)
//	FacetAuthorCounts     -> applies partition/media_type/character/work/
//	                          source/author_id/q (same 2026-09-09 change)
//	FacetCharacterCounts  -> applies partition/media_type/author-or-source/q
//	                          (character and work are the SAME row,
//	                          excluded together)
//	FacetCosWorkCounts    -> applies partition/media_type/author-or-source/q
//	                          (character and work are the SAME row,
//	                          excluded together)
//	FacetMediaTypeCounts  -> applies partition/character/work/author-or-source/q
//
// ============ Subset constraints: favorite / history (2026-09-05) ============
// favorite_subset / history_subset are NOT one of the four dimensions.
// When the caller passes favorite=1 / history=1, EVERY query here (the
// partition pill included) narrows its counting scope to favorited
// assets / assets having a kind='open' view event respectively (same
// shapes as the browse favorite predicate and the history anchor). The
// handler always passes 0/1 (plain arg, no three-valued logic); the
// subquery aliases fvs/veh are file-unique. No exclude-self interaction:
// they are not a dimension, so nothing is excluded on their account.
//
// ============ Shared predicate shapes ============
// The COS partition predicate is byte-identical in shape to browse.sql
// (include_cos / cos_only two-flag form) so both files stay reviewable
// side by side; the httpapi layer maps the `partition` enum onto the two
// flags (all -> 1/0, regular -> 0/0, cos -> 0/1). THESE COPIES MUST STAY
// IDENTICAL TO EACH OTHER AND TO browse.sql.
// The source predicate is likewise copied verbatim from browse.sql
// (source_is_other = the user-facing OTHER bucket: NULL source AND not
// cos-linked -- cos assets never enter the source system, enrich.go).
// The q predicate is likewise copied verbatim from browse.sql (FTS
// instr/lower substring AND-combination over a JSON keyword array).
// Partition pill is reported in full (it excludes itself), so the two
// branches are computed in one pass: regular = all_count - cos_count.
func (q *Queries) FacetPartitionCounts(ctx context.Context, arg FacetPartitionCountsParams) (FacetPartitionCountsRow, error) {
	row := q.db.QueryRowContext(ctx, facetPartitionCounts,
		arg.MediaType,
		arg.CharactersJson,
		arg.CosWork,
		arg.Source,
		arg.SourceIsOther,
		arg.AuthorID,
		arg.QJson,
		arg.FavoriteSubset,
		arg.HistorySubset,
	)
	var i FacetPartitionCountsRow
	err := row.Scan(&i.AllCount, &i.CosCount)
	return i, err
}

const facetSourceCounts = `-- name: FacetSourceCounts :many
SELECT a.source AS source_name,
       COUNT(*) AS file_count
FROM assets a
WHERE
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
    AND NOT EXISTS (
        SELECT 1 FROM asset_authors aas
        JOIN authors aus ON aus.id = aas.author_id
        WHERE aas.asset_id = a.asset_id AND aus.type = 'cos')
    AND (?1 IS NULL OR a.media_type = ?1)
    AND (?2 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?2) c
        WHERE NOT EXISTS (
            SELECT 1 FROM asset_characters ac
            WHERE ac.asset_id = a.asset_id AND ac.character_name = c.value)))
    AND (?3 IS NULL OR a.cos_work = ?3)
    AND ((?4 IS NULL AND ?5 = 0)
         OR (?5 = 1 AND a.source IS NULL
             AND NOT EXISTS (
                 SELECT 1 FROM asset_authors aaoth
                 JOIN authors auoth ON auoth.id = aaoth.author_id
                 WHERE aaoth.asset_id = a.asset_id AND auoth.type = 'cos'))
         OR a.source = ?4)
    AND (?6 IS NULL OR EXISTS (
        SELECT 1 FROM asset_authors aa2
        WHERE aa2.asset_id = a.asset_id AND aa2.author_id = ?6))
    AND (?7 IS NULL OR NOT EXISTS (
        SELECT 1 FROM json_each(?7) qk
        WHERE NOT EXISTS (
            SELECT 1 FROM assets_fts f
            WHERE f.rowid = a.rowid
              AND instr(lower(f.all_text), lower(qk.value)) > 0)))
    -- subset constraints (see file header): same two predicates as every
    -- other query in this file.
    AND (?8 = 0 OR EXISTS (
        SELECT 1 FROM favorites fvs WHERE fvs.asset_id = a.asset_id))
    AND (?9 = 0 OR EXISTS (
        SELECT 1 FROM view_events veh
        WHERE veh.asset_id = a.asset_id AND veh.kind = 'open'))
GROUP BY a.source
ORDER BY file_count DESC, a.source
`

type FacetSourceCountsParams struct {
	MediaType      interface{}
	CharactersJson interface{}
	CosWork        interface{}
	Source         interface{}
	SourceIsOther  interface{}
	AuthorID       interface{}
	QJson          interface{}
	FavoriteSubset interface{}
	HistorySubset  interface{}
}

type FacetSourceCountsRow struct {
	SourceName sql.NullString
	FileCount  int64
}

// Author-row SOURCE buckets: regular (non-cos-linked) assets grouped by
// the matcher's canonical source. The old app's groupBySource filtered
// !isCosFile before grouping; the NULL-source group is the user-facing
// OTHER bucket and IS returned (as a NULL row -- the handler labels it).
// source / source_is_other / author_id apply as plain narrowing keys
// (protocol 2026-09-09: fixed-author collections pass authorId here to
// scope the row; exclude-self is client-side -- album callers omit both
// params when asking for this row).
func (q *Queries) FacetSourceCounts(ctx context.Context, arg FacetSourceCountsParams) ([]FacetSourceCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, facetSourceCounts,
		arg.MediaType,
		arg.CharactersJson,
		arg.CosWork,
		arg.Source,
		arg.SourceIsOther,
		arg.AuthorID,
		arg.QJson,
		arg.FavoriteSubset,
		arg.HistorySubset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FacetSourceCountsRow
	for rows.Next() {
		var i FacetSourceCountsRow
		if err := rows.Scan(&i.SourceName, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
