// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :execrows


INSERT INTO favorites (asset_id, created_at) VALUES (?, ?)
ON CONFLICT (asset_id) DO NOTHING
`

type AddFavoriteParams struct {
	AssetID   string
	CreatedAt string
}

// favorites queries (DOMAIN_RULES 7: a boolean set).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
//
// Toggle semantics (SQLite has no single-statement atomic toggle):
//
//	inside one transaction, call RemoveFavorite first:
//	  rows == 1 -> was favorited, now removed, done;
//	  rows == 0 -> was not favorited, call AddFavorite, done.
//
// AddFavorite: ON CONFLICT DO NOTHING -- idempotent; 0 affected rows
// means it was already favorited.
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addFavorite, arg.AssetID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const isFavorite = `-- name: IsFavorite :one

SELECT COUNT(*) FROM favorites WHERE asset_id = ?
`

// IsFavorite: returns 0/1.
func (q *Queries) IsFavorite(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isFavorite, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removeFavorite = `-- name: RemoveFavorite :execrows

DELETE FROM favorites WHERE asset_id = ?
`

// RemoveFavorite: removing a non-favorite is not an error; 0 affected
// rows means it was not favorited.
func (q *Queries) RemoveFavorite(ctx context.Context, assetID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeFavorite, assetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
