// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy_import.sql

package db

import (
	"context"
)

const importAddAssetAuthor = `-- name: ImportAddAssetAuthor :exec
INSERT INTO asset_authors (asset_id, author_id)
VALUES (?, ?)
ON CONFLICT (asset_id, author_id) DO NOTHING
`

type ImportAddAssetAuthorParams struct {
	AssetID  string
	AuthorID string
}

// Idempotent many-to-many link (PK asset_id+author_id in 0001).
func (q *Queries) ImportAddAssetAuthor(ctx context.Context, arg ImportAddAssetAuthorParams) error {
	_, err := q.db.ExecContext(ctx, importAddAssetAuthor, arg.AssetID, arg.AuthorID)
	return err
}

const importAddAssetTag = `-- name: ImportAddAssetTag :exec
INSERT INTO asset_tags (asset_id, tag_id, created_at) VALUES (?, ?, ?)
ON CONFLICT (asset_id, tag_id) DO NOTHING
`

type ImportAddAssetTagParams struct {
	AssetID   string
	TagID     string
	CreatedAt string
}

// Idempotent tag-ref import (S10 "associations upsert by unique key"):
// the business AddAssetTag is a strict INSERT (runtime replace semantics),
// re-importing the same backup batch must not fail on the
// (asset_id, tag_id) PK. First association's created_at wins on re-import.
func (q *Queries) ImportAddAssetTag(ctx context.Context, arg ImportAddAssetTagParams) error {
	_, err := q.db.ExecContext(ctx, importAddAssetTag, arg.AssetID, arg.TagID, arg.CreatedAt)
	return err
}

const importAddLike = `-- name: ImportAddLike :exec
INSERT INTO likes (asset_id, day, created_at) VALUES (?, ?, ?)
ON CONFLICT (asset_id, day) DO NOTHING
`

type ImportAddLikeParams struct {
	AssetID   string
	Day       string
	CreatedAt string
}

// Idempotent like import: re-importing the same batch must not fail on
// the (asset_id, day) PK (S10 idempotency); business toggle path keeps
// its strict INSERT in likes.sql.
func (q *Queries) ImportAddLike(ctx context.Context, arg ImportAddLikeParams) error {
	_, err := q.db.ExecContext(ctx, importAddLike, arg.AssetID, arg.Day, arg.CreatedAt)
	return err
}

const importInsertTimelineTag = `-- name: ImportInsertTimelineTag :exec
INSERT INTO timeline_tags (id, asset_id, time_millis, name, created_at)
SELECT ?, ?, ?, ?, ?
WHERE NOT EXISTS (
    SELECT 1 FROM timeline_tags t
    WHERE t.asset_id = ? AND t.time_millis = ? AND t.name = ?
)
`

type ImportInsertTimelineTagParams struct {
	ID           string
	AssetID      string
	TimeMillis   int64
	Name         string
	CreatedAt    string
	AssetID_2    string
	TimeMillis_2 int64
	Name_2       string
}

// Idempotent timeline-tag import: content-level dedupe on
// (asset_id, time_millis, name) -- business path re-inserts with fresh
// uuid by design (replace semantics), import must not duplicate rows.
func (q *Queries) ImportInsertTimelineTag(ctx context.Context, arg ImportInsertTimelineTagParams) error {
	_, err := q.db.ExecContext(ctx, importInsertTimelineTag,
		arg.ID,
		arg.AssetID,
		arg.TimeMillis,
		arg.Name,
		arg.CreatedAt,
		arg.AssetID_2,
		arg.TimeMillis_2,
		arg.Name_2,
	)
	return err
}

const importMarkAuthorFollowed = `-- name: ImportMarkAuthorFollowed :execrows
UPDATE authors SET followed = 1 WHERE id = ?
`

// Mark followed (S6 boolean); 0 rows affected = unknown authorId,
// caller counts it into warnings.
func (q *Queries) ImportMarkAuthorFollowed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, importMarkAuthorFollowed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const importUpsertAuthor = `-- name: ImportUpsertAuthor :exec
INSERT INTO authors (id, display_name, type, followed, created_at)
VALUES (?, ?, ?, 0, ?)
ON CONFLICT(id) DO UPDATE SET display_name = excluded.display_name
`

type ImportUpsertAuthorParams struct {
	ID          string
	DisplayName string
	Type        string
	CreatedAt   string
}

// Upsert by legacy authorId (cos_ prefix preserved as-is, S10); id is
// the legacy identity, so re-import never duplicates. type derives from
// the cos_ prefix (0001 CHECK regular|cos).
func (q *Queries) ImportUpsertAuthor(ctx context.Context, arg ImportUpsertAuthorParams) error {
	_, err := q.db.ExecContext(ctx, importUpsertAuthor,
		arg.ID,
		arg.DisplayName,
		arg.Type,
		arg.CreatedAt,
	)
	return err
}

const listAssetsByFileName = `-- name: ListAssetsByFileName :many

SELECT asset_id, library_id, rel_path, file_name
FROM assets
WHERE file_name = ?
ORDER BY created_at
`

type ListAssetsByFileNameRow struct {
	AssetID   string
	LibraryID string
	RelPath   string
	FileName  string
}

// legacy_import.sql: one-shot import channel for qimeng_backup.json
// (DOMAIN_RULES S10 mapping). Kept separate from business queries so the
// migration semantics (idempotent upsert by legacy id) never mix with
// runtime creation paths (uuid ids). Author writes here are named
// Import* on purpose: the business-side authors.sql (M3 author system)
// owns differently-named queries for the same tables.
// Match legacy files to in-library assets by exact file name (S10).
// Multiple hits (same name in several folders) are disambiguated in Go
// by rel_path directory segment == legacy folderName.
func (q *Queries) ListAssetsByFileName(ctx context.Context, fileName string) ([]ListAssetsByFileNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByFileName, fileName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsByFileNameRow
	for rows.Next() {
		var i ListAssetsByFileNameRow
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
