// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package db

import (
	"context"
)

const createLibrary = `-- name: CreateLibrary :one

INSERT INTO libraries (id, name, root_path, kind, created_at) VALUES (?, ?, ?, ?, ?)
RETURNING id, name, root_path, created_at, kind
`

type CreateLibraryParams struct {
	ID        string
	Name      string
	RootPath  string
	Kind      string
	CreatedAt string
}

// libraries queries (M1 minimal set: full CRUD -- libraries are
// low-frequency admin operations).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, createLibrary,
		arg.ID,
		arg.Name,
		arg.RootPath,
		arg.Kind,
		arg.CreatedAt,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec

DELETE FROM libraries WHERE id = ?
`

// DeleteLibrary: cascades to all assets of this library
// (assets.library_id ON DELETE CASCADE). Media files themselves are NOT
// touched here -- deletion goes through the trash flow (filing module).
func (q *Queries) DeleteLibrary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, root_path, created_at, kind FROM libraries WHERE id = ?
`

func (q *Queries) GetLibrary(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, root_path, created_at, kind FROM libraries ORDER BY created_at DESC
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RootPath,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrary = `-- name: UpdateLibrary :one

UPDATE libraries SET name = ?, root_path = ? WHERE id = ?
RETURNING id, name, root_path, created_at, kind
`

type UpdateLibraryParams struct {
	Name     string
	RootPath string
	ID       string
}

// UpdateLibrary: rename / change root. Changing the root is an admin
// operation: rel_path of assets is unchanged, the scanner recomputes
// absolute paths from the new root.
func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, updateLibrary, arg.Name, arg.RootPath, arg.ID)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}
