// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package db

import (
	"context"
)

const addLike = `-- name: AddLike :exec


INSERT INTO likes (asset_id, day, created_at) VALUES (?, ?, ?)
`

type AddLikeParams struct {
	AssetID   string
	Day       string
	CreatedAt string
}

// likes queries (DOMAIN_RULES 5: one like per asset per day, resets
// next day, lifetime total kept forever).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
// AddLike: plain INSERT -- a second row for the same (asset_id, day) is
// rejected by PRIMARY KEY (asset_id, day): the "once per day" rule is
// enforced at the database layer, so concurrency/retry double-clicks
// cannot double-count. Check HasLikedOnDay before writing.
func (q *Queries) AddLike(ctx context.Context, arg AddLikeParams) error {
	_, err := q.db.ExecContext(ctx, addLike, arg.AssetID, arg.Day, arg.CreatedAt)
	return err
}

const countAssetLikes = `-- name: CountAssetLikes :one

SELECT COUNT(*) FROM likes WHERE asset_id = ?
`

// CountAssetLikes: lifetime like count (all history rows).
func (q *Queries) CountAssetLikes(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetLikes, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasLikedOnDay = `-- name: HasLikedOnDay :one

SELECT COUNT(*) FROM likes WHERE asset_id = ? AND day = ?
`

type HasLikedOnDayParams struct {
	AssetID string
	Day     string
}

// HasLikedOnDay: today's like status (0/1). day is YYYY-MM-DD in the
// server's local timezone (see migration header "day" convention).
func (q *Queries) HasLikedOnDay(ctx context.Context, arg HasLikedOnDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasLikedOnDay, arg.AssetID, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listLikedTodayForAssets = `-- name: ListLikedTodayForAssets :many
SELECT DISTINCT asset_id FROM likes
WHERE day = ? AND asset_id IN (SELECT value FROM json_each(?2))
`

type ListLikedTodayForAssetsParams struct {
	Day          string
	AssetIdsJson interface{}
}

// ListLikedTodayForAssets: batch form of HasLikedOnDay for list pages --
// the asset_ids among the given set that already have a like row on the
// given day. Same table and same day convention as HasLikedOnDay
// (day is YYYY-MM-DD in the server's local timezone). asset_ids_json is
// a JSON array consumed by json_each -- same parameter shape as
// ListAuthorNamesForAssets (see browse.sql header for the sqlc parser
// constraints that dictate it).
func (q *Queries) ListLikedTodayForAssets(ctx context.Context, arg ListLikedTodayForAssetsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLikedTodayForAssets, arg.Day, arg.AssetIdsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
