// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package db

import (
	"context"
)

const addLikeOnDayIdempotent = `-- name: AddLikeOnDayIdempotent :execrows


INSERT INTO likes (asset_id, day, created_at) VALUES (?, ?, ?)
ON CONFLICT (asset_id, day) DO NOTHING
`

type AddLikeOnDayIdempotentParams struct {
	AssetID   string
	Day       string
	CreatedAt string
}

// likes queries (DOMAIN_RULES 5: one like per asset per day, resets
// next day, lifetime total kept forever).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
// AddLikeOnDayIdempotent: ON CONFLICT DO NOTHING insert (audit R10,
// 2026-09-20). The old strict INSERT turned a concurrent double-click
// (both pass HasLikedOnDay=0) into a spurious 500 for the loser: the
// PK (asset_id, day) rejection now resolves as a 0-row write instead;
// rows==0 tells the caller the race was lost ("already liked by the
// winner") and the LikeState math reports liked=true. The "once per
// day" rule stays enforced at the database layer -- a lost race can
// never double-count.
func (q *Queries) AddLikeOnDayIdempotent(ctx context.Context, arg AddLikeOnDayIdempotentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addLikeOnDayIdempotent, arg.AssetID, arg.Day, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAssetLikes = `-- name: CountAssetLikes :one

SELECT COUNT(*) FROM likes WHERE asset_id = ?
`

// CountAssetLikes: lifetime like count (all history rows).
func (q *Queries) CountAssetLikes(ctx context.Context, assetID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetLikes, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasLikedOnDay = `-- name: HasLikedOnDay :one

SELECT COUNT(*) FROM likes WHERE asset_id = ? AND day = ?
`

type HasLikedOnDayParams struct {
	AssetID string
	Day     string
}

// HasLikedOnDay: today's like status (0/1). day is YYYY-MM-DD in the
// server's local timezone (see migration header "day" convention).
func (q *Queries) HasLikedOnDay(ctx context.Context, arg HasLikedOnDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasLikedOnDay, arg.AssetID, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listLikedTodayForAssets = `-- name: ListLikedTodayForAssets :many
SELECT DISTINCT asset_id FROM likes
WHERE day = ? AND asset_id IN (SELECT value FROM json_each(?2))
`

type ListLikedTodayForAssetsParams struct {
	Day          string
	AssetIdsJson interface{}
}

// ListLikedTodayForAssets: batch form of HasLikedOnDay for list pages --
// the asset_ids among the given set that already have a like row on the
// given day. Same table and same day convention as HasLikedOnDay
// (day is YYYY-MM-DD in the server's local timezone). asset_ids_json is
// a JSON array consumed by json_each -- same parameter shape as
// ListAuthorNamesForAssets (see browse.sql header for the sqlc parser
// constraints that dictate it).
func (q *Queries) ListLikedTodayForAssets(ctx context.Context, arg ListLikedTodayForAssetsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLikedTodayForAssets, arg.Day, arg.AssetIdsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
