// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Asset struct {
	AssetID             string
	LibraryID           string
	RelPath             string
	FileName            string
	MediaType           string
	SizeBytes           int64
	Mtime               string
	DurationMs          sql.NullInt64
	Width               sql.NullInt64
	Height              sql.NullInt64
	Source              sql.NullString
	CreatedAt           string
	UpdatedAt           string
	LastPositionSeconds sql.NullFloat64
	VideoCodec          sql.NullString
	AudioCodec          sql.NullString
	CosWork             sql.NullString
}

type AssetAuthor struct {
	AssetID  string
	AuthorID string
}

type AssetCharacter struct {
	AssetID       string
	CharacterName string
}

type AssetDailyStat struct {
	AssetID       string
	Day           string
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds int64
}

type AssetSearchText struct {
	AssetID string
	AllText interface{}
}

type AssetTag struct {
	AssetID   string
	TagID     string
	CreatedAt string
}

type AssetsFt struct {
	AllText string
	AssetID string
}

type AuthSession struct {
	ID          string
	UserID      string
	TokenHash   string
	DeviceLabel string
	CreatedAt   string
}

type Author struct {
	ID          string
	DisplayName string
	Type        string
	CreatedAt   string
	Followed    int64
}

type DailyShown struct {
	AssetID string
	Day     string
	Count   int64
}

type Favorite struct {
	AssetID   string
	CreatedAt string
}

type KvSetting struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Library struct {
	ID        string
	Name      string
	RootPath  string
	CreatedAt string
	Kind      string
	Enabled   int64
}

type Like struct {
	AssetID   string
	Day       string
	CreatedAt string
}

type Tag struct {
	ID        string
	Name      string
	CreatedAt string
}

type TimelineTag struct {
	ID         string
	AssetID    string
	TimeMillis int64
	Name       string
	CreatedAt  string
	Color      string
}

type TrashItem struct {
	ID           string
	OriginalPath string
	FileName     string
	SizeBytes    int64
	DeletedAt    string
	ExpiresAt    string
	MetadataJson string
}

type User struct {
	ID           string
	Name         string
	PasswordHash string
	Role         string
	TokenHash    string
	CreatedAt    string
}

type ViewEvent struct {
	ID            int64
	AssetID       string
	Kind          string
	SessionID     string
	StartedAt     string
	Seconds       sql.NullInt64
	ClientEventID sql.NullString
}
