// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Asset struct {
	AssetID    string
	LibraryID  string
	RelPath    string
	FileName   string
	MediaType  string
	SizeBytes  int64
	Mtime      string
	DurationMs sql.NullInt64
	Width      sql.NullInt64
	Height     sql.NullInt64
	Source     sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

type AssetAuthor struct {
	AssetID  string
	AuthorID string
}

type AssetCharacter struct {
	AssetID       string
	CharacterName string
}

type AssetTag struct {
	AssetID string
	TagID   string
}

type Author struct {
	ID          string
	DisplayName string
	Type        string
	CreatedAt   string
}

type DailyShown struct {
	AssetID string
	Day     string
	Count   int64
}

type Favorite struct {
	AssetID   string
	CreatedAt string
}

type Library struct {
	ID        string
	Name      string
	RootPath  string
	CreatedAt string
}

type Like struct {
	AssetID   string
	Day       string
	CreatedAt string
}

type Tag struct {
	ID        string
	Name      string
	CreatedAt string
}

type TimelineTag struct {
	ID         string
	AssetID    string
	TimeMillis int64
	Name       string
	CreatedAt  string
}

type TrashItem struct {
	ID           string
	OriginalPath string
	FileName     string
	SizeBytes    int64
	DeletedAt    string
	ExpiresAt    string
	MetadataJson string
}

type User struct {
	ID           string
	Name         string
	PasswordHash string
	Role         string
	TokenHash    string
	CreatedAt    string
}

type ViewEvent struct {
	ID        int64
	AssetID   string
	Kind      string
	SessionID string
	StartedAt string
	Seconds   sql.NullInt64
}
