// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommend.sql

package db

import (
	"context"
	"database/sql"
)

const countWindowedLikes = `-- name: CountWindowedLikes :many
SELECT likes.asset_id AS asset_id,
       CAST(COUNT(*) AS INTEGER) AS like_count
FROM likes
WHERE likes.day >= ?1
GROUP BY likes.asset_id
`

type CountWindowedLikesRow struct {
	AssetID   string
	LikeCount int64
}

// CountWindowedLikes: per-asset window like counts. likes is keyed
// (asset_id, day) (one like per asset per day, DOMAIN_RULES 5), so the
// table has native day granularity -- window likes = row count with
// day >= fromDay.
func (q *Queries) CountWindowedLikes(ctx context.Context, fromDay string) ([]CountWindowedLikesRow, error) {
	rows, err := q.db.QueryContext(ctx, countWindowedLikes, fromDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountWindowedLikesRow
	for rows.Next() {
		var i CountWindowedLikesRow
		if err := rows.Scan(&i.AssetID, &i.LikeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsRecommendInput = `-- name: ListAssetsRecommendInput :many

SELECT
    a.asset_id, a.library_id, a.rel_path, a.file_name, a.media_type,
    a.size_bytes, a.mtime, a.duration_ms, a.source, a.created_at,
    EXISTS(SELECT 1 FROM favorites fv WHERE fv.asset_id = a.asset_id) AS is_favorite,
    (SELECT COUNT(*) FROM likes l WHERE l.asset_id = a.asset_id) AS like_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'open') AS view_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'play') AS play_count,
    (SELECT COALESCE(SUM(v.seconds), 0) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'dwell') AS browse_seconds,
    (SELECT MAX(v.started_at) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'open') AS last_viewed_at,
    -- Column refs (ds.count) with a zero-row FROM return an EMPTY result
    -- set -> NULL in expression context; COALESCE outside the zero-row
    -- select is not executed. Nest the row pick inside COALESCE:
    -- zero rows -> inner select yields NULL -> 0. (SUM works without the
    -- nesting because aggregates always produce one row.)
    (SELECT COALESCE((SELECT ds.count FROM daily_shown ds
        WHERE ds.asset_id = a.asset_id AND ds.day = ?1), 0)) AS shown_today
FROM assets a
WHERE
    -- library kill-switch: disabled libraries vanish from browse/search/
    -- recommend lists; all records are kept (migration 0007, adr/0012)
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
    AND (?2 IS NULL OR a.media_type = ?2)
    -- COS isolation vs COS-only mode (DOMAIN_RULES 6): cos_only = 0 keeps
    -- the historical regular-stream exclusion (COS never enters regular
    -- streams); cos_only = 1 restricts candidates to COS-linked assets
    -- (home cos tab = legacy "COS recommend mode": same scoring, same
    -- daily-shown penalty). Two explicit branches keep the param strictly
    -- 0/1 two-valued (no NULL three-valued-logic rows) -- same shape as
    -- the browse partition predicate in browse.sql. Handler must always
    -- pass 0 or 1 (never NULL).
    AND ((?3 = 1 AND EXISTS (
              SELECT 1 FROM asset_authors aacos
              JOIN authors aucos ON aucos.id = aacos.author_id
              WHERE aacos.asset_id = a.asset_id AND aucos.type = 'cos'))
         OR (?3 = 0 AND NOT EXISTS (
              SELECT 1 FROM asset_authors aa
              JOIN authors au ON au.id = aa.author_id
              WHERE aa.asset_id = a.asset_id AND au.type = 'cos')))
ORDER BY a.asset_id
`

type ListAssetsRecommendInputParams struct {
	Day       string
	MediaType interface{}
	CosOnly   interface{}
}

type ListAssetsRecommendInputRow struct {
	AssetID       string
	LibraryID     string
	RelPath       string
	FileName      string
	MediaType     string
	SizeBytes     int64
	Mtime         string
	DurationMs    sql.NullInt64
	Source        sql.NullString
	CreatedAt     string
	IsFavorite    bool
	LikeCount     int64
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds interface{}
	LastViewedAt  interface{}
	ShownToday    interface{}
}

// recommend queries: one row per asset with the aggregates the
// recommendation algorithm (DOMAIN_RULES 1) consumes.
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug). Chinese explanations live in
// migrations/0001_init.up.sql and docs/DOMAIN_RULES.md.
//
// Why one row per asset instead of joins: SQLite aggregation fan-out
// (likes x view_events x daily_shown) would multiply rows; scalar
// subqueries keep the row count == asset count (single-level pattern,
// see browse.sql header rule 3).
//
// last_viewed_at is MAX(started_at) of kind='open' -> NULL when the
// asset was never opened; the algorithm maps NULL to the recency
// default 0.3 (DOMAIN_RULES 1.1).
func (q *Queries) ListAssetsRecommendInput(ctx context.Context, arg ListAssetsRecommendInputParams) ([]ListAssetsRecommendInputRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsRecommendInput, arg.Day, arg.MediaType, arg.CosOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRecommendInputRow
	for rows.Next() {
		var i ListAssetsRecommendInputRow
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.DurationMs,
			&i.Source,
			&i.CreatedAt,
			&i.IsFavorite,
			&i.LikeCount,
			&i.ViewCount,
			&i.PlayCount,
			&i.BrowseSeconds,
			&i.LastViewedAt,
			&i.ShownToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumWindowedDailyStats = `-- name: SumWindowedDailyStats :many

SELECT asset_daily_stats.asset_id AS asset_id,
       CAST(SUM(asset_daily_stats.view_count) AS INTEGER) AS view_count,
       CAST(SUM(asset_daily_stats.play_count) AS INTEGER) AS play_count
FROM asset_daily_stats
WHERE asset_daily_stats.day >= ?1
GROUP BY asset_daily_stats.asset_id
`

type SumWindowedDailyStatsRow struct {
	AssetID   string
	ViewCount int64
	PlayCount int64
}

// Windowed ranking heat inputs (DOMAIN_RULES 2, 2026-09-18): period
// rankings aggregate per-day data inside the window instead of lifetime
// totals. Both queries take fromDay = local calendar day (YYYY-MM-DD) of
// now - window; day >= fromDay includes the whole cutoff day (day-level
// bucketing is the finest granularity the two tables have).
//
// Rows are keyed by asset_id only; the rankings handler joins them to the
// already library/COS-filtered ListAssetsRecommendInput rows in Go, so
// extra rows (COS-linked or disabled-library assets) are simply never
// looked up. Assets without any window activity simply have no row
// (zero heat -> excluded from period boards by the admission rule).
// SumWindowedDailyStats: per-asset window sums from the "asset x day"
// materialized table (cache of the view_events stream; DOMAIN_RULES 5).
func (q *Queries) SumWindowedDailyStats(ctx context.Context, fromDay string) ([]SumWindowedDailyStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, sumWindowedDailyStats, fromDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumWindowedDailyStatsRow
	for rows.Next() {
		var i SumWindowedDailyStatsRow
		if err := rows.Scan(&i.AssetID, &i.ViewCount, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
