// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommend.sql

package db

import (
	"context"
	"database/sql"
)

const listAssetsRecommendInput = `-- name: ListAssetsRecommendInput :many

SELECT
    a.asset_id, a.library_id, a.rel_path, a.file_name, a.media_type,
    a.size_bytes, a.mtime, a.source, a.created_at,
    EXISTS(SELECT 1 FROM favorites fv WHERE fv.asset_id = a.asset_id) AS is_favorite,
    (SELECT COUNT(*) FROM likes l WHERE l.asset_id = a.asset_id) AS like_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'open') AS view_count,
    (SELECT COUNT(*) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'play') AS play_count,
    (SELECT COALESCE(SUM(v.seconds), 0) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'dwell') AS browse_seconds,
    (SELECT MAX(v.started_at) FROM view_events v WHERE v.asset_id = a.asset_id AND v.kind = 'open') AS last_viewed_at,
    -- Column refs (ds.count) with a zero-row FROM return an EMPTY result
    -- set -> NULL in expression context; COALESCE outside the zero-row
    -- select is not executed. Nest the row pick inside COALESCE:
    -- zero rows -> inner select yields NULL -> 0. (SUM works without the
    -- nesting because aggregates always produce one row.)
    (SELECT COALESCE((SELECT ds.count FROM daily_shown ds
        WHERE ds.asset_id = a.asset_id AND ds.day = ?1), 0)) AS shown_today
FROM assets a
WHERE
    -- library kill-switch: disabled libraries vanish from browse/search/
    -- recommend lists; all records are kept (migration 0007, adr/0012)
    EXISTS (SELECT 1 FROM libraries le
                WHERE le.id = a.library_id AND le.enabled = 1)
    AND (?2 IS NULL OR a.media_type = ?2)
    -- COS exclusion (DOMAIN_RULES 6: COS files never appear in regular
    -- streams) -- same predicate as ListAssetsFilteredDesc in browse.sql.
    AND NOT EXISTS (
        SELECT 1 FROM asset_authors aa
        JOIN authors au ON au.id = aa.author_id
        WHERE aa.asset_id = a.asset_id AND au.type = 'cos')
ORDER BY a.asset_id
`

type ListAssetsRecommendInputParams struct {
	Day       string
	MediaType interface{}
}

type ListAssetsRecommendInputRow struct {
	AssetID       string
	LibraryID     string
	RelPath       string
	FileName      string
	MediaType     string
	SizeBytes     int64
	Mtime         string
	Source        sql.NullString
	CreatedAt     string
	IsFavorite    bool
	LikeCount     int64
	ViewCount     int64
	PlayCount     int64
	BrowseSeconds interface{}
	LastViewedAt  interface{}
	ShownToday    interface{}
}

// recommend queries: one row per asset with the aggregates the
// recommendation algorithm (DOMAIN_RULES 1) consumes.
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug). Chinese explanations live in
// migrations/0001_init.up.sql and docs/DOMAIN_RULES.md.
//
// Why one row per asset instead of joins: SQLite aggregation fan-out
// (likes x view_events x daily_shown) would multiply rows; scalar
// subqueries keep the row count == asset count (single-level pattern,
// see browse.sql header rule 3).
//
// last_viewed_at is MAX(started_at) of kind='open' -> NULL when the
// asset was never opened; the algorithm maps NULL to the recency
// default 0.3 (DOMAIN_RULES 1.1).
func (q *Queries) ListAssetsRecommendInput(ctx context.Context, arg ListAssetsRecommendInputParams) ([]ListAssetsRecommendInputRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsRecommendInput, arg.Day, arg.MediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRecommendInputRow
	for rows.Next() {
		var i ListAssetsRecommendInputRow
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.Source,
			&i.CreatedAt,
			&i.IsFavorite,
			&i.LikeCount,
			&i.ViewCount,
			&i.PlayCount,
			&i.BrowseSeconds,
			&i.LastViewedAt,
			&i.ShownToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
