// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scanner.sql

package db

import (
	"context"
)

const deleteAsset = `-- name: DeleteAsset :exec

DELETE FROM assets WHERE asset_id = ?
`

// DeleteAsset: removes one asset row. FK ON DELETE CASCADE wipes
// dependent rows (likes/favorites/tags/characters/authors/daily_shown);
// view_events is deliberately FK-free (adr/0005) so the append-only
// history stream survives asset deletion.
func (q *Queries) DeleteAsset(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, assetID)
	return err
}

const listAssetsByLibrary = `-- name: ListAssetsByLibrary :many


SELECT asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at, last_position_seconds, video_codec, audio_codec, cos_work, tag_set_updated_at FROM assets WHERE library_id = ?
`

// scanner queries (M1: full-scan reconciliation -- diff / move-merge / delete).
// ASCII-only comments here; see assets.sql header note (sqlc v1.31.1
// multi-byte comment parser bug) and migrations/0001_init.up.sql for
// Chinese explanations.
// ListAssetsByLibrary: the scanner's reconciliation source. Loads every
// asset row of one library so the walker can (a) do change detection in
// memory (size+mtime, adr/0004) with zero SQL round-trips per file and
// (b) compute the disappeared-set diff at the end of a scan cycle.
// Why a full load is fine for M1: a home library is tens of thousands
// of rows x ~200 bytes. Revisit (keyset-chunked reads) only past ~1e6.
func (q *Queries) ListAssetsByLibrary(ctx context.Context, libraryID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.LibraryID,
			&i.RelPath,
			&i.FileName,
			&i.MediaType,
			&i.SizeBytes,
			&i.Mtime,
			&i.DurationMs,
			&i.Width,
			&i.Height,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPositionSeconds,
			&i.VideoCodec,
			&i.AudioCodec,
			&i.CosWork,
			&i.TagSetUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryRelinkSamples = `-- name: ListLibraryRelinkSamples :many

SELECT rel_path, size_bytes FROM assets
WHERE library_id = ?
ORDER BY size_bytes ASC
LIMIT ?
`

type ListLibraryRelinkSamplesParams struct {
	LibraryID string
	Limit     int64
}

type ListLibraryRelinkSamplesRow struct {
	RelPath   string
	SizeBytes int64
}

// ListLibraryRelinkSamples: fingerprint samples for auto-relink (ADR-0025).
// When a library root disappears from disk, the scanner compares a handful
// of known assets (relative path + exact byte size) against candidate
// directories under the old root's parent. Smallest files first: they are
// the cheapest to stat and the most likely to be unique content.
// Row cap is the relinkSampleCount constant in server/internal/scanner.
func (q *Queries) ListLibraryRelinkSamples(ctx context.Context, arg ListLibraryRelinkSamplesParams) ([]ListLibraryRelinkSamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryRelinkSamples, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibraryRelinkSamplesRow
	for rows.Next() {
		var i ListLibraryRelinkSamplesRow
		if err := rows.Scan(&i.RelPath, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAssetPath = `-- name: MoveAssetPath :one

UPDATE assets
SET rel_path = ?, file_name = ?, updated_at = ?
WHERE asset_id = ?
RETURNING asset_id, library_id, rel_path, file_name, media_type, size_bytes, mtime, duration_ms, width, height, source, created_at, updated_at, last_position_seconds, video_codec, audio_codec, cos_work, tag_set_updated_at
`

type MoveAssetPathParams struct {
	RelPath   string
	FileName  string
	UpdatedAt string
	AssetID   string
}

// MoveAssetPath: the move-merge write (adr/0004). Identity
// (asset_id / created_at) is untouched; only the path attribute moves.
// size/mtime are NOT rewritten here: the merge precondition is size and
// mtime being IDENTICAL between the gone row and the new row, so the
// stored values already describe the file at its new location.
// Caller must first free the target (library_id, rel_path) unique
// index entry (delete the freshly inserted row), otherwise the UPDATE
// violates the unique constraint.
func (q *Queries) MoveAssetPath(ctx context.Context, arg MoveAssetPathParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, moveAssetPath,
		arg.RelPath,
		arg.FileName,
		arg.UpdatedAt,
		arg.AssetID,
	)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.LibraryID,
		&i.RelPath,
		&i.FileName,
		&i.MediaType,
		&i.SizeBytes,
		&i.Mtime,
		&i.DurationMs,
		&i.Width,
		&i.Height,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPositionSeconds,
		&i.VideoCodec,
		&i.AudioCodec,
		&i.CosWork,
		&i.TagSetUpdatedAt,
	)
	return i, err
}
