// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const countSessionsByUser = `-- name: CountSessionsByUser :one
SELECT COUNT(*) FROM auth_sessions WHERE user_id = ?
`

func (q *Queries) CountSessionsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO auth_sessions (id, user_id, token_hash, device_label, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID          string
	UserID      string
	TokenHash   string
	DeviceLabel string
	CreatedAt   string
}

// sessions queries (multi-device concurrent auth sessions, migration 0011).
// ASCII-only comments here; see assets.sql header note and
// migrations/0011_auth_sessions.up.sql for Chinese explanations.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceLabel,
		arg.CreatedAt,
	)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM auth_sessions WHERE id = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM auth_sessions WHERE token_hash = ?
`

// Logout: revoke exactly the session matching the request token's hash
// (token_hash UNIQUE keeps it to one row).
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const listSessionHashesByUser = `-- name: ListSessionHashesByUser :many
SELECT token_hash FROM auth_sessions WHERE user_id = ?
`

func (q *Queries) ListSessionHashesByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionHashesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token_hash string
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionIDsByUser = `-- name: ListSessionIDsByUser :many
SELECT id FROM auth_sessions WHERE user_id = ? ORDER BY created_at DESC, id
`

// Newest first (created_at DESC, id as tiebreaker because millisecond
// timestamps can collide on rapid dev-login loops). Combined with
// DeleteSessionByID this implements "keep newest N per user" pruning in Go:
// sqlc v1.31.1's SQLite parser rejects the equivalent single DELETE with a
// same-table subquery ("column user_id is ambiguous") and WITH..DELETE
// ("relation does not exist"), so the cap logic lives in registerSessionLocked.
func (q *Queries) ListSessionIDsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionIDsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
