// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one

SELECT value FROM kv_settings WHERE key = ?
`

// settings queries: server-level KV settings (migrations/0003_settings_kv).
// Value semantics live on the reader side (JSON documents, e.g.
// recommend_prefs); this layer is key-value only.
// ASCII-only comments here; see assets.sql header note.
func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO kv_settings (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertSettingParams struct {
	Key       string
	Value     string
	UpdatedAt string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
