// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const addAssetTag = `-- name: AddAssetTag :exec
INSERT INTO asset_tags (asset_id, tag_id, created_at) VALUES (?, ?, ?)
`

type AddAssetTagParams struct {
	AssetID   string
	TagID     string
	CreatedAt string
}

// created_at = association time: the replace-style PUT re-inserts every
// row, so re-adding a tag bumps it to the top of the detail-page list
// (LEGACY_REQUIREMENTS A; column added in 0004).
func (q *Queries) AddAssetTag(ctx context.Context, arg AddAssetTagParams) error {
	_, err := q.db.ExecContext(ctx, addAssetTag, arg.AssetID, arg.TagID, arg.CreatedAt)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, created_at) VALUES (?, ?, ?) RETURNING id, name, created_at
`

type CreateTagParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.ID, arg.Name, arg.CreatedAt)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteAssetTags = `-- name: DeleteAssetTags :exec
DELETE FROM asset_tags WHERE asset_id = ?
`

// "Clear all" half of the replace-style PUT binding (DOMAIN_RULES 7).
func (q *Queries) DeleteAssetTags(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetTags, assetID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteTimelineTag = `-- name: DeleteTimelineTag :execrows
DELETE FROM timeline_tags WHERE id = ? AND asset_id = ?
`

type DeleteTimelineTagParams struct {
	ID      string
	AssetID string
}

// Scoped delete: tagId must belong to the given asset, so a stale
// (assetId, tagId) pair from another asset can never delete a row.
func (q *Queries) DeleteTimelineTag(ctx context.Context, arg DeleteTimelineTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTimelineTag, arg.ID, arg.AssetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const insertTimelineTag = `-- name: InsertTimelineTag :one
INSERT INTO timeline_tags (id, asset_id, time_millis, name, color, created_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, asset_id, time_millis, name, created_at, color
`

type InsertTimelineTagParams struct {
	ID         string
	AssetID    string
	TimeMillis int64
	Name       string
	Color      string
	CreatedAt  string
}

// color = ” means "no color set" (protocol batch P2, 2026-09-09;
// migration 0009 NOT NULL DEFAULT ” sentinel, DOMAIN_RULES 7).
func (q *Queries) InsertTimelineTag(ctx context.Context, arg InsertTimelineTagParams) (TimelineTag, error) {
	row := q.db.QueryRowContext(ctx, insertTimelineTag,
		arg.ID,
		arg.AssetID,
		arg.TimeMillis,
		arg.Name,
		arg.Color,
		arg.CreatedAt,
	)
	var i TimelineTag
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TimeMillis,
		&i.Name,
		&i.CreatedAt,
		&i.Color,
	)
	return i, err
}

const listAllAssetTags = `-- name: ListAllAssetTags :many
SELECT at.asset_id, t.name
FROM asset_tags at
JOIN tags t ON t.id = at.tag_id
ORDER BY at.asset_id, t.name
`

type ListAllAssetTagsRow struct {
	AssetID string
	Name    string
}

// Full-library tag map (asset_id -> tag names) consumed by the
// recommendation algorithm's tag relevance/collection scoring.
func (q *Queries) ListAllAssetTags(ctx context.Context) ([]ListAllAssetTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssetTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAssetTagsRow
	for rows.Next() {
		var i ListAllAssetTagsRow
		if err := rows.Scan(&i.AssetID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetIDsByTag = `-- name: ListAssetIDsByTag :many
SELECT asset_id FROM asset_tags WHERE tag_id = ?
`

// Assets holding the tag, read BEFORE DeleteTag: the FK cascade removes
// asset_tags rows server-side, so after the delete the join is empty and
// the affected set is unrecoverable. Those assets' tag sets changed ->
// each needs a TouchAssetTagSet bump (DOMAIN_RULES 10).
func (q *Queries) ListAssetIDsByTag(ctx context.Context, tagID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAssetIDsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many

SELECT t.id, t.name, COUNT(at.asset_id) AS file_count
FROM tags t
LEFT JOIN asset_tags at ON at.tag_id = t.id
GROUP BY t.id
ORDER BY t.name
`

type ListTagsRow struct {
	ID        string
	Name      string
	FileCount int64
}

// tags.sql: tag pool, asset tag bindings, timeline tags (DOMAIN_RULES 7).
// Cascade semantics via FKs: deleting a tags row clears asset_tags refs;
// deleting an assets row clears bindings and timeline tags (0001_init.up.sql).
// Tag pool + per-tag file count (LEFT JOIN keeps zero-ref tags).
// Order: name ASC -- filter panels and other non-detail scenes use
// name order (LEGACY_REQUIREMENTS A: only the detail-page tag popup
// uses association-time order, which is ListAssetTagRefs in browse.sql).
func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineTags = `-- name: ListTimelineTags :many
SELECT id, asset_id, time_millis, name, created_at, color FROM timeline_tags WHERE asset_id = ?
ORDER BY time_millis, id
`

func (q *Queries) ListTimelineTags(ctx context.Context, assetID string) ([]TimelineTag, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineTags, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineTag
	for rows.Next() {
		var i TimelineTag
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.TimeMillis,
			&i.Name,
			&i.CreatedAt,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssetTagByName = `-- name: RemoveAssetTagByName :execrows
DELETE FROM asset_tags
WHERE asset_id = ?
  AND tag_id = (SELECT id FROM tags WHERE name = ?)
`

type RemoveAssetTagByNameParams struct {
	AssetID string
	Name    string
}

// Per-tag unbinding (protocol batch P2, 2026-09-09): removes ONE
// (asset, tag) association and leaves every other association's
// created_at untouched -- unlike the replace-style PUT which re-inserts
// all rows. Idempotent at the association level: 0 rows affected =
// tag exists but was not attached (caller returns 204 either way;
// tag-name existence is checked by the caller first for a 404).
func (q *Queries) RemoveAssetTagByName(ctx context.Context, arg RemoveAssetTagByNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeAssetTagByName, arg.AssetID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAssetTagSet = `-- name: TouchAssetTagSet :exec
UPDATE assets SET tag_set_updated_at = ? WHERE asset_id = ?
`

type TouchAssetTagSetParams struct {
	TagSetUpdatedAt string
	AssetID         string
}

// Bump the asset's tag-set modification time (migration 0012 column,
// DOMAIN_RULES 10 tag-set sync semantics, 2026-09-20 user decision).
// Called by every asset_tags mutation path: replace-style PUT, single
// unbind, tag-delete cascade (via ListAssetIDsByTag BEFORE the delete),
// and the import's "backup newer" replace -- the last one writes the
// BACKUP's timestamp, not now. ” sentinel (never written) = unknown
// provenance: import falls back to union merge when either side is
// unknown (never fabricate a version for a merged state).
func (q *Queries) TouchAssetTagSet(ctx context.Context, arg TouchAssetTagSetParams) error {
	_, err := q.db.ExecContext(ctx, touchAssetTagSet, arg.TagSetUpdatedAt, arg.AssetID)
	return err
}

const updateTimelineTag = `-- name: UpdateTimelineTag :one
UPDATE timeline_tags
SET time_millis = ?, name = ?, color = ?
WHERE id = ? AND asset_id = ?
RETURNING id, asset_id, time_millis, name, created_at, color
`

type UpdateTimelineTagParams struct {
	TimeMillis int64
	Name       string
	Color      string
	ID         string
	AssetID    string
}

// Full replace of the mutable fields (time/name/color); scoped like the
// delete: tagId must belong to the given asset. 0 rows = unknown
// (assetId, tagId) pair, caller maps that to 404. Empty color clears it.
func (q *Queries) UpdateTimelineTag(ctx context.Context, arg UpdateTimelineTagParams) (TimelineTag, error) {
	row := q.db.QueryRowContext(ctx, updateTimelineTag,
		arg.TimeMillis,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.AssetID,
	)
	var i TimelineTag
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TimeMillis,
		&i.Name,
		&i.CreatedAt,
		&i.Color,
	)
	return i, err
}
