// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const addAssetTag = `-- name: AddAssetTag :exec
INSERT INTO asset_tags (asset_id, tag_id) VALUES (?, ?)
`

type AddAssetTagParams struct {
	AssetID string
	TagID   string
}

func (q *Queries) AddAssetTag(ctx context.Context, arg AddAssetTagParams) error {
	_, err := q.db.ExecContext(ctx, addAssetTag, arg.AssetID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, created_at) VALUES (?, ?, ?) RETURNING id, name, created_at
`

type CreateTagParams struct {
	ID        string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.ID, arg.Name, arg.CreatedAt)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteAssetTags = `-- name: DeleteAssetTags :exec
DELETE FROM asset_tags WHERE asset_id = ?
`

// "Clear all" half of the replace-style PUT binding (DOMAIN_RULES 7).
func (q *Queries) DeleteAssetTags(ctx context.Context, assetID string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetTags, assetID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteTimelineTag = `-- name: DeleteTimelineTag :execrows
DELETE FROM timeline_tags WHERE id = ? AND asset_id = ?
`

type DeleteTimelineTagParams struct {
	ID      string
	AssetID string
}

// Scoped delete: tagId must belong to the given asset, so a stale
// (assetId, tagId) pair from another asset can never delete a row.
func (q *Queries) DeleteTimelineTag(ctx context.Context, arg DeleteTimelineTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTimelineTag, arg.ID, arg.AssetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const insertTimelineTag = `-- name: InsertTimelineTag :one
INSERT INTO timeline_tags (id, asset_id, time_millis, name, created_at)
VALUES (?, ?, ?, ?, ?) RETURNING id, asset_id, time_millis, name, created_at
`

type InsertTimelineTagParams struct {
	ID         string
	AssetID    string
	TimeMillis int64
	Name       string
	CreatedAt  string
}

func (q *Queries) InsertTimelineTag(ctx context.Context, arg InsertTimelineTagParams) (TimelineTag, error) {
	row := q.db.QueryRowContext(ctx, insertTimelineTag,
		arg.ID,
		arg.AssetID,
		arg.TimeMillis,
		arg.Name,
		arg.CreatedAt,
	)
	var i TimelineTag
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.TimeMillis,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many

SELECT t.id, t.name, COUNT(at.asset_id) AS file_count
FROM tags t
LEFT JOIN asset_tags at ON at.tag_id = t.id
GROUP BY t.id
ORDER BY t.created_at, t.id
`

type ListTagsRow struct {
	ID        string
	Name      string
	FileCount int64
}

// tags.sql: tag pool, asset tag bindings, timeline tags (DOMAIN_RULES 7).
// Cascade semantics via FKs: deleting a tags row clears asset_tags refs;
// deleting an assets row clears bindings and timeline tags (0001_init.up.sql).
// Tag pool + per-tag file count (LEFT JOIN keeps zero-ref tags).
func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineTags = `-- name: ListTimelineTags :many
SELECT id, asset_id, time_millis, name, created_at FROM timeline_tags WHERE asset_id = ?
ORDER BY time_millis, id
`

func (q *Queries) ListTimelineTags(ctx context.Context, assetID string) ([]TimelineTag, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineTags, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineTag
	for rows.Next() {
		var i TimelineTag
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.TimeMillis,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
