// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one

SELECT COUNT(*) FROM users
`

// users queries (M1 single-user auth state: first-boot setup + token
// hash verification source).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
//
// The users table is multi-user-shaped on purpose (SECURITY.md); M1
// code only ever touches the FIRST row (created_at ASC).
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, password_hash, role, token_hash, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Name         string
	PasswordHash string
	Role         string
	TokenHash    string
	CreatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT id, name, password_hash, role, token_hash, created_at FROM users ORDER BY created_at LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getFirstUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserTokenHash = `-- name: UpdateUserTokenHash :exec
UPDATE users SET token_hash = ? WHERE id = (SELECT id FROM users ORDER BY created_at LIMIT 1)
`

// Token re-issue on password login: single-user single-token model --
// the new token invalidates the old one by replacing its hash.
func (q *Queries) UpdateUserTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, updateUserTokenHash, tokenHash)
	return err
}
