// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_events.sql

package db

import (
	"context"
	"database/sql"
)

const aggregateAllEventCounts = `-- name: AggregateAllEventCounts :many

SELECT asset_id, kind, COUNT(*) AS cnt
FROM view_events
WHERE kind IN ('open', 'play')
GROUP BY asset_id, kind
`

type AggregateAllEventCountsRow struct {
	AssetID string
	Kind    string
	Cnt     int64
}

// AggregateAllEventCounts: whole-library view/play aggregation --
// the recompute source for daily materialized tables (adr/0005 cache)
// and leaderboard heat. On scoring-rule changes, rerun this query over
// the full history; the event stream itself never changes.
func (q *Queries) AggregateAllEventCounts(ctx context.Context) ([]AggregateAllEventCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, aggregateAllEventCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateAllEventCountsRow
	for rows.Next() {
		var i AggregateAllEventCountsRow
		if err := rows.Scan(&i.AssetID, &i.Kind, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAssetEvents = `-- name: CountAssetEvents :many

SELECT asset_id, kind, COUNT(*) AS cnt
FROM view_events
WHERE asset_id = ? AND kind IN ('open', 'play')
GROUP BY asset_id, kind
`

type CountAssetEventsRow struct {
	AssetID string
	Kind    string
	Cnt     int64
}

// CountAssetEvents: per-asset view/play counts (DOMAIN_RULES 5:
// aggregated from the event stream; dwell is not counted). At most two
// rows per asset (open/play) -- the caller assembles them. Empty result
// means never opened/played, not an error.
func (q *Queries) CountAssetEvents(ctx context.Context, assetID string) ([]CountAssetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, countAssetEvents, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAssetEventsRow
	for rows.Next() {
		var i CountAssetEventsRow
		if err := rows.Scan(&i.AssetID, &i.Kind, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertViewEvent = `-- name: InsertViewEvent :exec


INSERT INTO view_events (asset_id, kind, session_id, started_at, seconds)
VALUES (?, ?, ?, ?, ?)
`

type InsertViewEventParams struct {
	AssetID   string
	Kind      string
	SessionID string
	StartedAt string
	Seconds   sql.NullInt64
}

// view_events queries (adr/0005: append-only, aggregate-only --
// UPDATE/DELETE must never appear in this file).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
// InsertViewEvent: the only write entry point. Session-level dedup
// (one open/play per session, DOMAIN_RULES 5) is decided server-side
// BEFORE the insert; the table has no unique constraint on purpose
// (adr/0005: scoring rules live in one place, not hidden in the schema).
func (q *Queries) InsertViewEvent(ctx context.Context, arg InsertViewEventParams) error {
	_, err := q.db.ExecContext(ctx, insertViewEvent,
		arg.AssetID,
		arg.Kind,
		arg.SessionID,
		arg.StartedAt,
		arg.Seconds,
	)
	return err
}
