// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_events.sql

package db

import (
	"context"
	"database/sql"
)

const aggregateAllEventCounts = `-- name: AggregateAllEventCounts :many

SELECT asset_id, kind, COUNT(*) AS cnt
FROM view_events
WHERE kind IN ('open', 'play')
GROUP BY asset_id, kind
`

type AggregateAllEventCountsRow struct {
	AssetID string
	Kind    string
	Cnt     int64
}

// AggregateAllEventCounts: whole-library view/play aggregation --
// the recompute source for daily materialized tables (adr/0005 cache)
// and leaderboard heat. On scoring-rule changes, rerun this query over
// the full history; the event stream itself never changes.
func (q *Queries) AggregateAllEventCounts(ctx context.Context) ([]AggregateAllEventCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, aggregateAllEventCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateAllEventCountsRow
	for rows.Next() {
		var i AggregateAllEventCountsRow
		if err := rows.Scan(&i.AssetID, &i.Kind, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAssetEvents = `-- name: CountAssetEvents :many

SELECT asset_id, kind, COUNT(*) AS cnt
FROM view_events
WHERE asset_id = ? AND kind IN ('open', 'play')
GROUP BY asset_id, kind
`

type CountAssetEventsRow struct {
	AssetID string
	Kind    string
	Cnt     int64
}

// CountAssetEvents: per-asset view/play counts (DOMAIN_RULES 5:
// aggregated from the event stream; dwell is not counted). At most two
// rows per asset (open/play) -- the caller assembles them. Empty result
// means never opened/played, not an error.
func (q *Queries) CountAssetEvents(ctx context.Context, assetID string) ([]CountAssetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, countAssetEvents, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAssetEventsRow
	for rows.Next() {
		var i CountAssetEventsRow
		if err := rows.Scan(&i.AssetID, &i.Kind, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenEventsAll = `-- name: CountOpenEventsAll :one

SELECT COUNT(*) FROM view_events WHERE kind = 'open'
`

// CountOpenEventsAll: lifetime open count (stats overview totalViews).
// view_events has no FK and may reference deleted assets (adr/0005);
// counting the stream directly is intentional -- deleted-asset history
// still counts as real views.
func (q *Queries) CountOpenEventsAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenEventsAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenEventsOnDay = `-- name: CountOpenEventsOnDay :one

SELECT COUNT(*) FROM view_events
WHERE kind = 'open' AND started_at >= ? AND started_at < ?
`

type CountOpenEventsOnDayParams struct {
	StartedAt   string
	StartedAt_2 string
}

// CountOpenEventsOnDay: open count within [dayStart, dayEnd) timestamp
// strings (stats overview todayViews; bounds built by the caller from
// the server clock's local calendar day, same format as started_at).
func (q *Queries) CountOpenEventsOnDay(ctx context.Context, arg CountOpenEventsOnDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenEventsOnDay, arg.StartedAt, arg.StartedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsViewEventOnDay = `-- name: ExistsViewEventOnDay :one

SELECT COUNT(*) FROM view_events
WHERE asset_id = ? AND kind = ? AND session_id = ?
  AND started_at >= ? AND started_at < ?
`

type ExistsViewEventOnDayParams struct {
	AssetID     string
	Kind        string
	SessionID   string
	StartedAt   string
	StartedAt_2 string
}

// ExistsViewEventOnDay: session-level dedup check (DOMAIN_RULES 5 --
// one open/play per asset+kind+session within the same local calendar
// day). dayStart/dayEnd are the UTC timestamp strings (store format,
// migrations/0001 header) of the event's local day 00:00 and next-day
// 00:00; the RFC3339 TEXT layout keeps lexicographic order ==
// chronological order, so the two-sided bound is exact. dwell never
// consults this query: dwell seconds always accumulate.
func (q *Queries) ExistsViewEventOnDay(ctx context.Context, arg ExistsViewEventOnDayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsViewEventOnDay,
		arg.AssetID,
		arg.Kind,
		arg.SessionID,
		arg.StartedAt,
		arg.StartedAt_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertViewEvent = `-- name: InsertViewEvent :exec


INSERT INTO view_events (asset_id, kind, session_id, started_at, seconds)
VALUES (?, ?, ?, ?, ?)
`

type InsertViewEventParams struct {
	AssetID   string
	Kind      string
	SessionID string
	StartedAt string
	Seconds   sql.NullInt64
}

// view_events queries (adr/0005: append-only, aggregate-only --
// UPDATE/DELETE must never appear in this file).
// ASCII-only comments here; see assets.sql header note and
// migrations/0001_init.up.sql for Chinese explanations.
// InsertViewEvent: the only write entry point. Session-level dedup
// (one open/play per session, DOMAIN_RULES 5) is decided server-side
// BEFORE the insert; the table has no unique constraint on purpose
// (adr/0005: scoring rules live in one place, not hidden in the schema).
func (q *Queries) InsertViewEvent(ctx context.Context, arg InsertViewEventParams) error {
	_, err := q.db.ExecContext(ctx, insertViewEvent,
		arg.AssetID,
		arg.Kind,
		arg.SessionID,
		arg.StartedAt,
		arg.Seconds,
	)
	return err
}

const listAllViewEvents = `-- name: ListAllViewEvents :many

SELECT asset_id, kind, session_id, started_at, seconds
FROM view_events
ORDER BY id
`

type ListAllViewEventsRow struct {
	AssetID   string
	Kind      string
	SessionID string
	StartedAt string
	Seconds   sql.NullInt64
}

// ListAllViewEvents: full-stream scan for the materialized-table
// rebuild (httpapi.RebuildAssetDailyStatsFromEvents). Append-only
// table, so id order == insertion order; seconds is NULL for open/play
// and only meaningful for dwell.
func (q *Queries) ListAllViewEvents(ctx context.Context) ([]ListAllViewEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllViewEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllViewEventsRow
	for rows.Next() {
		var i ListAllViewEventsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Kind,
			&i.SessionID,
			&i.StartedAt,
			&i.Seconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeOpenWindow = `-- name: SummarizeOpenWindow :one

SELECT CAST(COUNT(*) AS INTEGER) AS opens,
       CAST(COUNT(DISTINCT v.asset_id) AS INTEGER) AS files
FROM view_events v
JOIN assets a ON a.asset_id = v.asset_id
WHERE v.kind = 'open'
  AND (CAST(?1 AS TEXT) = '' OR v.started_at >= ?1)
`

type SummarizeOpenWindowRow struct {
	Opens int64
	Files int64
}

// SummarizeOpenWindow: numerator/denominator pair for the overview
// avgViewsPerFile field -- total opens vs DISTINCT assets with at least
// one open in the window (both restricted to live assets, DOMAIN_RULES
// 5: denominator 0 -> null is decided by the caller).
func (q *Queries) SummarizeOpenWindow(ctx context.Context, fromTs string) (SummarizeOpenWindowRow, error) {
	row := q.db.QueryRowContext(ctx, summarizeOpenWindow, fromTs)
	var i SummarizeOpenWindowRow
	err := row.Scan(&i.Opens, &i.Files)
	return i, err
}

const topDwellAssets = `-- name: TopDwellAssets :many

SELECT v.asset_id AS asset_id,
       a.file_name AS file_name,
       a.media_type AS media_type,
       CAST(COALESCE(SUM(v.seconds), 0) AS INTEGER) AS value
FROM view_events v
JOIN assets a ON a.asset_id = v.asset_id
WHERE v.kind = 'dwell'
  AND (CAST(?1 AS TEXT) = '' OR v.started_at >= ?1)
GROUP BY v.asset_id, a.file_name, a.media_type
ORDER BY value DESC, v.asset_id
LIMIT ?2
`

type TopDwellAssetsParams struct {
	FromTs string
	Lim    int64
}

type TopDwellAssetsRow struct {
	AssetID   string
	FileName  string
	MediaType string
	Value     int64
}

// TopDwellAssets: most-viewed by accumulated dwell seconds; files with
// no dwell event in the window simply do not appear (DOMAIN_RULES 5).
func (q *Queries) TopDwellAssets(ctx context.Context, arg TopDwellAssetsParams) ([]TopDwellAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, topDwellAssets, arg.FromTs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopDwellAssetsRow
	for rows.Next() {
		var i TopDwellAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.FileName,
			&i.MediaType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topOpenAssets = `-- name: TopOpenAssets :many


SELECT v.asset_id AS asset_id,
       a.file_name AS file_name,
       a.media_type AS media_type,
       CAST(COUNT(*) AS INTEGER) AS value
FROM view_events v
JOIN assets a ON a.asset_id = v.asset_id
WHERE v.kind = 'open'
  AND (CAST(?1 AS TEXT) = '' OR v.started_at >= ?1)
GROUP BY v.asset_id, a.file_name, a.media_type
ORDER BY value DESC, v.asset_id
LIMIT ?2
`

type TopOpenAssetsParams struct {
	FromTs string
	Lim    int64
}

type TopOpenAssetsRow struct {
	AssetID   string
	FileName  string
	MediaType string
	Value     int64
}

// ============ Stats top-lists (protocol batch P2, 2026-09-09) ============
// Windowed per-asset/author/tag aggregation straight from the event
// stream (single source of truth, DOMAIN_RULES 5). Window semantics:
// from_ts = RFC3339 timestamp string (store layout) of the window's
// first local-calendar-day 00:00; empty string = no window (range=all),
// same sentinel as media_type in daily_stats.sql. INNER JOIN assets on
// purpose: the ranking must render file info, so deleted-asset events
// (no FK, adr/0005) cannot appear here even though the overview still
// counts them. Tie-break = primary key ascending for stable ordering.
// TopOpenAssets: most-viewed by open count within the window.
func (q *Queries) TopOpenAssets(ctx context.Context, arg TopOpenAssetsParams) ([]TopOpenAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, topOpenAssets, arg.FromTs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopOpenAssetsRow
	for rows.Next() {
		var i TopOpenAssetsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.FileName,
			&i.MediaType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topOpenAuthors = `-- name: TopOpenAuthors :many

SELECT au.id AS author_id,
       au.display_name AS display_name,
       CAST(COUNT(*) AS INTEGER) AS views
FROM view_events v
JOIN assets a ON a.asset_id = v.asset_id
JOIN asset_authors aa ON aa.asset_id = a.asset_id
JOIN authors au ON au.id = aa.author_id
WHERE v.kind = 'open'
  AND (CAST(?1 AS TEXT) = '' OR v.started_at >= ?1)
GROUP BY au.id, au.display_name
ORDER BY views DESC, au.id
LIMIT ?2
`

type TopOpenAuthorsParams struct {
	FromTs string
	Lim    int64
}

type TopOpenAuthorsRow struct {
	AuthorID    string
	DisplayName string
	Views       int64
}

// TopOpenAuthors: per-author open count within the window. Many-to-many
// asset x author: one open counts once for EVERY linked author. COS
// authors are counted via their COS-linked assets only (asset_authors
// holds no regular links for them -- prefix isolation, DOMAIN_RULES 6).
func (q *Queries) TopOpenAuthors(ctx context.Context, arg TopOpenAuthorsParams) ([]TopOpenAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, topOpenAuthors, arg.FromTs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopOpenAuthorsRow
	for rows.Next() {
		var i TopOpenAuthorsRow
		if err := rows.Scan(&i.AuthorID, &i.DisplayName, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topOpenTags = `-- name: TopOpenTags :many

SELECT t.name AS tag,
       CAST(COUNT(*) AS INTEGER) AS views
FROM view_events v
JOIN assets a ON a.asset_id = v.asset_id
JOIN asset_tags atg ON atg.asset_id = a.asset_id
JOIN tags t ON t.id = atg.tag_id
WHERE v.kind = 'open'
  AND (CAST(?1 AS TEXT) = '' OR v.started_at >= ?1)
GROUP BY t.id, t.name
ORDER BY views DESC, t.name
LIMIT ?2
`

type TopOpenTagsParams struct {
	FromTs string
	Lim    int64
}

type TopOpenTagsRow struct {
	Tag   string
	Views int64
}

// TopOpenTags: per-tag open count within the window (tagged assets).
func (q *Queries) TopOpenTags(ctx context.Context, arg TopOpenTagsParams) ([]TopOpenTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, topOpenTags, arg.FromTs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopOpenTagsRow
	for rows.Next() {
		var i TopOpenTagsRow
		if err := rows.Scan(&i.Tag, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
